import { readFileSync, readdirSync } from "node:fs";
import { randomUUID } from "node:crypto";
import { fileURLToPath } from "node:url";
import { afterAll, beforeAll, expect, it } from "vitest";
import { createDatabaseClient, type DatabaseClient } from "@steam-top/db";
import { AdminAuthService } from "./admin-auth";
import { PostgresAdminStore } from "./postgres-admin-store";
import { tokenHash } from "./admin-session";
import { postgresTestSchemaUrl } from "../postgres-test-url";

const databaseUrl = process.env.TEST_DATABASE_URL; const schemaName = `admin_${randomUUID().replaceAll("-", "")}`; let client: DatabaseClient;
function barrier(participants: number) { let arrived = 0; let release!: () => void; const ready = new Promise<void>((resolve) => { release = resolve; }); return async () => { arrived++; if (arrived === participants) release(); await ready; }; }
beforeAll(async () => { if (!databaseUrl) return; const local = /(?:localhost|127\.0\.0\.1)/u.test(databaseUrl); client = createDatabaseClient({ url: postgresTestSchemaUrl(databaseUrl, schemaName), ssl: local ? false : "require", allowInsecure: local, maxConnections: 20 }); await client.sql.unsafe(`create schema ${schemaName}`); await client.sql.unsafe(`set search_path to ${schemaName},public`); const directory = fileURLToPath(new URL("../../../../drizzle", import.meta.url)); for (const file of readdirSync(directory).filter((name) => name.endsWith(".sql")).sort()) for (const statement of readFileSync(`${directory}/${file}`, "utf8").split("--> statement-breakpoint").map((value) => value.trim()).filter(Boolean)) if(!statement.includes('"restore_control"'))await client.sql.unsafe(statement.replaceAll('"public".', `"${schemaName}".`)); }, 30_000);
afterAll(async () => { if (!client) return; await client.sql.unsafe("set search_path to public"); await client.sql.unsafe(`drop schema ${schemaName} cascade`); await client.close(); });

it.skipIf(!databaseUrl)("bootstraps concurrently once and never overwrites the first credential", async () => { const store = new PostgresAdminStore(client.db); const services = Array.from({ length: 5 }, () => new AdminAuthService(store, { allowedOrigins: ["https://example.test"] })); await Promise.all(services.map((service) => service.bootstrap("admin", "first-password"))); await services[0]!.bootstrap("admin", "other-password"); const valid = await Promise.all(services.map((service) => service.verifyPassword("admin", "first-password"))); expect(valid.every(Boolean)).toBe(true); expect(await services[0]!.verifyPassword("admin", "other-password")).toBe(false); });

it.skipIf(!databaseUrl)("atomically revokes and never revives an idle session", async () => { let now = new Date("2026-08-29T00:00:00Z"); const store = new PostgresAdminStore(client.db); const auth = new AdminAuthService(store, { now: () => now, allowedOrigins: ["https://example.test"] }); await auth.bootstrap("race-admin", "race-password"); const login = await auth.login("race-admin", "race-password", { clientKey: "127.0.0.1" }); if (login.status !== "ok") throw new Error("login failed"); now = new Date(now.getTime() + 30 * 60_000); await Promise.allSettled([auth.authenticate(login.token), store.revokeSession(login.session.tokenHash, now)]); expect(await auth.authenticate(login.token)).toBeNull(); });

it.skipIf(!databaseUrl)("enforces unique session token hashes", async () => { const now = new Date(); const store = new PostgresAdminStore(client.db); const owner = await store.createUserIfAbsent({ username: "unique-admin", passwordHash: "argon-placeholder" }); const input = { adminUserId: owner.id, tokenHash: "a".repeat(64), csrfTokenHash: "b".repeat(64), createdAt: now, lastSeenAt: now, absoluteExpiresAt: new Date(now.getTime() + 1_000) }; await store.createSession(input); await expect(store.createSession(input)).rejects.toThrow(); });

it.skipIf(!databaseUrl)("serializes twenty distributed login attempts so only five reach credential failure", async () => { const store = new PostgresAdminStore(client.db); const bootstrap = new AdminAuthService(store, { allowedOrigins: ["https://example.test"], csrfSecret: Buffer.alloc(32, 2) }); await bootstrap.bootstrap("limited-admin", "correct-password"); const services = Array.from({ length: 20 }, () => new AdminAuthService(store, { allowedOrigins: ["https://example.test"], csrfSecret: Buffer.alloc(32, 2) })); const results = await Promise.all(services.map((service) => service.login("limited-admin", "wrong-password", { clientKey: "shared-proxy" }))); expect(results.filter((item) => item.status === "invalid")).toHaveLength(5); expect(results.filter((item) => item.status === "locked")).toHaveLength(15); }, 30_000);

it.skipIf(!databaseUrl)("keeps audit append-only and consumes a purpose-bound grant exactly once", async () => { const now = new Date(); const store = new PostgresAdminStore(client.db); const auth = new AdminAuthService(store, { allowedOrigins: ["https://example.test"], csrfSecret: Buffer.alloc(32, 3), now: () => now }); await auth.bootstrap("grant-admin", "grant-password"); const login = await auth.login("grant-admin", "grant-password", { clientKey: "grant-client" }); if (login.status !== "ok") throw new Error("login failed"); const current = await auth.authenticate(login.token, false); const grant = await auth.reauthenticate(login.token, current!.csrfToken, "grant-password", "delete", { clientKey: "grant-client" }); expect(grant).toBeTruthy(); expect(await auth.consumeReauthGrant(login.token, grant!, "other")).toBe(false); expect(await auth.consumeReauthGrant(login.token, grant!, "delete")).toBe(true); expect(await auth.consumeReauthGrant(login.token, grant!, "delete")).toBe(false); await expect(client.sql`update admin_audit set action='tampered' where action='admin.reauth.issued'`).rejects.toThrow(/append-only/u); await expect(client.sql`delete from admin_audit where action='admin.reauth.issued'`).rejects.toThrow(/append-only/u); });

it.skipIf(!databaseUrl)("durably queues and idempotently drains a success audit", async () => {
  const store = new PostgresAdminStore(client.db);
  await store.queueAudit({ action: "match.persistence.retry", outcome: "success", details: { matchId: crypto.randomUUID() } });
  expect(await store.pumpAuditOutbox(new Date("2099-01-01"), 10)).toBe(1);
  expect(await store.pumpAuditOutbox(new Date("2099-01-01"), 10)).toBe(0);
});

it.skipIf(!databaseUrl)("disabling an admin atomically prevents later session and grant use", async () => { const now = new Date(); const store = new PostgresAdminStore(client.db); const auth = new AdminAuthService(store, { allowedOrigins: ["https://example.test"], csrfSecret: Buffer.alloc(32, 4), now: () => now }); const owner = await auth.bootstrap("disabled-admin", "disabled-password"); const login = await auth.login("disabled-admin", "disabled-password", { clientKey: "disabled-client" }); if (login.status !== "ok") throw new Error("login failed"); const current = await auth.authenticate(login.token, false); const grant = await auth.reauthenticate(login.token, current!.csrfToken, "disabled-password", "delete", { clientKey: "disabled-client" }); await store.setUserActive(owner.id, false, now); expect(await auth.authenticate(login.token, false)).toBeNull(); expect(await auth.consumeReauthGrant(login.token, grant!, "delete")).toBe(false); });

it.skipIf(!databaseUrl)("linearizes revoke against one-time grant consumption across connections", async () => { const now = new Date(); const storeA = new PostgresAdminStore(client.db); const storeB = new PostgresAdminStore(client.db); const auth = new AdminAuthService(storeA, { allowedOrigins: ["https://example.test"], csrfSecret: Buffer.alloc(32, 5), now: () => now }); await auth.bootstrap("revoke-consume-admin", "race-password"); const login = await auth.login("revoke-consume-admin", "race-password", { clientKey: "race" }); if (login.status !== "ok") throw new Error("login failed"); const current = await auth.authenticate(login.token, false); const grant = await auth.reauthenticate(login.token, current!.csrfToken, "race-password", "delete", { clientKey: "race" }); const start = barrier(2); const [revoke, consume] = await Promise.all([start().then(() => storeA.revokeSession(login.session.tokenHash, now)), start().then(() => storeB.consumeReauthGrant({ tokenHash: tokenHash(grant!), adminUserId: login.user.id, adminSessionId: login.session.id, purpose: "delete", now }))]); expect(revoke).toBe(true); expect([true, false]).toContain(consume); expect(await auth.consumeReauthGrant(login.token, grant!, "delete")).toBe(false); expect(await auth.authenticate(login.token, false)).toBeNull(); });

it.skipIf(!databaseUrl)("linearizes disable against grant and session creation", async () => { const now = new Date(); const storeA = new PostgresAdminStore(client.db); const storeB = new PostgresAdminStore(client.db); const owner = await storeA.createUserIfAbsent({ username: "disable-create-admin", passwordHash: "argon-placeholder" }); const sessionInput = { adminUserId: owner.id, tokenHash: "c".repeat(64), csrfTokenHash: "d".repeat(64), createdAt: now, lastSeenAt: now, absoluteExpiresAt: new Date(now.getTime() + 60_000) }; const start = barrier(2); const [disabled, created] = await Promise.allSettled([start().then(() => storeA.setUserActive(owner.id, false, now)), start().then(() => storeB.createSession(sessionInput))]); expect(disabled.status).toBe("fulfilled"); if (created.status === "fulfilled") expect(await storeA.findSession(sessionInput.tokenHash)).toBeNull(); else expect(String(created.reason)).toMatch(/INACTIVE/u); await expect(storeB.createSession({ ...sessionInput, tokenHash: "e".repeat(64) })).rejects.toThrow(/INACTIVE/u); await expect(storeB.createReauthGrant({ tokenHash: "f".repeat(64), adminUserId: owner.id, adminSessionId: created.status === "fulfilled" ? created.value.id : randomUUID(), purpose: "delete", expiresAt: new Date(now.getTime() + 300_000) })).rejects.toThrow(/INACTIVE/u); });
