import { readFileSync, readdirSync } from "node:fs";
import { randomUUID } from "node:crypto";
import { fileURLToPath } from "node:url";
import { afterAll, beforeAll, expect, it } from "vitest";
import { createDatabaseClient, type DatabaseClient } from "@steam-top/db";
import { AdminAuthService } from "./admin-auth";
import { PostgresAdminStore } from "./postgres-admin-store";

const databaseUrl = process.env.TEST_DATABASE_URL; const schemaName = `admin_${randomUUID().replaceAll("-", "")}`; let client: DatabaseClient;
beforeAll(async () => { if (!databaseUrl) return; const local = /(?:localhost|127\.0\.0\.1)/u.test(databaseUrl); client = createDatabaseClient({ url: databaseUrl, ssl: local ? false : "require", allowInsecure: local, maxConnections: 20 }); await client.sql.unsafe(`create schema ${schemaName}`); await client.sql.unsafe(`set search_path to ${schemaName},public`); const directory = fileURLToPath(new URL("../../../../drizzle", import.meta.url)); for (const file of readdirSync(directory).filter((name) => name.endsWith(".sql")).sort()) for (const statement of readFileSync(`${directory}/${file}`, "utf8").split("--> statement-breakpoint").map((value) => value.trim()).filter(Boolean)) await client.sql.unsafe(statement); }, 30_000);
afterAll(async () => { if (!client) return; await client.sql.unsafe("set search_path to public"); await client.sql.unsafe(`drop schema ${schemaName} cascade`); await client.close(); });

it.skipIf(!databaseUrl)("bootstraps concurrently once and never overwrites the first credential", async () => { const store = new PostgresAdminStore(client.db); const services = Array.from({ length: 5 }, () => new AdminAuthService(store, { allowedOrigins: ["https://example.test"] })); await Promise.all(services.map((service) => service.bootstrap("admin", "first-password"))); await services[0]!.bootstrap("admin", "other-password"); const valid = await Promise.all(services.map((service) => service.verifyPassword("admin", "first-password"))); expect(valid.every(Boolean)).toBe(true); expect(await services[0]!.verifyPassword("admin", "other-password")).toBe(false); });

it.skipIf(!databaseUrl)("atomically revokes and never revives an idle session", async () => { let now = new Date("2026-08-29T00:00:00Z"); const store = new PostgresAdminStore(client.db); const auth = new AdminAuthService(store, { now: () => now, allowedOrigins: ["https://example.test"] }); await auth.bootstrap("race-admin", "race-password"); const login = await auth.login("race-admin", "race-password", { clientKey: "127.0.0.1" }); if (login.status !== "ok") throw new Error("login failed"); now = new Date(now.getTime() + 30 * 60_000); await Promise.allSettled([auth.authenticate(login.token), store.revokeSession(login.session.tokenHash, now)]); expect(await auth.authenticate(login.token)).toBeNull(); });

it.skipIf(!databaseUrl)("enforces unique session token hashes", async () => { const now = new Date(); const store = new PostgresAdminStore(client.db); const owner = await store.createUserIfAbsent({ username: "unique-admin", passwordHash: "argon-placeholder" }); const input = { adminUserId: owner.id, tokenHash: "a".repeat(64), csrfTokenHash: "b".repeat(64), createdAt: now, lastSeenAt: now, absoluteExpiresAt: new Date(now.getTime() + 1_000) }; await store.createSession(input); await expect(store.createSession(input)).rejects.toThrow(); });

it.skipIf(!databaseUrl)("serializes twenty distributed login attempts so only five reach credential failure", async () => { const store = new PostgresAdminStore(client.db); const bootstrap = new AdminAuthService(store, { allowedOrigins: ["https://example.test"], csrfSecret: Buffer.alloc(32, 2) }); await bootstrap.bootstrap("limited-admin", "correct-password"); const services = Array.from({ length: 20 }, () => new AdminAuthService(store, { allowedOrigins: ["https://example.test"], csrfSecret: Buffer.alloc(32, 2) })); const results = await Promise.all(services.map((service) => service.login("limited-admin", "wrong-password", { clientKey: "shared-proxy" }))); expect(results.filter((item) => item.status === "invalid")).toHaveLength(5); expect(results.filter((item) => item.status === "locked")).toHaveLength(15); }, 30_000);

it.skipIf(!databaseUrl)("keeps audit append-only and consumes a purpose-bound grant exactly once", async () => { const now = new Date(); const store = new PostgresAdminStore(client.db); const auth = new AdminAuthService(store, { allowedOrigins: ["https://example.test"], csrfSecret: Buffer.alloc(32, 3), now: () => now }); await auth.bootstrap("grant-admin", "grant-password"); const login = await auth.login("grant-admin", "grant-password", { clientKey: "grant-client" }); if (login.status !== "ok") throw new Error("login failed"); const current = await auth.authenticate(login.token, false); const grant = await auth.reauthenticate(login.token, current!.csrfToken, "grant-password", "delete", { clientKey: "grant-client" }); expect(grant).toBeTruthy(); expect(await auth.consumeReauthGrant(login.token, grant!, "other")).toBe(false); expect(await auth.consumeReauthGrant(login.token, grant!, "delete")).toBe(true); expect(await auth.consumeReauthGrant(login.token, grant!, "delete")).toBe(false); await expect(client.sql`update admin_audit set action='tampered' where action='admin.reauth.issued'`).rejects.toThrow(/append-only/u); await expect(client.sql`delete from admin_audit where action='admin.reauth.issued'`).rejects.toThrow(/append-only/u); });

it.skipIf(!databaseUrl)("disabling an admin atomically prevents later session and grant use", async () => { const now = new Date(); const store = new PostgresAdminStore(client.db); const auth = new AdminAuthService(store, { allowedOrigins: ["https://example.test"], csrfSecret: Buffer.alloc(32, 4), now: () => now }); const owner = await auth.bootstrap("disabled-admin", "disabled-password"); const login = await auth.login("disabled-admin", "disabled-password", { clientKey: "disabled-client" }); if (login.status !== "ok") throw new Error("login failed"); const current = await auth.authenticate(login.token, false); const grant = await auth.reauthenticate(login.token, current!.csrfToken, "disabled-password", "delete", { clientKey: "disabled-client" }); await store.setUserActive(owner.id, false, now); expect(await auth.authenticate(login.token, false)).toBeNull(); expect(await auth.consumeReauthGrant(login.token, grant!, "delete")).toBe(false); });
