FROM postgres:16.10-alpine3.22
COPY --chmod=755 infra/postgres/secure-entrypoint.sh /usr/local/bin/secure-entrypoint.sh
ENTRYPOINT ["secure-entrypoint.sh"]
CMD ["postgres", "-c", "ssl=on", "-c", "ssl_cert_file=/var/lib/postgresql/tls/server.crt", "-c", "ssl_key_file=/var/lib/postgresql/tls/server.key"]
