CREATE TABLE IF NOT EXISTS restore_control.platform_installation (
  singleton boolean PRIMARY KEY DEFAULT true CHECK (singleton),
  host_id text NOT NULL CHECK (host_id ~ '^[a-f0-9]{64}$'),
  bootstrap_digest text NOT NULL CHECK (bootstrap_digest ~ '^[a-f0-9]{64}$'),
  authorization_nonce text NOT NULL CHECK (authorization_nonce ~ '^[a-f0-9]{64}$'),
  claimed_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  generation bigint NOT NULL DEFAULT 1 CHECK (generation > 0),
  UNIQUE (host_id, bootstrap_digest, authorization_nonce)
);
CREATE OR REPLACE FUNCTION restore_control.assert_pristine_platform_installation() RETURNS void LANGUAGE plpgsql AS $$
DECLARE expected text[] := ARRAY['admin_audit','admin_audit_outbox','admin_command_operations','admin_login_limits','admin_reauth_grants','admin_sessions','admin_users','analytics_daily_summaries','battle_results','deletion_audit','deletion_ledger_outbox','deletion_operations','deletion_preview_designs','deletion_preview_identities','deletion_preview_matches','deletion_previews','design_event_snapshots','design_layers','designs','device_activity_days','identities','identity_links','identity_sessions','match_participant_snapshots','match_persistence_jobs','matches','platform_settings','room_event_snapshots','room_participants','room_projection_jobs','rooms','rounds','webclip_token_nonces'];actual text[];name text;rows bigint;
BEGIN SELECT array_agg(tablename ORDER BY tablename) INTO actual FROM pg_tables WHERE schemaname='public';IF actual IS DISTINCT FROM expected THEN RAISE EXCEPTION 'durable public schema drift';END IF;FOREACH name IN ARRAY expected LOOP EXECUTE format('LOCK TABLE public.%I IN SHARE MODE',name);IF name='platform_settings' THEN IF NOT EXISTS(SELECT 1 FROM platform_settings WHERE singleton AND NOT paused) OR (SELECT count(*) FROM platform_settings)<>1 THEN RAISE EXCEPTION 'platform settings baseline invalid';END IF;CONTINUE;END IF;EXECUTE format('SELECT count(*) FROM public.%I',name) INTO rows;IF rows<>0 THEN RAISE EXCEPTION 'durable table % is not pristine',name;END IF;END LOOP;IF (SELECT count(*) FROM restore_control.finalize_outbox)<>0 OR (SELECT count(*) FROM restore_control.promotion_outbox)<>0 OR (SELECT count(*) FROM restore_control.promotion_audit)<>0 THEN RAISE EXCEPTION 'restore control data is not pristine';END IF;IF NOT EXISTS(SELECT 1 FROM restore_control.deployment_environment WHERE singleton AND environment='production' AND NOT restore_allowed) OR (SELECT count(*) FROM restore_control.deployment_environment)<>1 THEN RAISE EXCEPTION 'deployment marker baseline invalid';END IF;END$$;
