import { mkdtemp,readFile,rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { afterEach,expect,it } from "vitest";
import { FileDeletionLedger } from "./deletion-ledger";
import { reconcileLedger,reconcileProductionDeletion } from "./deletion-ledger-cli";
process.env.DELETION_SOURCE_INSTANCE_ID="90000000-0000-4000-8000-000000000001";
const roots:string[]=[];afterEach(async()=>Promise.all(roots.splice(0).map(path=>rm(path,{recursive:true,force:true}))));
async function fixture(){const root=await mkdtemp(join(tmpdir(),"ledger-cli-"));roots.push(root);return new FileDeletionLedger(join(root,"private","ledger.log"));}
it("reconciles committed audits and explicitly confirmed rollbacks",async()=>{const ledger=await fixture(),input={auditId:"10000000-0000-4000-8000-000000000001",operationDigest:"a".repeat(64)};await ledger.recordPending(input);expect(await reconcileLedger({...input,ledger,confirmRolledBack:false,lookupAudit:async()=>({exists:true,sourceInstanceId:process.env.DELETION_SOURCE_INSTANCE_ID!})})).toBe("C");const second={auditId:"10000000-0000-4000-8000-000000000002",operationDigest:"b".repeat(64)};await ledger.recordPending(second);expect(await reconcileLedger({...second,ledger,confirmRolledBack:true,lookupAudit:async()=>({exists:false,sourceInstanceId:process.env.DELETION_SOURCE_INSTANCE_ID!}),authorizeRollback:async()=>true})).toBe("A");expect(await readFile(ledger.path,"utf8")).toContain(`C ${input.auditId}`);expect(await readFile(ledger.path,"utf8")).toContain(`A ${second.auditId}`);});
it("does not mutate the ledger when DB is unavailable or rollback is unconfirmed",async()=>{const ledger=await fixture(),input={auditId:"10000000-0000-4000-8000-000000000001",operationDigest:"a".repeat(64)};await ledger.recordPending(input);const before=await readFile(ledger.path,"utf8");await expect(reconcileLedger({...input,ledger,confirmRolledBack:false,lookupAudit:async()=>{throw new Error("offline");}})).rejects.toThrow("offline");await expect(reconcileLedger({...input,ledger,confirmRolledBack:false,lookupAudit:async()=>({exists:false,sourceInstanceId:process.env.DELETION_SOURCE_INSTANCE_ID!})})).rejects.toThrow(/CONFIRMATION/u);expect(await readFile(ledger.path,"utf8")).toBe(before);});
it("keeps every production reconciliation authority check in schema-qualified locked SQL",async()=>{const source=await readFile(fileURLToPath(new URL("./deletion-ledger-cli.ts",import.meta.url)),"utf8");for(const required of ["public.deletion_operations","for update of o","restore_control.deployment_environment","op.created_at<=now()-interval '15 minutes'","public.admin_reauth_grants","g.purpose='deletion_reconcile'","g.consumed_at is null","g.expires_at>now()","u.active","s.revoked_at is null","s.archived_at is null","s.expires_at>now()","s.last_seen_at>now()-interval '30 minutes'","s.created_at>now()-interval '12 hours'","public.deletion_ledger_outbox","on conflict(audit_id,terminal)","public.admin_audit"]){expect(source).toContain(required);}expect(source).not.toContain("set search_path");});
it("runs database decision, durable ledger append, then database completion through the exported core",async()=>{const ledger=await fixture(),input={auditId:"10000000-0000-4000-8000-000000000003",operationDigest:"c".repeat(64),sourceInstanceId:process.env.DELETION_SOURCE_INSTANCE_ID!};await ledger.recordPending(input);const events:string[]=[];expect(await reconcileProductionDeletion({tombstone:input,ledger,confirmedRollback:true,grantHash:"d".repeat(64),database:{decide:async()=>{events.push("decide");return {terminal:"A",sourceInstanceId:input.sourceInstanceId};},complete:async({terminal})=>{events.push(`complete:${terminal}`);}}})).toBe("A");expect(events).toEqual(["decide","complete:A"]);expect(await readFile(ledger.path,"utf8")).toContain(`A ${input.auditId}`);});
it("leaves the outbox pending when append fails and retries without a new grant",async()=>{const input={auditId:"10000000-0000-4000-8000-000000000004",operationDigest:"d".repeat(64),sourceInstanceId:process.env.DELETION_SOURCE_INSTANCE_ID!},events:string[]=[];let fail=true;const ledger={recoverCommitted:async()=>{events.push("append");if(fail){fail=false;throw new Error("disk full");}},recoverAborted:async()=>{throw new Error("unexpected");}};const database={decide:async()=>{events.push("decide");return {terminal:"C" as const,sourceInstanceId:input.sourceInstanceId};},complete:async()=>{events.push("complete");}};await expect(reconcileProductionDeletion({tombstone:input,ledger:ledger as never,confirmedRollback:false,grantHash:"",database})).rejects.toThrow("disk full");await expect(reconcileProductionDeletion({tombstone:input,ledger:ledger as never,confirmedRollback:false,grantHash:"",database})).resolves.toBe("C");expect(events).toEqual(["decide","append","decide","append","complete"]);});
