import { execFile } from "node:child_process";
import { createHash,randomUUID } from "node:crypto";
import { readFileSync,readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";
import { createDatabaseClient,type DatabaseClient } from "@steam-top/db";
import { afterAll,beforeAll,expect,it } from "vitest";
import { PsqlReconciliationDatabaseRunner,reconcileProductionDeletion,type ReconciliationTombstone } from "./deletion-ledger-cli";

const databaseUrl=process.env.TEST_DATABASE_URL,run=promisify(execFile);let client:DatabaseClient,sourceInstanceId="";
const psql=async(sql:string,extraEnv:NodeJS.ProcessEnv={})=>(await run("psql",[databaseUrl!,"-X","-v","ON_ERROR_STOP=1","-Atqc",sql],{env:{...process.env,...extraEnv}})).stdout;
const runner=()=>new PsqlReconciliationDatabaseRunner(psql);
beforeAll(async()=>{if(!databaseUrl)return;client=createDatabaseClient({url:databaseUrl,ssl:false,allowInsecure:true,maxConnections:10});const exists=(await client.sql.unsafe("select to_regclass('public.deletion_operations') value"))[0]?.value;if(!exists){const directory=fileURLToPath(new URL("../../../../drizzle",import.meta.url));const restoreControlExists=Boolean((await client.sql.unsafe("select to_regnamespace('restore_control') value"))[0]?.value);for(const file of readdirSync(directory).filter(name=>name.endsWith(".sql")).sort())for(const statement of readFileSync(`${directory}/${file}`,"utf8").split("--> statement-breakpoint").map(value=>value.trim()).filter(Boolean))if(!restoreControlExists||!statement.includes('"restore_control"'))await client.sql.unsafe(statement);}sourceInstanceId=String((await client.sql.unsafe("select restore_target_id from restore_control.deployment_environment where singleton"))[0]?.restore_target_id);},30_000);
afterAll(async()=>{if(client)await client.close();});

async function authority(overrides:Readonly<{active?:boolean;revoked?:boolean;archived?:boolean;idle?:boolean;absolute?:boolean;expiredSession?:boolean;expiredGrant?:boolean;purpose?:string;consumed?:boolean}>={}){const user=randomUUID(),session=randomUUID(),token=randomUUID(),hash=createHash("sha256").update(token).digest("hex");await client.sql.unsafe("insert into public.admin_users(id,username,password_hash,active) values($1,$2,'hash',$3)",[user,`u-${user}`,overrides.active??true]);await client.sql.unsafe(`insert into public.admin_sessions(id,admin_user_id,token_hash,csrf_token_hash,created_at,last_seen_at,expires_at,revoked_at,archived_at) values($1,$2,$3,$4,case when $5 then now()-interval '13 hours' else now()-interval '1 hour' end,case when $6 then now()-interval '31 minutes' else now() end,case when $7 then now()-interval '1 second' else now()+interval '1 hour' end,case when $8 then now() else null end,case when $9 then now() else null end)`,[session,user,createHash("sha256").update(session).digest("hex"),createHash("sha256").update(user).digest("hex"),overrides.absolute??false,overrides.idle??false,overrides.expiredSession??false,overrides.revoked||overrides.archived||false,overrides.archived??false]);await client.sql.unsafe("insert into public.admin_reauth_grants(admin_user_id,admin_session_id,token_hash,purpose,created_at,expires_at,consumed_at) values($1,$2,$3,$4,now()-interval '1 minute',case when $5 then now()-interval '1 second' else now()+interval '4 minutes' end,case when $6 then now() else null end)",[user,session,hash,overrides.purpose??"deletion_reconcile",overrides.expiredGrant??false,overrides.consumed??false]);return {hash,user,session};}
async function operation(status:"pending"|"committed"="pending",source=sourceInstanceId,digest="a".repeat(64)){const tombstone={auditId:randomUUID(),operationDigest:digest,sourceInstanceId:source};await client.sql.unsafe("insert into public.deletion_operations(audit_id,source_instance_id,operation_digest,status,created_at,terminal_at) values($1,$2,$3,$4,now()-interval '20 minutes',case when $4='committed' then now() else null end)",[tombstone.auditId,source,digest,status]);return tombstone;}
const ledger=()=>({recoverCommitted:async()=>{},recoverAborted:async()=>{}});

it.skipIf(!databaseUrl)("reconciles an aged pending operation with one grant and persists accepted/success audits",async()=>{const tombstone=await operation(),auth=await authority();expect(await reconcileProductionDeletion({tombstone,ledger:ledger() as never,confirmedRollback:true,grantHash:auth.hash,database:runner()})).toBe("A");expect((await client.sql.unsafe("select status from public.deletion_operations where audit_id=$1",[tombstone.auditId]))[0]?.status).toBe("aborted");expect((await client.sql.unsafe("select action from public.admin_audit where target_id=$1 order by id",[tombstone.auditId])).map(row=>row.action)).toEqual(["deletion.ledger.reconcile.accepted","deletion.ledger.reconcile.success"]);});
it.skipIf(!databaseUrl)("recovers a committed operation without consuming a grant",async()=>{const tombstone=await operation("committed");expect(await reconcileProductionDeletion({tombstone,ledger:ledger() as never,confirmedRollback:false,grantHash:"",database:runner()})).toBe("C");expect((await client.sql.unsafe("select terminal,completed_at is not null done from public.deletion_ledger_outbox where audit_id=$1",[tombstone.auditId]))[0]).toMatchObject({terminal:"C",done:true});});

it.skipIf(!databaseUrl).each([
  ["disabled admin",{active:false}], ["revoked session",{revoked:true}], ["archived session",{archived:true}], ["idle session",{idle:true}], ["absolute session",{absolute:true}], ["expired session",{expiredSession:true}], ["expired grant",{expiredGrant:true}], ["wrong purpose",{purpose:"record_delete"}], ["consumed grant",{consumed:true}],
] as const)("rejects %s authority",async(_label,override)=>{const tombstone=await operation(),auth=await authority(override);await expect(reconcileProductionDeletion({tombstone,ledger:ledger() as never,confirmedRollback:true,grantHash:auth.hash,database:runner()})).rejects.toThrow("ROLLBACK_GRANT_REQUIRED");expect((await client.sql.unsafe("select status from public.deletion_operations where audit_id=$1",[tombstone.auditId]))[0]?.status).toBe("pending");});
it.skipIf(!databaseUrl)("rejects source mismatch and same audit id with a different digest",async()=>{const mismatch=await operation("pending",randomUUID()),auth=await authority();await expect(reconcileProductionDeletion({tombstone:mismatch,ledger:ledger() as never,confirmedRollback:true,grantHash:auth.hash,database:runner()})).rejects.toThrow("SOURCE_INSTANCE_MISMATCH");const saved=await operation(),corrupt={...saved,operationDigest:"f".repeat(64)};await expect(reconcileProductionDeletion({tombstone:corrupt,ledger:ledger() as never,confirmedRollback:true,grantHash:(await authority()).hash,database:runner()})).rejects.toThrow("DIGEST_CORRUPTION");});
it.skipIf(!databaseUrl)("uses public authority under a malicious search_path",async()=>{const tombstone=await operation("committed");const hostile=new PsqlReconciliationDatabaseRunner(sql=>psql(sql,{PGOPTIONS:"-c search_path=pg_catalog"}));await expect(reconcileProductionDeletion({tombstone,ledger:ledger() as never,confirmedRollback:false,grantHash:"",database:hostile})).resolves.toBe("C");});
it.skipIf(!databaseUrl)("keeps outbox pending on append failure and completes retry without another grant",async()=>{const tombstone=await operation(),auth=await authority();let failed=false;const flaky={recoverCommitted:async()=>{},recoverAborted:async()=>{if(!failed){failed=true;throw new Error("disk full");}}};await expect(reconcileProductionDeletion({tombstone,ledger:flaky as never,confirmedRollback:true,grantHash:auth.hash,database:runner()})).rejects.toThrow("disk full");expect((await client.sql.unsafe("select completed_at from public.deletion_ledger_outbox where audit_id=$1",[tombstone.auditId]))[0]?.completed_at).toBeNull();await expect(reconcileProductionDeletion({tombstone,ledger:flaky as never,confirmedRollback:false,grantHash:"",database:runner()})).resolves.toBe("A");expect((await client.sql.unsafe("select completed_at from public.deletion_ledger_outbox where audit_id=$1",[tombstone.auditId]))[0]?.completed_at).toBeInstanceOf(Date);});
it.skipIf(!databaseUrl)("recovers when the completion commit response is uncertain",async()=>{const tombstone=await operation("committed"),base=runner();let uncertain=true;const database={decide:base.decide.bind(base),complete:async(input:Parameters<typeof base.complete>[0])=>{await base.complete(input);if(uncertain){uncertain=false;throw new Error("ECONNRESET");}}};await expect(reconcileProductionDeletion({tombstone,ledger:ledger() as never,confirmedRollback:false,grantHash:"",database})).rejects.toThrow("ECONNRESET");await expect(reconcileProductionDeletion({tombstone,ledger:ledger() as never,confirmedRollback:false,grantHash:"",database})).resolves.toBe("C");expect((await client.sql.unsafe("select count(*)::int count from public.admin_audit where target_id=$1 and action='deletion.ledger.reconcile.success'",[tombstone.auditId]))[0]?.count).toBe(1);});
it.skipIf(!databaseUrl)("serializes delete commit before reconcile A through the operation row lock",async()=>{const tombstone=await operation(),auth=await authority();let locked!:()=>void,release!:()=>void;const hasLock=new Promise<void>(resolve=>{locked=resolve;}),gate=new Promise<void>(resolve=>{release=resolve;});const commit=client.sql.begin(async tx=>{await tx.unsafe("select audit_id from public.deletion_operations where audit_id=$1 for update",[tombstone.auditId]);locked();await gate;await tx.unsafe("update public.deletion_operations set status='committed',terminal_at=now() where audit_id=$1",[tombstone.auditId]);});await hasLock;let settled=false;const reconcile=reconcileProductionDeletion({tombstone,ledger:ledger() as never,confirmedRollback:true,grantHash:auth.hash,database:runner()}).then(value=>{settled=true;return value;});await new Promise(resolve=>setTimeout(resolve,50));expect(settled).toBe(false);release();await commit;expect(await reconcile).toBe("C");expect((await client.sql.unsafe("select consumed_at from public.admin_reauth_grants where token_hash=$1",[auth.hash]))[0]?.consumed_at).toBeNull();});
it.skipIf(!databaseUrl)("keeps reconcile A authoritative when a delete commit arrives second",async()=>{const tombstone=await operation(),auth=await authority();expect(await reconcileProductionDeletion({tombstone,ledger:ledger() as never,confirmedRollback:true,grantHash:auth.hash,database:runner()})).toBe("A");const changed=await client.sql.unsafe("update public.deletion_operations set status='committed',terminal_at=now() where audit_id=$1 and status='pending' returning audit_id",[tombstone.auditId]);expect(changed).toHaveLength(0);expect((await client.sql.unsafe("select status from public.deletion_operations where audit_id=$1",[tombstone.auditId]))[0]?.status).toBe("aborted");});
