import { createHash, randomUUID } from "node:crypto";
import { constants } from "node:fs";
import { chmod, lstat, mkdir, open, readFile, rename, rm, stat, writeFile } from "node:fs/promises";
import { dirname, isAbsolute } from "node:path";

export interface DeletionLedger { recordPending(input: Readonly<{ auditId: string; operationDigest: string }>): Promise<void>; recordCommitted(input: Readonly<{ auditId: string; operationDigest: string }>): Promise<void>; recordAborted(input: Readonly<{ auditId: string; operationDigest: string }>): Promise<void>; }
type Lease = Readonly<{ token: string; heartbeatAt: number }>;

/** External append-only tombstones make backups predating a deletion ineligible for restore. */
export class FileDeletionLedger {
  constructor(readonly path: string, private readonly leaseMs = 30_000) { if (!isAbsolute(path)) throw new TypeError("DELETION_LEDGER_FILE_MUST_BE_ABSOLUTE");if(!Number.isSafeInteger(leaseMs)||leaseMs<100)throw new TypeError("INVALID_DELETION_LEDGER_LEASE"); }
  async #privateDirectory() { const directory=dirname(this.path);await mkdir(directory,{recursive:true,mode:0o700});const info=await lstat(directory);if(!info.isDirectory()||info.isSymbolicLink()||info.uid!==process.getuid?.())throw new Error("UNSAFE_DELETION_LEDGER_DIRECTORY");await chmod(directory,0o700);return directory; }
  async #writeLease(lock:string,lease:Lease){const temporary=`${lock}/.owner-${lease.token}`;await writeFile(temporary,JSON.stringify(lease),{flag:"wx",mode:0o600});await rename(temporary,`${lock}/owner`);const directory=await open(lock,constants.O_RDONLY);try{await directory.sync();}finally{await directory.close();}}
  async #readLease(lock:string){return JSON.parse(await readFile(`${lock}/owner`,"utf8")) as Lease;}
  async #lock(directory:string){const lock=`${this.path}.lock`,token=randomUUID();for(let attempt=0;attempt<500;attempt++){try{await mkdir(lock,{mode:0o700});await this.#writeLease(lock,{token,heartbeatAt:Date.now()});let lost=false,renewing=false;const heartbeat=setInterval(()=>{if(renewing||lost)return;renewing=true;void (async()=>{try{const current=await this.#readLease(lock);if(current.token!==token){lost=true;return;}await this.#writeLease(lock,{token,heartbeatAt:Date.now()});}catch{lost=true;}finally{renewing=false;}})();},Math.max(50,Math.floor(this.leaseMs/3)));heartbeat.unref();return async()=>{clearInterval(heartbeat);if(lost)throw new Error("DELETION_LEDGER_LEASE_LOST");const current=await this.#readLease(lock);if(current.token!==token)throw new Error("DELETION_LEDGER_LEASE_LOST");const released=`${lock}.released-${token}`;await rename(lock,released);await rm(released,{recursive:true});const parent=await open(directory,constants.O_RDONLY);try{await parent.sync();}finally{await parent.close();}};}catch(error){if((error as NodeJS.ErrnoException).code!=="EEXIST")throw error;try{const info=await lstat(lock);if(!info.isDirectory()||info.isSymbolicLink()||info.uid!==process.getuid?.()||(info.mode&0o077)!==0)throw new Error("UNSAFE_DELETION_LEDGER_LOCK");let lease:Lease|undefined;try{lease=await this.#readLease(lock);}catch(error){if((error as NodeJS.ErrnoException).code!=="ENOENT"&&!(error instanceof SyntaxError))throw error;}const heartbeatAt=typeof lease?.heartbeatAt==="number"?lease.heartbeatAt:info.mtimeMs;if(Date.now()-heartbeatAt>this.leaseMs){const stale=`${lock}.stale-${randomUUID()}`;try{await rename(lock,stale);await rm(stale,{recursive:true});continue;}catch(reclaimError){if((reclaimError as NodeJS.ErrnoException).code!=="ENOENT")throw reclaimError;}}}catch(staleError){if((staleError as NodeJS.ErrnoException).code!=="ENOENT")throw staleError;}await new Promise(resolve=>setTimeout(resolve,10));}}throw new Error("DELETION_LEDGER_LOCK_TIMEOUT");}
  async #withLock<T>(operation:()=>Promise<T>){const directory=await this.#privateDirectory(),release=await this.#lock(directory);try{return await operation();}finally{await release();}}
  async #validate(){try{const info=await lstat(this.path);if(!info.isFile()||info.isSymbolicLink()||info.uid!==process.getuid?.()||(info.mode&0o077)!==0||info.size>64*1024*1024)throw new Error("UNSAFE_DELETION_LEDGER");}catch(error){if((error as NodeJS.ErrnoException).code!=="ENOENT")throw error;}}
  async #readSafe(){const file=await open(this.path,constants.O_RDONLY|constants.O_NOFOLLOW);try{const fd=await file.stat(),pathInfo=await stat(this.path);if(!fd.isFile()||fd.uid!==process.getuid?.()||(fd.mode&0o077)!==0||fd.ino!==pathInfo.ino||fd.dev!==pathInfo.dev)throw new Error("UNSAFE_DELETION_LEDGER");return await file.readFile();}finally{await file.close();}}
  async #record(state:"P"|"C"|"A",input:{auditId:string;operationDigest:string}){if(!/^[0-9a-f-]{36}$/iu.test(input.auditId)||!/^[a-f0-9]{64}$/u.test(input.operationDigest))throw new TypeError("INVALID_DELETION_TOMBSTONE");await this.#withLock(async()=>{await this.#validate();const line=`${state} ${input.auditId.toLowerCase()} ${input.operationDigest}\n`;try{if((await this.#readSafe()).toString("utf8").split("\n").includes(line.trimEnd()))return;}catch(error){if((error as NodeJS.ErrnoException).code!=="ENOENT")throw error;}const file=await open(this.path,constants.O_WRONLY|constants.O_APPEND|constants.O_CREAT|constants.O_NOFOLLOW,0o600);try{const fd=await file.stat(),pathInfo=await stat(this.path);if(!fd.isFile()||fd.uid!==process.getuid?.()||(fd.mode&0o077)!==0||fd.ino!==pathInfo.ino||fd.dev!==pathInfo.dev)throw new Error("UNSAFE_DELETION_LEDGER");await file.write(line);await file.datasync();await file.chmod(0o600);}finally{await file.close();}const parent=await open(dirname(this.path),constants.O_RDONLY);try{await parent.sync();}finally{await parent.close();}});}
  async snapshot(destination:string){if(!isAbsolute(destination))throw new TypeError("DELETION_LEDGER_SNAPSHOT_MUST_BE_ABSOLUTE");return this.#withLock(async()=>{await this.#validate();const content=await this.#readSafe();const output=await open(destination,constants.O_WRONLY|constants.O_CREAT|constants.O_EXCL|constants.O_NOFOLLOW,0o600);try{await output.writeFile(content);await output.sync();}finally{await output.close();}const parent=await open(dirname(destination),constants.O_RDONLY);try{await parent.sync();}finally{await parent.close();}return Object.freeze({lines:content.length===0?0:content.toString("utf8").split("\n").filter(Boolean).length,sha256:createHash("sha256").update(content).digest("hex")});});}
  recordPending(input:{auditId:string;operationDigest:string}){return this.#record("P",input);}recordCommitted(input:{auditId:string;operationDigest:string}){return this.#record("C",input);}recordAborted(input:{auditId:string;operationDigest:string}){return this.#record("A",input);}
}
