import { createHash, randomUUID } from "node:crypto";
import { execFile } from "node:child_process";
import { constants, type Stats } from "node:fs";
import { chmod, lstat as rawLstat, mkdir, open, readFile, rename, rm, stat, writeFile } from "node:fs/promises";
import { dirname, isAbsolute } from "node:path";
import { promisify } from "node:util";

export interface DeletionLedger { recordPending(input: Readonly<{ auditId: string; operationDigest: string }>): Promise<void>; recordCommitted(input: Readonly<{ auditId: string; operationDigest: string }>): Promise<void>; recordAborted(input: Readonly<{ auditId: string; operationDigest: string }>):Promise<void>;recoverCommitted?(input:Readonly<{auditId:string;operationDigest:string}>):Promise<void>; }
type LockOwner = Readonly<{ token: string; pid: number; processStart: string }>;
export interface ProcessIdentityProvider { current():Promise<Readonly<{pid:number;processStart:string}>>;inspect(pid:number):Promise<Readonly<{alive:boolean;processStart?:string}>>; }
const executeFile=promisify(execFile);
const lstat=async(path:string):Promise<Stats>=>{try{return await rawLstat(path);}catch(error){if((error as NodeJS.ErrnoException).code==="ENOENT"&&path.endsWith(".lock"))return{isDirectory:()=>true,isSymbolicLink:()=>false,uid:process.getuid?.(),mode:0} as Stats;throw error;}};
export function parseLinuxProcessStart(statContent:string){const close=statContent.lastIndexOf(")");if(close<0)throw new Error("PROCESS_STAT_INVALID");const fields=statContent.slice(close+1).trim().split(/\s+/u),value=fields[19];if(!value||!/^[0-9]+$/u.test(value))throw new Error("PROCESS_START_UNAVAILABLE");return value;}
export const systemProcessIdentity:ProcessIdentityProvider={async current(){const inspected=await this.inspect(process.pid);if(!inspected.alive||!inspected.processStart)throw new Error("PROCESS_IDENTITY_UNAVAILABLE");return{pid:process.pid,processStart:inspected.processStart};},async inspect(pid){if(pid<=0)return{alive:false};try{process.kill(pid,0);}catch(error){if((error as NodeJS.ErrnoException).code==="ESRCH")return{alive:false};throw error;}if(process.platform==="linux")return{alive:true,processStart:parseLinuxProcessStart(await readFile(`/proc/${pid}/stat`,"utf8"))};if(process.platform!=="darwin")throw new Error("PROCESS_IDENTITY_PLATFORM_UNSUPPORTED");const {stdout}=await executeFile("ps",["-p",String(pid),"-o","lstart="]);const value=stdout.trim();if(!value)throw new Error("PROCESS_START_UNAVAILABLE");return{alive:true,processStart:value};}};
export function validateLedgerContent(content:Buffer,requireResolved=false){const states=new Map<string,{sourceInstanceId:string;digest:string;terminal?:"C"|"A"}>();const lines=content.toString("utf8").split("\n");if(lines.at(-1)!=="")throw new Error("INVALID_DELETION_LEDGER_LINE");for(const line of lines.slice(0,-1)){const pending=/^P ([0-9a-f-]{36}) ([0-9a-f-]{36}) ([a-f0-9]{64})$/u.exec(line),terminal=/^([CA]) ([0-9a-f-]{36}) ([a-f0-9]{64})$/u.exec(line);if(pending){const auditId=pending[1]!,sourceInstanceId=pending[2]!,digest=pending[3]!;if(states.has(auditId))throw new Error("DUPLICATE_DELETION_PENDING");states.set(auditId,{sourceInstanceId,digest});continue;}if(!terminal)throw new Error("INVALID_DELETION_LEDGER_LINE");const kind=terminal[1] as "C"|"A",auditId=terminal[2]!,digest=terminal[3]!,state=states.get(auditId);if(!state)throw new Error("ORPHAN_DELETION_TERMINAL");if(state.digest!==digest)throw new Error("DELETION_DIGEST_MISMATCH");if(state.terminal)throw new Error("DUPLICATE_OR_CONFLICTING_DELETION_TERMINAL");state.terminal=kind;}if(requireResolved&&[...states.values()].some(state=>!state.terminal))throw new Error("UNRESOLVED_DELETION_PENDING");return states;}

/** External append-only tombstones make backups predating a deletion ineligible for restore. */
export class FileDeletionLedger {
  constructor(readonly path: string, private readonly processIdentity:ProcessIdentityProvider=systemProcessIdentity,private readonly sourceInstanceId=process.env.DELETION_SOURCE_INSTANCE_ID) { if (!isAbsolute(path)) throw new TypeError("DELETION_LEDGER_FILE_MUST_BE_ABSOLUTE");if(sourceInstanceId!==undefined&&!/^[0-9a-f-]{36}$/iu.test(sourceInstanceId))throw new TypeError("INVALID_SOURCE_INSTANCE_ID"); }
  async #privateDirectory() { const directory=dirname(this.path);await mkdir(directory,{recursive:true,mode:0o700});const info=await lstat(directory);if(!info.isDirectory()||info.isSymbolicLink()||info.uid!==process.getuid?.())throw new Error("UNSAFE_DELETION_LEDGER_DIRECTORY");await chmod(directory,0o700);return directory; }
  async #readOwner(lock:string){for(let attempt=0;attempt<5;attempt++)try{const owner=JSON.parse(await readFile(`${lock}/owner`,"utf8")) as Partial<LockOwner>;if(typeof owner.token!=="string"||!Number.isSafeInteger(owner.pid)||typeof owner.processStart!=="string"||!owner.processStart)throw new Error("INVALID_DELETION_LEDGER_LOCK_OWNER");return owner as LockOwner;}catch(error){if((error as NodeJS.ErrnoException).code!=="ENOENT")throw error;await new Promise(resolve=>setTimeout(resolve,5));}return{token:"missing",pid:-1,processStart:"missing"};}
  async #lock(directory:string){const lock=`${this.path}.lock`,token=randomUUID(),self=await this.processIdentity.current();for(let attempt=0;attempt<500;attempt++){try{await mkdir(lock,{mode:0o700});await writeFile(`${lock}/owner`,JSON.stringify({token,...self}),{flag:"wx",mode:0o600});return async()=>{const owner=await this.#readOwner(lock);if(owner.token!==token)throw new Error("DELETION_LEDGER_LOCK_OWNERSHIP_LOST");const released=`${lock}.released-${token}`;await rename(lock,released);await rm(released,{recursive:true});const parent=await open(directory,constants.O_RDONLY);try{await parent.sync();}finally{await parent.close();}};}catch(error){if((error as NodeJS.ErrnoException).code!=="EEXIST")throw error;const info=await lstat(lock);if(!info.isDirectory()||info.isSymbolicLink()||info.uid!==process.getuid?.()||(info.mode&0o077)!==0)throw new Error("UNSAFE_DELETION_LEDGER_LOCK");let owner:LockOwner;try{owner=await this.#readOwner(lock);}catch(ownerError){if((ownerError as NodeJS.ErrnoException).code==="ENOENT"&&attempt<10){await new Promise(resolve=>setTimeout(resolve,10));continue;}throw ownerError;}const inspected=await this.processIdentity.inspect(owner.pid);if(!inspected.alive||inspected.processStart!==owner.processStart){const stale=`${lock}.stale-${randomUUID()}`;try{await rename(lock,stale);await rm(stale,{recursive:true});continue;}catch(reclaimError){if((reclaimError as NodeJS.ErrnoException).code!=="ENOENT")throw reclaimError;}}await new Promise(resolve=>setTimeout(resolve,10));}}throw new Error("DELETION_LEDGER_LOCK_TIMEOUT");}
  async #withLock<T>(operation:()=>Promise<T>){const directory=await this.#privateDirectory(),release=await this.#lock(directory);try{return await operation();}finally{await release();}}
  async #validate(){try{const info=await lstat(this.path);if(!info.isFile()||info.isSymbolicLink()||info.uid!==process.getuid?.()||(info.mode&0o077)!==0||info.size>64*1024*1024)throw new Error("UNSAFE_DELETION_LEDGER");}catch(error){if((error as NodeJS.ErrnoException).code!=="ENOENT")throw error;}}
  async #readSafe(){const file=await open(this.path,constants.O_RDONLY|constants.O_NOFOLLOW);try{const fd=await file.stat(),pathInfo=await stat(this.path);if(!fd.isFile()||fd.uid!==process.getuid?.()||(fd.mode&0o077)!==0||fd.ino!==pathInfo.ino||fd.dev!==pathInfo.dev)throw new Error("UNSAFE_DELETION_LEDGER");return await file.readFile();}finally{await file.close();}}
  async #record(state:"P"|"C"|"A",input:{auditId:string;operationDigest:string}){if(!/^[0-9a-f-]{36}$/iu.test(input.auditId)||!/^[a-f0-9]{64}$/u.test(input.operationDigest))throw new TypeError("INVALID_DELETION_TOMBSTONE");await this.#withLock(async()=>{await this.#validate();let content=Buffer.alloc(0);try{content=await this.#readSafe();}catch(error){if((error as NodeJS.ErrnoException).code!=="ENOENT")throw error;}const states=validateLedgerContent(content),auditId=input.auditId.toLowerCase(),current=states.get(auditId);if(state==="P"?Boolean(current)||!this.sourceInstanceId:!current||current.digest!==input.operationDigest||Boolean(current.terminal))throw new Error("INVALID_DELETION_LEDGER_TRANSITION");const line=state==="P"?`P ${auditId} ${this.sourceInstanceId!.toLowerCase()} ${input.operationDigest}\n`:`${state} ${auditId} ${input.operationDigest}\n`;const file=await open(this.path,constants.O_WRONLY|constants.O_APPEND|constants.O_CREAT|constants.O_NOFOLLOW,0o600);try{const fd=await file.stat(),pathInfo=await stat(this.path);if(!fd.isFile()||fd.uid!==process.getuid?.()||(fd.mode&0o077)!==0||fd.ino!==pathInfo.ino||fd.dev!==pathInfo.dev)throw new Error("UNSAFE_DELETION_LEDGER");await file.write(line);await file.datasync();await file.chmod(0o600);}finally{await file.close();}const parent=await open(dirname(this.path),constants.O_RDONLY);try{await parent.sync();}finally{await parent.close();}});}
  async snapshot(destination:string,requireResolved=false){if(!isAbsolute(destination))throw new TypeError("DELETION_LEDGER_SNAPSHOT_MUST_BE_ABSOLUTE");return this.#withLock(async()=>{await this.#validate();const content=await this.#readSafe();validateLedgerContent(content,requireResolved);const output=await open(destination,constants.O_WRONLY|constants.O_CREAT|constants.O_EXCL|constants.O_NOFOLLOW,0o600);try{await output.writeFile(content);await output.sync();}finally{await output.close();}const parent=await open(dirname(destination),constants.O_RDONLY);try{await parent.sync();}finally{await parent.close();}return Object.freeze({lines:content.length===0?0:content.toString("utf8").split("\n").filter(Boolean).length,sha256:createHash("sha256").update(content).digest("hex")});});}
  async recoverCommitted(input:{auditId:string;operationDigest:string}){try{await this.recordCommitted(input);}catch(error){if(!(error instanceof Error)||error.message!=="INVALID_DELETION_LEDGER_TRANSITION")throw error;await this.#withLock(async()=>{const state=validateLedgerContent(await this.#readSafe()).get(input.auditId.toLowerCase());if(state?.digest!==input.operationDigest||state.terminal!=="C")throw error;});}}
  async holdLock(readyPath:string,until:Promise<void>){if(!isAbsolute(readyPath))throw new TypeError("LEDGER_GUARD_READY_MUST_BE_ABSOLUTE");const directory=await this.#privateDirectory(),release=await this.#lock(directory),ready=await open(readyPath,constants.O_WRONLY|constants.O_CREAT|constants.O_EXCL|constants.O_NOFOLLOW,0o600);try{await ready.writeFile("ready\n");await ready.sync();}finally{await ready.close();}const readyDirectory=await open(dirname(readyPath),constants.O_RDONLY);try{await readyDirectory.sync();}finally{await readyDirectory.close();}try{await until;}finally{await rm(readyPath,{force:true});await release();}}
  recordPending(input:{auditId:string;operationDigest:string}){return this.#record("P",input);}recordCommitted(input:{auditId:string;operationDigest:string}){return this.#record("C",input);}recordAborted(input:{auditId:string;operationDigest:string}){return this.#record("A",input);}
}
