import { randomUUID } from "node:crypto";
import { readFileSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { afterAll, beforeAll, expect, it } from "vitest";
import { createDatabaseClient, type DatabaseClient } from "@steam-top/db";
import { PostgresAdminRecordsSource } from "./records-routes";
import { postgresTestSchemaUrl } from "../postgres-test-url";

const databaseUrl=process.env.TEST_DATABASE_URL,schemaName=`leaderboard_${randomUUID().replaceAll("-","")}`;let client:DatabaseClient,source:PostgresAdminRecordsSource;
const ids={canonicalA:randomUUID(),oldA:randomUUID(),b:randomUUID(),c:randomUUID(),d:randomUUID(),star:randomUUID(),hex:randomUUID(),circle:randomUUID(),triangle:randomUUID(),room:randomUUID()};
async function addDesign(id:string,owner:string,shape:"star"|"polygon"|"circle",points=8) {await client.sql.unsafe("insert into designs(id,logical_design_id,owner_identity_id,version,schema_version,name,screw_count,screw_radius_mm,screw_rotation_deg,metal_disc_diameter_mm,total_mass_g,polar_moment_gmm2,center_of_mass_x_mm,center_of_mass_y_mm,performance_speed,performance_spin_duration,performance_stability,performance_impact_resistance,performance_model_version,battle_eligible,validation_issues) values($1,$1,$2,1,'1','fixture',6,12,0,30,40,12000,0,0,60,60,60,60,'perf-1',false,'[]')",[id,owner]);const positions=["top","middle","bottom"] as const;for(let order=0;order<3;order++)await client.sql.unsafe("insert into design_layers(design_id,source_layer_id,layer_order,position,shape,points,diameter_mm,actual_area_mm2,corner_roundness,rotation_deg,color) values($1,$2,$3,$4,$5,$6,50,1500,0.2,0,'#123456')",[id,`${id}-${order}`,order,positions[order]!,shape,points]);await client.sql`update designs set battle_eligible=true where id=${id}`;}
async function addMatch(input:{at:string,p1:string,p2:string,d1:string,d2:string,n1:string,n2:string,c1:string,c2:string,device1:string,device2:string,challenge1:number,challenge2:number,status?:"completed"|"in_progress"}){const match=randomUUID(),status=input.status??"completed";await client.sql.unsafe("insert into matches(id,room_id,idempotency_fingerprint,status,player1_identity_id,player2_identity_id,player1_design_id,player2_design_id,player1_device_name,player2_device_name,performance_model_version,physics_model_version,protocol_version,started_at) values($1,$2,$3,'in_progress',$4,$5,$6,$7,$8,$9,'perf-1','physics-1',1,$10::timestamptz-interval '1 minute')",[match,ids.room,randomUUID().replaceAll("-","").padEnd(64,"0"),input.p1,input.p2,input.d1,input.d2,input.device1,input.device2,input.at]);await client.sql.unsafe("insert into match_participant_snapshots(match_id,slot,identity_id_at_start,canonical_identity_id_at_start,identity_status_snapshot,class_name_snapshot,display_name_snapshot,design_id,captured_at) values($1,'player1',$2,$3,'iclass',$4,$5,$6,$10::timestamptz-interval '1 minute'),($1,'player2',$7,$7,'iclass',$8,$9,$11,$10::timestamptz-interval '1 minute')",[match,input.p1,input.p1===ids.oldA?ids.canonicalA:input.p1,input.c1,input.n1,input.d1,input.p2,input.c2,input.n2,input.d2,input.at]);if(status==="completed")await client.sql.unsafe("update matches set status='completed',player1_battle_points=2,player2_battle_points=0,player1_challenge_points=$2,player2_challenge_points=$3,player1_total=2+$2,player2_total=$3,winner='player1',round_winners='[\"player1\",\"player1\"]',completed_at=$4 where id=$1",[match,input.challenge1,input.challenge2,input.at]);}

beforeAll(async()=>{if(!databaseUrl)return;const local=/(?:localhost|127\.0\.0\.1)/u.test(databaseUrl);client=createDatabaseClient({url:postgresTestSchemaUrl(databaseUrl,schemaName),ssl:local?false:"require",allowInsecure:local,maxConnections:10});await client.sql.unsafe(`create schema ${schemaName}`);await client.sql.unsafe(`set search_path to ${schemaName},public`);const directory=fileURLToPath(new URL("../../../../drizzle",import.meta.url));for(const file of readdirSync(directory).filter(name=>name.endsWith(".sql")).sort())for(const statement of readFileSync(`${directory}/${file}`,"utf8").split("--> statement-breakpoint").map(value=>value.trim()).filter(Boolean))if(!statement.includes('"restore_control"'))await client.sql.unsafe(statement.replaceAll('"public".', `"${schemaName}".`).replaceAll("public.", `${schemaName}.`));
  const devices=[randomUUID(),randomUUID(),randomUUID(),randomUUID(),randomUUID()] as const;await client.sql.unsafe("insert into identities(id,status,display_name,class_name,anonymous_device_id) values($1,'iclass','Ada Latest','2B',$2),($3,'iclass','Ada Old','1A',$4),($5,'iclass','Ben','1B',$6),($7,'iclass','Cara','1C',$8),($9,'iclass','Dion','1D',$10)",[ids.canonicalA,devices[0],ids.oldA,devices[1],ids.b,devices[2],ids.c,devices[3],ids.d,devices[4]]);await client.sql`insert into rooms(id,code,name,owner_identity_id,status) values(${ids.room},'LBTEST','Leaderboard',${ids.canonicalA},'waiting')`;
  await addDesign(ids.star,ids.oldA,"star");await addDesign(ids.hex,ids.b,"polygon",6);await addDesign(ids.circle,ids.c,"circle");await addDesign(ids.triangle,ids.canonicalA,"polygon",3);
  await addMatch({at:"2026-08-01T04:00:00Z",p1:ids.oldA,p2:ids.b,d1:ids.star,d2:ids.hex,n1:"Ada Old",n2:"Ben",c1:"1A",c2:"1B",device1:"iPad-A",device2:"iPad-B",challenge1:.5,challenge2:.5});
  await addMatch({at:"2026-08-02T04:00:00Z",p1:ids.c,p2:ids.canonicalA,d1:ids.circle,d2:ids.triangle,n1:"Cara",n2:"Ada Latest",c1:"1C",c2:"2B",device1:"iPad-C",device2:"Mac-A",challenge1:.5,challenge2:.5});
  await addMatch({at:"2026-08-03T04:00:00Z",p1:ids.b,p2:ids.d,d1:ids.hex,d2:ids.circle,n1:"Ben",n2:"Dion",c1:"1B",c2:"1D",device1:"iPad-B",device2:"iPad-D",challenge1:.5,challenge2:.5});
  await addMatch({at:"2026-08-04T04:00:00Z",p1:ids.d,p2:ids.canonicalA,d1:ids.circle,d2:ids.triangle,n1:"Dion",n2:"Ada Latest",c1:"1D",c2:"2B",device1:"ignored",device2:"ignored",challenge1:.5,challenge2:.5,status:"in_progress"});source=new PostgresAdminRecordsSource(client.sql);
},30_000);
afterAll(async()=>{if(!client)return;await client.sql.unsafe("set search_path to public");await client.sql.unsafe(`drop schema ${schemaName} cascade`);await client.close();});

it.skipIf(!databaseUrl)("merges canonical identities, uses the latest event label, scores both slots and dense-ranks ties",async()=>{const page=await source.queryLeaderboard({page:1,pageSize:10});expect(page.total).toBe(4);expect(page.rows.map(row=>[row.displayName,row.rank,row.battleScore,row.challengeScore,row.totalScore,row.matches])).toEqual([["Ada Latest",1,2,1,3,2],["Ben",1,2,1,3,2],["Cara",2,2,.5,2.5,1],["Dion",3,0,.5,.5,1]]);expect(page.rows[0]).toMatchObject({identityId:ids.canonicalA,className:"2B"});},30_000);

it.skipIf(!databaseUrl)("applies date, class, identity, device and parameter filters to immutable participant events",async()=>{const base={page:1,pageSize:10};expect((await source.queryLeaderboard({...base,className:"1A"})).rows).toEqual([expect.objectContaining({identityId:ids.canonicalA,displayName:"Ada Old",className:"1A",totalScore:2.5})]);expect((await source.queryLeaderboard({...base,identity:"Ada Latest"})).rows).toEqual([expect.objectContaining({identityId:ids.canonicalA,totalScore:.5})]);expect((await source.queryLeaderboard({...base,device:"Mac-A"})).rows).toEqual([expect.objectContaining({identityId:ids.canonicalA,totalScore:.5})]);expect((await source.queryLeaderboard({...base,parameter:"star"})).rows).toEqual([expect.objectContaining({identityId:ids.canonicalA,totalScore:2.5})]);expect((await source.queryLeaderboard({...base,from:"2026-08-02",to:"2026-08-02",className:"2B",identity:"Latest",device:"Mac-A",parameter:"polygon"})).rows).toEqual([expect.objectContaining({identityId:ids.canonicalA,totalScore:.5})]);},30_000);

it.skipIf(!databaseUrl)("keeps deterministic pages and the true total on an empty page",async()=>{const first=await source.queryLeaderboard({page:1,pageSize:2}),second=await source.queryLeaderboard({page:2,pageSize:2}),empty=await source.queryLeaderboard({page:3,pageSize:2});expect(first.rows.map(row=>row.displayName)).toEqual(["Ada Latest","Ben"]);expect(second.rows.map(row=>row.displayName)).toEqual(["Cara","Dion"]);expect(empty).toMatchObject({rows:[],total:4,page:3,pageSize:2});},30_000);
