import type { DatabaseClient } from "@steam-top/db";
import type { FastifyInstance } from "fastify";
import { z } from "zod";
import { authenticateAdminRead, type AdminAuthService } from "../auth/admin-auth";
const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/u);
export const adminRecordFilters=z.object({page:z.coerce.number().int().min(1).max(100000).default(1),pageSize:z.coerce.number().int().min(1).max(100).default(25),from:date.optional(),to:date.optional(),className:z.string().trim().max(30).optional(),identity:z.string().trim().max(80).optional(),device:z.string().trim().max(128).optional(),parameter:z.string().trim().max(128).optional()}).strict().refine(x=>!x.from||!x.to||x.from<=x.to,"INVALID_DATE_RANGE");
export type AdminRecordFilters=z.infer<typeof adminRecordFilters>;export type AdminRecordPage={rows:readonly Record<string,unknown>[];total:number;page:number;pageSize:number};export interface AdminRecordsSource{query(filters:AdminRecordFilters):Promise<AdminRecordPage>}
export class PostgresAdminRecordsSource implements AdminRecordsSource{constructor(private readonly sql:DatabaseClient["sql"]){ }async query(f:AdminRecordFilters){const offset=(f.page-1)*f.pageSize,pattern=(value:string|undefined)=>value?`%${value.replaceAll("%","\\%").replaceAll("_","\\_")}%`:null;const query=`select m.id,m.completed_at "occurredAt",coalesce(p.class_name_snapshot,i.class_name,'') "className",coalesce(i.display_name,'已刪除身份') identity,coalesce(case when p.slot='player1' then m.player1_device_name else m.player2_device_name end,'') "deviceName",coalesce(dl.parameters,'') parameters,coalesce(case when p.slot='player1' then m.player1_total else m.player2_total end,0)::float8 "totalScore",count(*) over()::integer total from matches m join match_participant_snapshots p on p.match_id=m.id left join identities i on i.id=coalesce(p.canonical_identity_id_at_start,p.identity_id_at_start) left join lateral(select string_agg(concat(shape,' ',diameter_mm,'mm'),' / ' order by layer_order) parameters from design_layers where design_id=p.design_id) dl on true where m.status='completed' and ($1::date is null or (m.completed_at at time zone 'Asia/Hong_Kong')::date >= $1::date) and ($2::date is null or (m.completed_at at time zone 'Asia/Hong_Kong')::date <= $2::date) and ($3::text is null or coalesce(p.class_name_snapshot,i.class_name,'') ilike $3 escape '\\') and ($4::text is null or coalesce(i.display_name,'') ilike $4 escape '\\') and ($5::text is null or coalesce(case when p.slot='player1' then m.player1_device_name else m.player2_device_name end,'') ilike $5 escape '\\') and ($6::text is null or coalesce(dl.parameters,'') ilike $6 escape '\\') order by m.completed_at desc,m.id,p.slot limit $7 offset $8`;const rows=await this.sql.unsafe(query,[f.from??null,f.to??null,pattern(f.className),pattern(f.identity),pattern(f.device),pattern(f.parameter),f.pageSize,offset]) as readonly Record<string,unknown>[];return{rows:rows.map(({total:_,...row})=>row),total:Number(rows[0]?.total??0),page:f.page,pageSize:f.pageSize}}}
export function registerAdminRecordRoutes(app:FastifyInstance,auth:AdminAuthService,source:AdminRecordsSource){app.get("/api/admin/records",async(request,reply)=>{if(!await authenticateAdminRead(request,reply,auth))return;const parsed=adminRecordFilters.safeParse(request.query);if(!parsed.success)return reply.code(400).send({error:"INVALID_RECORD_FILTERS"});reply.header("Cache-Control","private, no-store");try{return await source.query(parsed.data)}catch(error){auth.report("admin.records.query",error,request.id);return reply.code(503).send({error:"RECORDS_UNAVAILABLE"})}})}
