import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
const read=(p:string)=>readFileSync(p,"utf8");
describe("independently installed production bootstrap",()=>{
  it("is a small fixed root with externally pinned source trust",()=>{const install=read("infra/bootstrap/install-bootstrap.sh"),verify=read("infra/bootstrap/verify-bootstrap.sh");expect(install).toContain("EXPECTED_BOOTSTRAP_ARCHIVE_SHA256");expect(install).toContain("BOOTSTRAP_ALLOWED_SIGNERS_FILE");expect(install).toContain("/opt/steam-top-bootstrap");expect(verify).toContain("/etc/steam-top-bootstrap/trust.json");expect(verify).toContain("bootstrapSha256");expect(verify).toContain("root-owned exact mode");});
  it("builds a reproducible archive whose external digest can be rotated before release",()=>{const build=read("infra/bootstrap/create-package.sh");expect(build).toContain("--sort=name");expect(build).toContain("--mtime=@0");expect(build).toContain("gzip -n");});
  it("verifies protected workflow identity before installing a versioned runtime",()=>{const prepare=read("infra/bootstrap/prepare-release.sh"),identity=read("infra/bootstrap/verify-attestation-identity.mjs");expect(prepare).toContain("gh attestation verify");expect(prepare).toContain("--format json");expect(prepare).toContain("APPROVED-RELEASE.json");expect(prepare).toContain("runtime-files.sha256");expect(prepare).toContain('/opt/steam-top/releases/');expect(prepare).toContain("current.next");expect(identity).toContain("workflowRef");expect(identity).toContain("workflowSha");});
  it("production sudo invokes only the preinstalled bootstrap",()=>{const workflow=read(".github/workflows/record-deployment.yml"),docs=read("docs/operations/release.md");expect(workflow).toContain("/opt/steam-top-bootstrap/deploy-release.sh");expect(workflow).not.toContain("sudo DEPLOYMENT_AUTHORIZATION_PURPOSE=production /opt/steam-top/scripts/");expect(docs).toContain("/opt/steam-top-bootstrap");expect(docs).toContain("校方主機管理員");});
  it("stages the exact runtime files in the attested release artifact",()=>{const workflow=read(".github/workflows/ci.yml");expect(workflow).toContain("stage-runtime-files.mjs");expect(workflow).toContain("release/runtime");});
  it("publishes a signed bootstrap only from a protected default branch",()=>{const bootstrap=read(".github/workflows/bootstrap.yml");expect(bootstrap).toContain("push:");expect(bootstrap).toContain("branches:");expect(bootstrap).toContain("verify-environment-protection.mjs");expect(bootstrap).toContain("EXPECTED_BOOTSTRAP_ARCHIVE_SHA256");expect(bootstrap).toContain("BOOTSTRAP_SIGNING_KEY");expect(bootstrap).toContain("steam-top-bootstrap-source");expect(bootstrap).toContain("bootstrap.tgz.sig");});
  it("tag integration downloads and verifies the externally pinned bootstrap payload",()=>{const ci=read(".github/workflows/ci.yml"),bootstrap=read(".github/workflows/bootstrap.yml");expect(ci).toContain("BOOTSTRAP_RUN_ID");expect(ci).toContain("BOOTSTRAP_ARCHIVE_SHA256");expect(ci).toContain('name: "production-bootstrap-${{ vars.BOOTSTRAP_COMMIT }}"');expect(ci).toContain("gh attestation verify bootstrap/bootstrap.tgz");expect(ci).not.toContain("bootstrap/infra/bootstrap/install-bootstrap.sh");expect(ci).toContain("/usr/local/sbin/install-steam-top-bootstrap bootstrap/bootstrap.tgz");expect(bootstrap).not.toContain("infra/bootstrap/install-bootstrap.sh\n");});
  it("requires a separately provisioned pinned installer",()=>{const ci=read(".github/workflows/ci.yml"),docs=read("docs/operations/release.md");expect(ci).toContain("/usr/local/sbin/install-steam-top-bootstrap");expect(ci).toContain("INSTALLER_SHA256");expect(ci).toContain("steam-top-bootstrap-installer");expect(docs).toContain("INSTALLER_SHA256");expect(docs).toContain("主機 image provisioning");});
  it("requires the tag commit to be contained by the protected default branch",()=>{const ci=read(".github/workflows/ci.yml");expect(ci).toContain('compare/$RELEASE_COMMIT...$default_sha');expect(ci).toContain('"$ancestry" == ahead || "$ancestry" == identical');});
  it("seals protected state only from the signed monotonic host ledger",()=>{const activate=read("infra/bootstrap/activate-production-state.sh");expect(activate).toContain('deployment-ledger"');expect(activate).toContain("inspect-signed-generation-chain.mjs");expect(activate).toContain("steam-top-host-deployment-ledger");expect(activate).toContain("expectedPreviousState");expect(activate).toContain("ledger.previousState");});
});
