import {execFile,execFileSync,fork} from "node:child_process";
import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,chmodSync,symlinkSync,rmSync,renameSync,cpSync,statSync,readdirSync} from "node:fs";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {promisify} from "node:util";
import {afterEach,describe,expect,it} from "vitest";

const roots:string[]=[];
const execFileAsync=promisify(execFile);
afterEach(()=>{while(roots.length)rmSync(roots.pop()!,{recursive:true,force:true})});
function run(files:Record<string,string>){const root=mkdtempSync(join(tmpdir(),"deployment-policy-"));roots.push(root);const dir=join(root,".github/workflows");mkdirSync(dir,{recursive:true});for(const [name,text] of Object.entries(files))writeFileSync(join(dir,name),text);return()=>execFileSync(process.execPath,["scripts/verify-deployment-permissions.mjs",root],{stdio:"pipe"})}

describe("deployment permission policy",()=>{
  it("accepts the exact protected writer shapes and sole local caller",()=>expect(()=>execFileSync(process.execPath,["scripts/verify-deployment-permissions.mjs"],{stdio:"pipe"})).not.toThrow());
  for(const [name,yaml] of Object.entries({
    implicit:"jobs:\n  x: {runs-on: ubuntu-latest}\n",
    writeAll:"permissions: write-all\njobs:\n  x: {runs-on: ubuntu-latest}\n",
    quoted:"permissions: {contents: read}\njobs:\n  x:\n    permissions: {'deployments': 'write'}\n    runs-on: ubuntu-latest\n",
    override:"permissions: {deployments: write}\njobs:\n  x:\n    permissions: {contents: read, deployments: write}\n    runs-on: ubuntu-latest\n",
    dynamic:"permissions: {contents: read}\njobs:\n  x:\n    permissions: {deployments: '${{ matrix.permission }}'}\n    runs-on: ubuntu-latest\n",
    caller:"permissions: {contents: read}\njobs:\n  x:\n    uses: ./.github/workflows/ci.yml\n",
  }))it(`rejects ${name} permission form`,()=>expect(run({"evil.yml":yaml})).toThrow());
  it("resolves aliases before enforcing write-all",()=>expect(run({"evil.yml":"permissions: &p write-all\njobs:\n  x:\n    permissions: *p\n    runs-on: ubuntu-latest\n"})).toThrow());
  it("rejects same-repository or external remote reusable syntax",()=>expect(run({"evil.yml":"permissions: {}\njobs:\n  x:\n    uses: school/steam-top/.github/workflows/ci.yml@main\n"})).toThrow(/remote reusable workflows forbidden/));
  it("rejects an allowlisted writer when runs-on, steps, concurrency or bound command changes",()=>{const source=readFileSync(".github/workflows/reconcile-production-e2e.yml","utf8");for(const changed of [source.replace("runs-on: ubuntu-24.04","runs-on: arbitrary"),source.replaceAll("group: production-deployment-status-authority","group: other"),source.replace("Mark only orphaned matching Deployments terminal error","arbitrary writer command")])expect(run({"reconcile-production-e2e.yml":changed})).toThrow()});
  it("rejects workflow plus job lock re-entry",()=>{const source=readFileSync(".github/workflows/reconcile-production-e2e.yml","utf8").replace("permissions: { contents: read }","permissions: { contents: read }\nconcurrency: { group: production-deployment-status-authority, cancel-in-progress: false }");expect(run({"reconcile-production-e2e.yml":source})).toThrow(/workflow-level deployment authority lock forbidden/)});
  it("does not trust a candidate verifier changed alongside its writer",()=>{const source=readFileSync(".github/workflows/reconcile-production-e2e.yml","utf8").replace("runs-on: ubuntu-24.04","runs-on: attacker");expect(run({"reconcile-production-e2e.yml":source,"candidate-verifier.yml":"permissions: {}\njobs: {}\n"})).toThrow(/protected writer job shape mismatch/)});
  it("uses canonical Git modes and gives a fresh clone the same digest",()=>{const root=mkdtempSync(join(tmpdir(),"policy-bundle-")),clone=mkdtempSync(join(tmpdir(),"policy-clone-"));roots.push(root,clone);mkdirSync(join(root,"scripts"),{recursive:true});writeFileSync(join(root,"scripts/authority.sh"),"#!/bin/sh\nexit 0\n");chmodSync(join(root,"scripts/authority.sh"),0o755);writeFileSync(join(root,"drizzle.config.ts"),"export default {}\n");writeFileSync(join(root,".npmrc"),"strict-peer-dependencies=true\n");execFileSync("git",["init","-q",root]);execFileSync("git",["-C",root,"config","user.email","test@example.invalid"]);execFileSync("git",["-C",root,"config","user.name","test"]);execFileSync("git",["-C",root,"add","-A"]);execFileSync("git",["-C",root,"commit","-qm","fixture"]);chmodSync(join(root,"scripts/authority.sh"),0o555);chmodSync(join(root,".npmrc"),0o444);const digest=()=>execFileSync(process.execPath,["scripts/verify-production-policy-bundle.mjs",root],{encoding:"utf8",stdio:"pipe"}).trim(),trusted=digest();chmodSync(join(root,"scripts/authority.sh"),0o755);chmodSync(join(root,".npmrc"),0o644);expect(digest()).toBe(trusted);execFileSync("git",["clone","-q",root,clone]);expect(execFileSync(process.execPath,["scripts/verify-production-policy-bundle.mjs",clone],{encoding:"utf8"}).trim()).toBe(trusted);chmodSync(join(root,"scripts/authority.sh"),0o644);expect(digest).toThrow(/clean HEAD required/);execFileSync("git",["-C",root,"update-index","--chmod=-x","scripts/authority.sh"]);expect(digest).toThrow(/clean HEAD required/)});
  it("rejects unstaged, staged, renamed and ignored paths before hashing",()=>{const root=mkdtempSync(join(tmpdir(),"policy-dirty-"));roots.push(root);mkdirSync(join(root,"scripts/nested"),{recursive:true});writeFileSync(join(root,"scripts/authority.sh"),"#!/bin/sh\n");chmodSync(join(root,"scripts/authority.sh"),0o755);writeFileSync(join(root,".gitignore"),"ignored-root\nignored-nested/\n");execFileSync("git",["init","-q",root]);execFileSync("git",["-C",root,"config","user.email","test@example.invalid"]);execFileSync("git",["-C",root,"config","user.name","test"]);execFileSync("git",["-C",root,"add","-A"]);execFileSync("git",["-C",root,"commit","-qm","fixture"]);const verify=()=>execFileSync(process.execPath,["scripts/verify-production-policy-bundle.mjs",root],{stdio:"pipe"});writeFileSync(join(root,"scripts/authority.sh"),"changed\n");expect(verify).toThrow(/clean HEAD required/);execFileSync("git",["-C",root,"checkout","--","scripts/authority.sh"]);writeFileSync(join(root,"scripts/authority.sh"),"staged\n");execFileSync("git",["-C",root,"add","scripts/authority.sh"]);expect(verify).toThrow(/clean HEAD required/);execFileSync("git",["-C",root,"reset","--hard","-q","HEAD"]);renameSync(join(root,"scripts/authority.sh"),join(root,"scripts/renamed.sh"));execFileSync("git",["-C",root,"add","-A"]);expect(verify).toThrow(/clean HEAD required/);execFileSync("git",["-C",root,"reset","--hard","-q","HEAD"]);for(const relative of ["ignored-root","ignored-nested/file"]){const target=join(root,relative);mkdirSync(join(target,".."),{recursive:true});writeFileSync(target,"ignored\n");expect(verify).toThrow(/clean HEAD required/);rmSync(target,{force:true})}mkdirSync(join(root,"ignored-nested"),{recursive:true});symlinkSync("../scripts/authority.sh",join(root,"ignored-nested/link"));expect(verify).toThrow(/clean HEAD required/);rmSync(join(root,"ignored-nested"),{recursive:true,force:true});mkdirSync(join(root,"ignored-nested"),{recursive:true});execFileSync("mkfifo",[join(root,"ignored-nested/pipe")]);expect(verify).toThrow(/clean HEAD required/)});
  it("rejects an unmerged index",()=>{const root=mkdtempSync(join(tmpdir(),"policy-unmerged-"));roots.push(root);writeFileSync(join(root,"file"),"base\n");execFileSync("git",["init","-q","-b","main",root]);execFileSync("git",["-C",root,"config","user.email","test@example.invalid"]);execFileSync("git",["-C",root,"config","user.name","test"]);execFileSync("git",["-C",root,"add","file"]);execFileSync("git",["-C",root,"commit","-qm","base"]);execFileSync("git",["-C",root,"checkout","-qb","other"]);writeFileSync(join(root,"file"),"other\n");execFileSync("git",["-C",root,"commit","-qam","other"]);execFileSync("git",["-C",root,"checkout","-q","main"]);writeFileSync(join(root,"file"),"main\n");execFileSync("git",["-C",root,"commit","-qam","main"]);expect(()=>execFileSync("git",["-C",root,"merge","other"],{stdio:"pipe"})).toThrow();expect(()=>execFileSync(process.execPath,["scripts/verify-production-policy-bundle.mjs",root],{stdio:"pipe"})).toThrow(/clean HEAD required|index/)});
  it("rejects a tracked symlink and a parent-directory symlink replacement",()=>{for(const replacement of ["tracked-link","parent-link"]){const root=mkdtempSync(join(tmpdir(),"policy-link-"));roots.push(root);mkdirSync(join(root,"authority"));writeFileSync(join(root,"authority/file"),"bytes\n");if(replacement==="tracked-link")symlinkSync("authority/file",join(root,"link"));execFileSync("git",["init","-q",root]);execFileSync("git",["-C",root,"config","user.email","test@example.invalid"]);execFileSync("git",["-C",root,"config","user.name","test"]);execFileSync("git",["-C",root,"add","-A"]);execFileSync("git",["-C",root,"commit","-qm","fixture"]);if(replacement==="parent-link"){renameSync(join(root,"authority"),join(root,"elsewhere"));symlinkSync("elsewhere",join(root,"authority"))}expect(()=>execFileSync(process.execPath,["scripts/verify-production-policy-bundle.mjs",root],{stdio:"pipe"})).toThrow(replacement==="tracked-link"?/rejects symlink/:/clean HEAD required/)}});
  it("rejects empty untracked and ignored directories omitted by porcelain",()=>{const root=mkdtempSync(join(tmpdir(),"policy-empty-dir-"));roots.push(root);writeFileSync(join(root,"tracked"),"bytes\n");writeFileSync(join(root,".gitignore"),"ignored/\n");execFileSync("git",["init","-q",root]);execFileSync("git",["-C",root,"add","-A"]);execFileSync("git",["-C",root,"commit","-qm","fixture"]);for(const name of ["untracked","ignored"]){mkdirSync(join(root,name));expect(()=>execFileSync(process.execPath,["scripts/verify-production-policy-bundle.mjs",root],{stdio:"pipe"})).toThrow(/clean HEAD required/);rmSync(join(root,name),{recursive:true})}});
  it("rejects untracked regular, symlink and FIFO entries",()=>{const root=mkdtempSync(join(tmpdir(),"policy-untracked-kind-"));roots.push(root);writeFileSync(join(root,"tracked"),"bytes\n");execFileSync("git",["init","-q",root]);execFileSync("git",["-C",root,"add","tracked"]);execFileSync("git",["-C",root,"commit","-qm","fixture"]);const verify=()=>execFileSync(process.execPath,["scripts/verify-production-policy-bundle.mjs",root],{stdio:"pipe"});writeFileSync(join(root,"extra"),"bytes\n");expect(verify).toThrow(/clean HEAD required/);rmSync(join(root,"extra"));symlinkSync("tracked",join(root,"extra"));expect(verify).toThrow(/clean HEAD required/);rmSync(join(root,"extra"));execFileSync("mkfifo",[join(root,"extra")]);expect(verify).toThrow(/clean HEAD required/)});
  it("rejects control and non-canonical index paths",()=>{for(const name of ["line\nbreak",process.platform==="linux"?Buffer.from([0x62,0x61,0x64,0xff]):null]){if(name===null)continue;const root=mkdtempSync(join(tmpdir(),"policy-path-"));roots.push(root);const pathName=Buffer.isBuffer(name)?Buffer.concat([Buffer.from(`${root}/`),name]):join(root,name);writeFileSync(pathName,"bytes\n");execFileSync("git",["init","-q",root]);execFileSync("git",["-C",root,"add","-A"]);execFileSync("git",["-C",root,"commit","-qm","fixture"]);expect(()=>execFileSync(process.execPath,["scripts/verify-production-policy-bundle.mjs",root],{stdio:"pipe"})).toThrow(/authority index path rejected/)}});
  it("refreshes sealed write-bit changes without a stat-cache false positive",()=>{const root=mkdtempSync(join(tmpdir(),"policy-refresh-"));roots.push(root);writeFileSync(join(root,"plain"),"plain\n");writeFileSync(join(root,"exec"),"#!/bin/sh\n");chmodSync(join(root,"exec"),0o755);execFileSync("git",["init","-q",root]);execFileSync("git",["-C",root,"add","-A"]);execFileSync("git",["-C",root,"commit","-qm","fixture"]);const digest=()=>execFileSync(process.execPath,["scripts/verify-production-policy-bundle.mjs",root],{encoding:"utf8",stdio:"pipe"}).trim(),expected=digest();for(let index=0;index<20;index++){chmodSync(join(root,"plain"),index%2?0o644:0o444);chmodSync(join(root,"exec"),index%2?0o755:0o555);expect(digest()).toBe(expected)}});
  it("keeps a file-protocol shallow snapshot valid after source objects disappear",()=>{const root=mkdtempSync(join(tmpdir(),"policy-source-")),base=mkdtempSync(join(tmpdir(),"policy-independent-")),clone=join(base,"repo");roots.push(root,base);writeFileSync(join(root,"tracked"),"immutable bytes\n");execFileSync("git",["init","-q",root]);execFileSync("git",["-C",root,"add","tracked"]);execFileSync("git",["-C",root,"commit","-qm","fixture"]);const commit=execFileSync("git",["-C",root,"rev-parse","HEAD"],{encoding:"utf8"}).trim(),blob=execFileSync("git",["-C",root,"rev-parse","HEAD:tracked"],{encoding:"utf8"}).trim();execFileSync("git",["init","-q",clone]);execFileSync("git",["-C",clone,"remote","add","origin",`file://${root}`]);execFileSync("git",["-C",clone,"fetch","-q","--depth=1","--no-tags","origin",commit]);execFileSync("git",["-C",clone,"checkout","--detach","-q","FETCH_HEAD"]);expect(()=>readFileSync(join(clone,".git/objects/info/alternates"))).toThrow();rmSync(join(root,".git/objects"),{recursive:true,force:true});expect(execFileSync("git",["-C",clone,"cat-file","blob",blob],{encoding:"utf8"})).toBe("immutable bytes\n");expect(execFileSync("git",["-C",clone,"hash-object","tracked"],{encoding:"utf8"}).trim()).toBe(blob)});
  it("leaves the original index byte-for-byte unchanged across concurrent verification",async()=>{const root=mkdtempSync(join(tmpdir(),"policy-index-copy-"));roots.push(root);writeFileSync(join(root,"tracked"),"bytes\n");execFileSync("git",["init","-q",root]);execFileSync("git",["-C",root,"add","tracked"]);execFileSync("git",["-C",root,"commit","-qm","fixture"]);chmodSync(join(root,"tracked"),0o444);const index=join(root,execFileSync("git",["-C",root,"rev-parse","--git-path","index"],{encoding:"utf8"}).trim()),before=readFileSync(index),beforeStat=statSync(index,{bigint:true});await Promise.all([1,2].map(()=>execFileAsync(process.execPath,["scripts/verify-production-policy-bundle.mjs",root],{timeout:15000})));const afterStat=statSync(index,{bigint:true});expect(readFileSync(index)).toEqual(before);expect([afterStat.dev,afterStat.ino,afterStat.size,afterStat.mtimeNs,afterStat.ctimeNs]).toEqual([beforeStat.dev,beforeStat.ino,beforeStat.size,beforeStat.mtimeNs,beforeStat.ctimeNs])});
  it("requires one full commit OID before printing any rotation command",()=>{const root=mkdtempSync(join(tmpdir(),"policy-helper-"));roots.push(root);mkdirSync(join(root,"scripts"));cpSync("scripts/print-production-policy-pin.sh",join(root,"scripts/print-production-policy-pin.sh"));cpSync("scripts/verify-production-policy-bundle.mjs",join(root,"scripts/verify-production-policy-bundle.mjs"));execFileSync("git",["init","-q",root]);execFileSync("git",["-C",root,"add","-A"]);execFileSync("git",["-C",root,"commit","-qm","fixture"]);const oid=execFileSync("git",["-C",root,"rev-parse","HEAD"],{encoding:"utf8"}).trim();for(const args of [[],[oid.slice(0,8)],["HEAD"]]){let succeeded=true,stdout="";try{stdout=execFileSync("bash",[join(root,"scripts/print-production-policy-pin.sh"),...args],{encoding:"utf8",stdio:"pipe"})}catch(error:any){succeeded=false;stdout=String(error.stdout??"")}expect(succeeded).toBe(false);expect(stdout).not.toContain("gh variable set")}const output=execFileSync("bash",[join(root,"scripts/print-production-policy-pin.sh"),oid],{encoding:"utf8",timeout:15000});expect(output).toContain(`Reviewed clean checkout commit: ${oid}`);expect(output).toContain("Reviewed bundle SHA-256:");expect(output).toContain("gh variable set PRODUCTION_POLICY_BUNDLE_SHA256")});
  it("rejects native SHA-256 repositories without promotion output",()=>{const root=mkdtempSync(join(tmpdir(),"policy-sha256-"));roots.push(root);try{execFileSync("git",["init","-q","--object-format=sha256",root],{stdio:"pipe"})}catch{return}mkdirSync(join(root,"scripts"));cpSync("scripts/print-production-policy-pin.sh",join(root,"scripts/print-production-policy-pin.sh"));cpSync("scripts/verify-production-policy-bundle.mjs",join(root,"scripts/verify-production-policy-bundle.mjs"));execFileSync("git",["-C",root,"add","-A"]);execFileSync("git",["-C",root,"commit","-qm","fixture"]);const oid=execFileSync("git",["-C",root,"rev-parse","HEAD"],{encoding:"utf8"}).trim();expect(oid).toHaveLength(64);let stdout="";try{stdout=execFileSync("bash",[join(root,"scripts/print-production-policy-pin.sh"),oid],{encoding:"utf8",stdio:"pipe"});throw new Error("SHA-256 helper unexpectedly succeeded")}catch(error:any){stdout=String(error.stdout??stdout)}expect(stdout).not.toContain("gh variable set");expect(()=>execFileSync(process.execPath,["scripts/verify-production-policy-bundle.mjs",root],{stdio:"pipe"})).toThrow(/SHA-1 repositories only/)});
  it("ignores hostile Git environment and user configuration",()=>{const root=mkdtempSync(join(tmpdir(),"policy-hostile-env-")),fake=mkdtempSync(join(tmpdir(),"policy-fake-path-")),home=mkdtempSync(join(tmpdir(),"policy-home-"));roots.push(root,fake,home);writeFileSync(join(root,"tracked"),"bytes\n");execFileSync("git",["init","-q",root]);execFileSync("git",["-C",root,"add","tracked"]);execFileSync("git",["-C",root,"commit","-qm","fixture"]);writeFileSync(join(fake,"git"),"#!/bin/sh\nexit 99\n");chmodSync(join(fake,"git"),0o755);writeFileSync(join(home,".gitconfig"),'[url "file:///attacker"]\n\tinsteadOf = file://\n');const run=(env?:NodeJS.ProcessEnv)=>execFileSync(process.execPath,["scripts/verify-production-policy-bundle.mjs",root],{encoding:"utf8",env}).trim(),expected=run();expect(run({...process.env,PATH:fake,HOME:home,GIT_DIR:"/invalid",GIT_WORK_TREE:"/invalid",GIT_COMMON_DIR:"/invalid",GIT_OBJECT_DIRECTORY:"/invalid",GIT_ALTERNATE_OBJECT_DIRECTORIES:"/invalid",GIT_CONFIG_COUNT:"1",GIT_CONFIG_KEY_0:"url.file:///attacker.insteadOf",GIT_CONFIG_VALUE_0:"file://",GIT_SSH_COMMAND:"false",GIT_ASKPASS:"false"})).toBe(expected)});
  it("runs the rotation helper through sanitized absolute tooling",()=>{const root=mkdtempSync(join(tmpdir(),"policy-helper-env-")),fake=mkdtempSync(join(tmpdir(),"policy-helper-path-"));roots.push(root,fake);mkdirSync(join(root,"scripts"));cpSync("scripts/print-production-policy-pin.sh",join(root,"scripts/print-production-policy-pin.sh"));cpSync("scripts/verify-production-policy-bundle.mjs",join(root,"scripts/verify-production-policy-bundle.mjs"));execFileSync("git",["init","-q",root]);execFileSync("git",["-C",root,"add","-A"]);execFileSync("git",["-C",root,"commit","-qm","fixture"]);const oid=execFileSync("git",["-C",root,"rev-parse","HEAD"],{encoding:"utf8"}).trim(),output=execFileSync("/bin/bash",[join(root,"scripts/print-production-policy-pin.sh"),oid],{encoding:"utf8",env:{...process.env,PATH:fake,HOME:fake,GIT_DIR:"/invalid",GIT_WORK_TREE:"/invalid",GIT_OBJECT_DIRECTORY:"/invalid",GIT_ALTERNATE_OBJECT_DIRECTORIES:"/invalid",GIT_CONFIG_COUNT:"1",GIT_CONFIG_KEY_0:"url.file:///attacker.insteadOf",GIT_CONFIG_VALUE_0:"file://"},timeout:15000});expect(output).toContain(`Reviewed clean checkout commit: ${oid}`);expect(output).toContain("gh variable set PRODUCTION_POLICY_BUNDLE_SHA256")});
  it("removes its private index directory while an async Git child is running",async()=>{const root=mkdtempSync(join(tmpdir(),"policy-signal-"));roots.push(root);for(let index=0;index<400;index++)writeFileSync(join(root,`file-${index}`),`${index}\n`);execFileSync("git",["init","-q",root]);execFileSync("git",["-C",root,"add","-A"]);execFileSync("git",["-C",root,"commit","-qm","fixture"]);const before=new Set(readdirSync("/tmp").filter(name=>name.startsWith("steam-top-policy-verify-"))),child=fork("scripts/verify-production-policy-bundle.mjs",[root],{stdio:["ignore","ignore","ignore","ipc"]}),exited=new Promise<number|null>(resolve=>child.once("exit",resolve));await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error("Git child not observed")),3000),listener=(message:unknown)=>{if((message as any)?.purpose==="steam-top-policy-git-child-running"){clearTimeout(timer);child.off("message",listener);resolve()}};child.on("message",listener)});const created=readdirSync("/tmp").find(name=>name.startsWith("steam-top-policy-verify-")&&!before.has(name));expect(created).toBeTruthy();child.kill("SIGTERM");expect(await exited).toBe(143);expect(readdirSync("/tmp")).not.toContain(created)},15000);
  it("detects same-size replacement after opening the authority file",async()=>{const root=mkdtempSync(join(tmpdir(),"stable-authority-"));roots.push(root);const file=join(root,"authority"),replacement=join(root,"replacement"),old=join(root,"old");writeFileSync(file,"AAAA");writeFileSync(replacement,"BBBB");chmodSync(file,0o644);chmodSync(replacement,0o644);const {readStableAuthorityFile}=await import("../../scripts/read-stable-authority-file.mjs");expect(()=>readStableAuthorityFile(file,0o644,()=>{renameSync(file,old);renameSync(replacement,file)})).toThrow(/changed while hashing|path identity changed/)});
});
