import {readFileSync} from "node:fs";import {describe,expect,it} from "vitest";
const workflow=readFileSync(".github/workflows/authorize-rollback.yml","utf8");
const record=readFileSync(".github/workflows/record-deployment.yml","utf8");
describe("protected rollback authorization",()=>{
 it("requires manual environment approval and derives current state",()=>{expect(workflow).toContain("environment: production-rollback-approval");expect(workflow).toContain("verify-rollback-go-live.mjs");expect(workflow).toContain("resolve-current-deployment.mjs");expect(workflow).not.toContain("current_run_id:");});
 it("verifies tagged CI source runs, artifact ownership and signer workflow",()=>{expect(workflow).toContain("actions/runs/$PREVIOUS_RUN");expect(workflow).toContain("git/ref/tags/$tag");expect(workflow).toContain("verify-run-artifact.mjs");expect(workflow).toContain("sources/current/runtime-files.sha256");expect(workflow.match(/--signer-workflow/gu)?.length).toBe(3);});
 it("attests an artifact named with both commits and run",()=>{expect(workflow).toContain('authorized-rollback-${{ inputs.previous_commit }}-${{ env.CURRENT_COMMIT }}-${{ github.run_id }}');expect(workflow).toContain("ROLLBACK-SOURCES.json");const refs=[...workflow.matchAll(/uses:\s*[^@\s]+@([^\s#]+)/gu)].map(x=>x[1]);expect(refs.every(x=>/^[a-f0-9]{40}$/u.test(x!))).toBe(true);});
 it("derives current database from protected deployment state",()=>{expect(workflow).toContain("deployments?environment=production");expect(workflow).toContain("deployment-status.json");expect(record).toContain("environment: production");expect(record).toContain("deployments: write");expect(record).toContain("manifest_sha256");expect(record).toContain("create-deployment-status.mjs");});
 it("does not interpolate dispatch expressions inside shell",()=>{for(const file of [".github/workflows/authorize-rollback.yml",".github/workflows/record-deployment.yml"]){const text=readFileSync(file,"utf8");for(const block of text.split(/\n\s*- (?:name:|uses:)/u)){const shell=block.split("run: |")[1];if(shell)expect(shell).not.toMatch(/\$\{\{\s*inputs\./u);}}});
});
