import { lstat, mkdir, mkdtemp, symlink, utimes, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { randomUUID } from "node:crypto";
import { afterEach, expect, it } from "vitest";
import { ExportBusyError, ExportLifecycleManager, ExportStorageError } from "./lifecycle";

const roots:string[]=[];afterEach(async()=>{for(const root of roots.splice(0))await import("node:fs/promises").then(fs=>fs.rm(root,{recursive:true,force:true}));});
it("creates private roots and files, limits admission, and finalizes once",async()=>{const parent=await mkdtemp(join(tmpdir(),"export-life-test-"));roots.push(parent);const manager=new ExportLifecycleManager({root:join(parent,"private"),maxConcurrent:1,minFreeBytes:1});await manager.initialize();expect((await lstat(manager.root)).mode&0o777).toBe(0o700);const lease=await manager.acquire();expect((await lstat(lease.file)).mode&0o777).toBe(0o600);await expect(manager.acquire()).rejects.toBeInstanceOf(ExportBusyError);await Promise.all([lease.finalize(),lease.finalize()]);expect(manager.activeCount).toBe(0);await manager.close();});
it("removes stale or invalid markers while preserving only fresh live cross-process and current active work",async()=>{const parent=await mkdtemp(join(tmpdir(),"export-janitor-test-")),root=join(parent,"private"),outside=join(parent,"outside"),events:unknown[]=[];roots.push(parent);await mkdir(root,{mode:0o700});await writeFile(outside,"keep");const stale=join(root,"export-stale"),fresh=join(root,"export-fresh"),aliveFresh=join(root,"export-alive-fresh"),aliveStale=join(root,"export-alive-stale"),dead=join(root,"export-dead"),invalid=join(root,"export-invalid"),oversize=join(root,"export-oversize");for(const dir of [stale,fresh,aliveFresh,aliveStale,dead,invalid,oversize])await mkdir(dir);await writeFile(join(stale,"export.xlsx"),"old");await writeFile(join(fresh,"export.xlsx"),"new");const marker=(pid:number,heartbeatAt:number)=>JSON.stringify({pid,startId:randomUUID(),heartbeatAt});await writeFile(join(aliveFresh,".active.json"),marker(process.pid,Date.now()));await writeFile(join(aliveStale,".active.json"),marker(process.pid,0));await writeFile(join(dead,".active.json"),marker(2_147_483_647,Date.now()));await writeFile(join(invalid,".active.json"),'{"pid":"bad"}');await writeFile(join(oversize,".active.json"),"x".repeat(4_097));for(const dir of [stale,aliveFresh,aliveStale,dead,invalid,oversize])await utimes(dir,new Date(0),new Date(0));await symlink(outside,join(root,"export-link"));await writeFile(join(root,"unrelated"),"keep");const manager=new ExportLifecycleManager({root,staleMs:1_000,minFreeBytes:1,legacyRoot:parent,reportError:error=>events.push(error)});await manager.initialize();for(const removed of [stale,aliveStale,dead,invalid,oversize])await expect(lstat(removed)).rejects.toThrow();expect((await lstat(aliveFresh)).isDirectory()).toBe(true);expect((await lstat(fresh)).isDirectory()).toBe(true);expect(events.some(value=>String(value).includes("EXPORT_MARKER_INVALID"))).toBe(true);await expect(lstat(join(root,"export-link"))).rejects.toThrow();expect((await lstat(outside)).isFile()).toBe(true);expect((await lstat(join(root,"unrelated"))).isFile()).toBe(true);const lease=await manager.acquire();await utimes(lease.dir,new Date(0),new Date(0));await manager.janitor(Date.now()+10_000);expect((await lstat(lease.dir)).isDirectory()).toBe(true);await lease.finalize();await manager.close();});
it("rejects insufficient disk reserve and aborts active work on shutdown",async()=>{const parent=await mkdtemp(join(tmpdir(),"export-budget-test-"));roots.push(parent);const unavailable=new ExportLifecycleManager({root:join(parent,"full"),minFreeBytes:Number.MAX_SAFE_INTEGER});await unavailable.initialize();await expect(unavailable.acquire()).rejects.toBeInstanceOf(ExportStorageError);await unavailable.close();const manager=new ExportLifecycleManager({root:join(parent,"close"),minFreeBytes:1});await manager.initialize();const lease=await manager.acquire(),aborted=new Promise<void>(resolve=>lease.signal.addEventListener("abort",()=>resolve(),{once:true}));await manager.close();await aborted;expect(manager.activeCount).toBe(0);});
it("reserves global bytes atomically and destroys output at the per-file byte limit",async()=>{const parent=await mkdtemp(join(tmpdir(),"export-byte-test-"));roots.push(parent);const manager=new ExportLifecycleManager({root:join(parent,"private"),legacyRoot:parent,minFreeBytes:1,maxConcurrent:3,maxFileBytes:10,maxTempBytes:20});await manager.initialize();const [a,b]=await Promise.all([manager.acquire(),manager.acquire()]);await expect(manager.acquire()).rejects.toBeInstanceOf(ExportStorageError);const output=a.openOutput();output.stream.end(Buffer.alloc(11));await expect(output.done).rejects.toBeInstanceOf(ExportStorageError);await Promise.all([a.finalize(),b.finalize()]);const c=await manager.acquire();await c.finalize();await manager.close();});
it("migrates exact stale legacy test.xlsx directories and unlinks matching symlinks without following them",async()=>{const parent=await mkdtemp(join(tmpdir(),"export-legacy-test-")),root=join(parent,"private"),legacy=join(parent,"steam-top-export-old"),legacyTest=join(parent,"steam-top-export-test-old"),near=join(parent,"steam-top-export-unsafe.name"),outside=join(parent,"outside"),link=join(parent,"steam-top-export-link"),events:unknown[]=[];roots.push(parent);await mkdir(root);await writeFile(outside,"keep");for(const dir of [legacy,legacyTest,near]){await mkdir(dir);await writeFile(join(dir,"test.xlsx"),"private legacy data");await utimes(dir,new Date(0),new Date(0));}await symlink(outside,link);const manager=new ExportLifecycleManager({root,legacyRoot:parent,staleMs:1,minFreeBytes:1,reportError:error=>events.push(error)});await manager.initialize();await expect(lstat(legacy)).rejects.toThrow();await expect(lstat(legacyTest)).rejects.toThrow();await expect(lstat(link)).rejects.toThrow();expect((await lstat(outside)).isFile()).toBe(true);expect((await lstat(near)).isDirectory()).toBe(true);expect(events.some(value=>String(value).includes("EXPORT_LEGACY_REMOVED"))).toBe(true);expect(events.some(value=>String(value).includes("EXPORT_LEGACY_SYMLINK_REMOVED"))).toBe(true);await manager.close();});
