import { createWriteStream } from "node:fs";
import { chmod,lstat,mkdir,mkdtemp,open,readFile,readdir,rm,stat,statfs,utimes,writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { Transform,type Writable } from "node:stream";
import { pipeline } from "node:stream/promises";
import { randomUUID } from "node:crypto";

export class ExportBusyError extends Error{constructor(){super("EXPORT_BUSY");}}
export class ExportStorageError extends Error{constructor(){super("EXPORT_STORAGE_UNAVAILABLE");}}
export type ExportOutput=Readonly<{stream:Writable;done:Promise<void>}>;
export type ExportLease=Readonly<{dir:string;file:string;signal:AbortSignal;openOutput:()=>ExportOutput;finalize:()=>Promise<void>}>;
type Active={controller:AbortController;dir:string;file:string;marker:string;startId:string;heartbeat?:NodeJS.Timeout;reserved:number;written:number;output?:ExportOutput;final?:Promise<void>};
const PREFIX=/^export-[A-Za-z0-9_-]+$/u,LEGACY=/^steam-top-export(?:-test)?-[A-Za-z0-9_-]+$/u;
function pidAlive(pid:number){if(!Number.isSafeInteger(pid)||pid<1)return false;try{process.kill(pid,0);return true;}catch(error){return (error as NodeJS.ErrnoException).code==="EPERM";}}
export class ExportLifecycleManager{
 readonly root:string;readonly #active=new Set<Active>();readonly #finalizers=new Set<Promise<void>>();#accepting=true;#timer?:NodeJS.Timeout;#reserved=0;#pending=0;#lock:Promise<void>=Promise.resolve();#janitor:Promise<void>|undefined;
 constructor(private readonly options:Readonly<{root?:string;legacyRoot?:string;maxConcurrent?:number;maxTempBytes?:number;maxFileBytes?:number;minFreeBytes?:number;staleMs?:number;janitorLimit?:number;janitorIntervalMs?:number;heartbeatMs?:number;closeTimeoutMs?:number;reportError?:(error:unknown)=>void}>={}){this.root=options.root??join(tmpdir(),"steam-top-exports-private");}
 get activeCount(){return this.#active.size;}
 #exclusive<T>(task:()=>Promise<T>):Promise<T>{const result=this.#lock.then(task,task);this.#lock=result.then(()=>undefined,()=>undefined);return result;}
 async initialize(){await this.#ensureRoot();await this.janitor();const interval=this.options.janitorIntervalMs??15*60_000;this.#timer=setInterval(()=>{this.janitor().catch(error=>this.options.reportError?.(error));},interval);this.#timer.unref();}
 async #ensureRoot(){await mkdir(this.root,{recursive:true,mode:0o700});const rootStat=await lstat(this.root);if(rootStat.isSymbolicLink()||!rootStat.isDirectory())throw new ExportStorageError();await chmod(this.root,0o700);}
 janitor(now=Date.now()){if(this.#janitor)return this.#janitor;this.#janitor=this.#exclusive(async()=>{await this.#cleanRoot(this.root,PREFIX,now,true);const legacy=this.options.legacyRoot??tmpdir();if(legacy!==this.root)await this.#cleanRoot(legacy,LEGACY,now,false);}).finally(()=>{this.#janitor=undefined;});return this.#janitor;}
  async #cleanRoot(root:string,pattern:RegExp,now:number,privateRoot:boolean){let names:string[];try{names=await readdir(root);}catch(error){this.options.reportError?.(error);return;}const activeDirs=new Set([...this.#active].map(row=>row.dir));let handled=0;for(const name of names.sort()){if(handled>=(this.options.janitorLimit??200))break;if(!pattern.test(name))continue;handled++;const path=join(root,name);if(activeDirs.has(path))continue;try{const info=await lstat(path);if(info.isSymbolicLink()){await rm(path,{force:true});if(!privateRoot)this.options.reportError?.(new Error("EXPORT_LEGACY_SYMLINK_REMOVED"));continue;}if(!info.isDirectory()||now-info.mtimeMs<=(this.options.staleMs??60*60_000))continue;const marker=await this.#marker(path),fresh=Boolean(marker&&now-marker.heartbeatAt<=(this.options.staleMs??60*60_000));if(marker&&fresh&&pidAlive(marker.pid))continue;await rm(path,{recursive:true,force:true});if(!privateRoot)this.options.reportError?.(new Error("EXPORT_LEGACY_REMOVED"));}catch(error){this.options.reportError?.(error);}}}
  async #marker(dir:string):Promise<{pid:number;startId:string;heartbeatAt:number}|null>{const path=join(dir,".active.json");try{const info=await lstat(path);if(!info.isFile()||info.isSymbolicLink()||info.size>4_096){this.options.reportError?.(new Error("EXPORT_MARKER_INVALID"));return null;}const parsed=JSON.parse(await readFile(path,"utf8")) as Record<string,unknown>,pid=parsed.pid,startId=parsed.startId,heartbeatAt=parsed.heartbeatAt;if(!Number.isSafeInteger(pid)||Number(pid)<1||typeof startId!=="string"||!/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/iu.test(startId)||typeof heartbeatAt!=="number"||!Number.isSafeInteger(heartbeatAt)||heartbeatAt<0){this.options.reportError?.(new Error("EXPORT_MARKER_INVALID"));return null;}return{pid:Number(pid),startId,heartbeatAt};}catch(error){this.options.reportError?.(new Error((error as NodeJS.ErrnoException).code==="ENOENT"?"EXPORT_MARKER_MISSING":"EXPORT_MARKER_INVALID"));return null;}}
 async acquire():Promise<ExportLease>{if(!this.#accepting)throw new ExportBusyError();this.#pending++;try{return await this.#exclusive(async()=>{if(!this.#accepting||this.#active.size>=(this.options.maxConcurrent??2))throw new ExportBusyError();await this.#ensureRoot();const reserve=this.options.maxFileBytes??256*1024*1024,maxTotal=this.options.maxTempBytes??512*1024*1024;if(this.#reserved+reserve>maxTotal)throw new ExportStorageError();const fs=await statfs(this.root),free=Number(fs.bavail)*Number(fs.bsize);if(!Number.isSafeInteger(free)||free-reserve<(this.options.minFreeBytes??256*1024*1024))throw new ExportStorageError();const dir=await mkdtemp(join(this.root,"export-"));try{await chmod(dir,0o700);const file=join(dir,"export.xlsx"),descriptor=await open(file,"wx",0o600);await descriptor.close();await chmod(file,0o600);const active:Active={controller:new AbortController(),dir,file,marker:join(dir,".active.json"),startId:randomUUID(),reserved:reserve,written:0};await this.#writeMarker(active);active.heartbeat=setInterval(()=>{this.#touch(active).catch(error=>this.options.reportError?.(error));},this.options.heartbeatMs??30_000);active.heartbeat.unref();this.#reserved+=reserve;this.#active.add(active);return this.#lease(active);}catch(error){await rm(dir,{recursive:true,force:true});throw error;}});}finally{this.#pending--;}}
 #lease(active:Active):ExportLease{let final:Promise<void>|undefined;const openOutput=()=>{if(active.output)return active.output;const monitor=new Transform({transform:(chunk,_encoding,callback)=>{const size=Buffer.byteLength(chunk);if(active.written+size>active.reserved){callback(new ExportStorageError());return;}active.written+=size;callback(null,chunk);}}),destination=createWriteStream(active.file,{flags:"w",mode:0o600});const done=pipeline(monitor,destination);active.output={stream:monitor,done};return active.output;};const finalize=()=>{if(final)return final;final=this.#exclusive(async()=>{this.#active.delete(active);if(active.heartbeat)clearInterval(active.heartbeat);this.#reserved=Math.max(0,this.#reserved-active.reserved);active.output?.stream.destroy();try{await active.output?.done;}catch{/* expected after abort */}await rm(active.dir,{recursive:true,force:true});});active.final=final;this.trackFinalizer(final);return final;};return{dir:active.dir,file:active.file,signal:active.controller.signal,openOutput,finalize};}
 async #writeMarker(active:Active){await writeFile(active.marker,JSON.stringify({pid:process.pid,startId:active.startId,heartbeatAt:Date.now()}),{mode:0o600});await chmod(active.marker,0o600);}
 async #touch(active:Active){if(!this.#active.has(active))return;await this.#writeMarker(active);await utimes(active.dir,new Date(),new Date());}
 async validateFile(file:string){const info=await stat(file);if(!info.isFile()||(info.mode&0o777)!==0o600||info.size>(this.options.maxFileBytes??256*1024*1024))throw new ExportStorageError();}
 trackFinalizer<T>(promise:Promise<T>):Promise<T>{const tracked=promise.then(()=>undefined,()=>undefined);this.#finalizers.add(tracked);void tracked.finally(()=>this.#finalizers.delete(tracked));return promise;}
 async close(){this.#accepting=false;if(this.#timer)clearInterval(this.#timer);while(this.#pending>0)await new Promise<void>(resolve=>setImmediate(resolve));for(const active of this.#active)active.controller.abort(new Error("SERVER_SHUTDOWN"));const work=Promise.allSettled([...this.#active].map(active=>active.final??this.#lease(active).finalize())).then(()=>Promise.allSettled([...this.#finalizers]));const timeout=this.options.closeTimeoutMs??10_000;let timer:NodeJS.Timeout|undefined,timedOut=false;const deadline=new Promise<void>(resolve=>{timer=setTimeout(()=>{timedOut=true;this.options.reportError?.(new Error("EXPORT_CLOSE_TIMEOUT"));resolve();},timeout);timer.unref();});await Promise.race([work,deadline]);if(timer)clearTimeout(timer);if(!timedOut&&this.#finalizers.size>0)this.options.reportError?.(new Error("EXPORT_CLOSE_TIMEOUT"));}
}
