import type { DatabaseClient } from "@steam-top/db";
import * as schema from "@steam-top/db/schema";
import { drizzle, type PostgresJsDatabase } from "drizzle-orm/postgres-js";
import { sql, type SQL } from "drizzle-orm";
import { parameterPerformance } from "../analytics/parameters";
import { usageAnalytics,analyticsFiltersSchema,hongKongDateBounds,type AnalyticsFilters } from "../analytics/usage";
import type { ExportDataSource,ExportSnapshot } from "./workbook";

type Db=PostgresJsDatabase<typeof schema>;type AnyRow=Readonly<Record<string,string|number|boolean|Date|null|undefined>>;const PAGE=1_000;
const asRows=(value:unknown)=>value as readonly AnyRow[];
async function* keysetPages(query:(cursor:AnyRow|undefined,limit:number)=>Promise<unknown>,signal?:AbortSignal){let cursor:AnyRow|undefined;for(;;){if(signal?.aborted)throw signal.reason;const batch=asRows(await query(cursor,PAGE));yield* batch;if(batch.length<PAGE)return;cursor=batch.at(-1);}}
const num=(value:unknown)=>{const n=Number(value);if(!Number.isFinite(n))throw new Error("INVALID_EXPORT_NUMBER");return n;};
const text=(value:unknown)=>{if(typeof value!=="string"||value.length===0)throw new Error("INVALID_EXPORT_CURSOR");return value;};
export const exportDatabaseDate=(value:unknown):Date=>{const parsed=value instanceof Date?value:typeof value==="string"?new Date(value):null;if(!parsed||!Number.isFinite(parsed.getTime()))throw new Error("INVALID_EXPORT_CURSOR");return parsed;};
const date=exportDatabaseDate;
export class PostgresExportDataSource implements ExportDataSource{
 constructor(private readonly client:DatabaseClient){}
 async withSnapshot<T>(input:AnalyticsFilters,signal:AbortSignal|undefined,consume:(snapshot:ExportSnapshot)=>Promise<T>):Promise<T>{const filters=analyticsFiltersSchema.parse(input),bounds=hongKongDateBounds(filters.from,filters.to);const result=await this.client.sql.begin("isolation level repeatable read read only",async transaction=>{const db=drizzle(transaction as never,{schema});await db.execute(sql`set local statement_timeout='120s'`);await db.execute(sql`set local idle_in_transaction_session_timeout='150s'`);const cutoffRow=asRows(await db.execute(sql`select transaction_timestamp() "cutoff"`))[0],cutoff=exportDatabaseDate(cutoffRow?.cutoff);
   const conditions:SQL[]=[sql`m.status='completed'`,sql`m.completed_at>=${bounds.from}::timestamptz`,sql`m.completed_at<${bounds.toExclusive}::timestamptz`,sql`m.completed_at<=${cutoff}::timestamptz`];if(filters.performanceModelVersion)conditions.push(sql`m.performance_model_version=${filters.performanceModelVersion}`);if(filters.physicsModelVersion)conditions.push(sql`m.physics_model_version=${filters.physicsModelVersion}`);if(filters.className||filters.identityStatus)conditions.push(sql`exists(select 1 from match_participant_snapshots fp where fp.match_id=m.id ${filters.className?sql`and fp.class_name_snapshot=${filters.className}`:sql``} ${filters.identityStatus?sql`and fp.identity_status_snapshot=${filters.identityStatus}`:sql``})`);const where=sql.join(conditions,sql` and `);
   const versions=asRows(await db.execute(sql`select array_agg(distinct m.performance_model_version order by m.performance_model_version) "performance",array_agg(distinct m.physics_model_version order by m.physics_model_version) "physics" from matches m where ${where}`))[0];
   const countRow=asRows(await db.execute(sql`select count(distinct m.id)::double precision matches,count(distinct rr.id)::double precision rounds,count(distinct (m.id,p.slot,l.id))::double precision designs,count(distinct (m.id,ps.slot))::double precision identities from matches m left join rounds rr on rr.match_id=m.id cross join lateral(values('player1'::player_slot,m.player1_design_id),('player2'::player_slot,m.player2_design_id)) p(slot,design_id) left join design_layers l on l.design_id=p.design_id left join match_participant_snapshots ps on ps.match_id=m.id where ${where}`))[0];
   const matches=keysetPages((cursor,limit)=>db.execute(sql`select m.id "matchId",m.completed_at "completedAt",r.code "roomCode",coalesce(i1.display_name,'已刪除身份') player1,coalesce(i2.display_name,'已刪除身份') player2,m.winner,m.player1_battle_points::integer "player1BattleScore",m.player1_challenge_points::double precision "player1ChallengeScore",m.player1_total::double precision "player1TotalScore",m.player2_battle_points::integer "player2BattleScore",m.player2_challenge_points::double precision "player2ChallengeScore",m.player2_total::double precision "player2TotalScore",m.performance_model_version "performanceModelVersion",m.physics_model_version "physicsModelVersion" from matches m left join rooms r on r.id=m.room_id left join identities i1 on i1.id=m.player1_identity_id left join identities i2 on i2.id=m.player2_identity_id where ${where} ${cursor?sql`and (m.completed_at,m.id)>(${date(cursor.completedAt)},${text(cursor.matchId)}::uuid)`:sql``} order by m.completed_at,m.id limit ${limit}`),signal);
   const rounds=keysetPages((cursor,limit)=>db.execute(sql`select rr.match_id "matchId",m.completed_at "_completedAt",rr.round_number::integer round,rr.attempt::integer "_attempt",rr.launch_grade_a "launchGradeA",rr.launch_grade_b "launchGradeB",case rr.outcome when 'player1' then 'player1' when 'player2' then 'player2' else 'draw' end winner,case when rr.outcome='player1' then 1 else 0 end::integer "scoreA",case when rr.outcome='player2' then 1 else 0 end::integer "scoreB" from rounds rr join matches m on m.id=rr.match_id where ${where} ${cursor?sql`and (m.completed_at,m.id,rr.round_number,rr.attempt)>(${date(cursor._completedAt)},${text(cursor.matchId)}::uuid,${num(cursor.round)},${num(cursor._attempt)})`:sql``} order by m.completed_at,m.id,rr.round_number,rr.attempt limit ${limit}`),signal);
   const designs=keysetPages((cursor,limit)=>db.execute(sql`select d.id "designId",m.id "matchId",m.completed_at "_completedAt",p.slot participant,l.position,l.layer_order::integer "layerOrder",l.shape,case l.shape when 'circle' then '不適用' when 'polygon' then '邊數' when 'star' then '尖角數' else '波瓣數' end "pointsLabel",case when l.shape='circle' then null else l.points::integer end "pointsValue",l.diameter_mm::double precision "diameterMm",l.actual_area_mm2::double precision "actualAreaMm2",l.rotation_deg::double precision "rotationDeg",l.corner_roundness::double precision "cornerRoundness",d.screw_count::integer "screwCount",d.total_mass_g::double precision "totalMassG",d.metal_disc_diameter_mm::double precision "metalDiscDiameterMm",d.center_of_mass_x_mm::double precision "centerOfMassXMm",d.center_of_mass_y_mm::double precision "centerOfMassYMm",sqrt(d.center_of_mass_x_mm*d.center_of_mass_x_mm+d.center_of_mass_y_mm*d.center_of_mass_y_mm)::double precision "eccentricityMm",d.polar_moment_gmm2::double precision "momentOfInertia",d.performance_model_version "performanceModelVersion" from matches m cross join lateral(values('player1'::player_slot,m.player1_design_id),('player2'::player_slot,m.player2_design_id)) p(slot,design_id) join designs d on d.id=p.design_id join design_layers l on l.design_id=d.id where ${where} ${cursor?sql`and (m.completed_at,m.id,p.slot,l.layer_order)>(${date(cursor._completedAt)},${text(cursor.matchId)}::uuid,${text(cursor.participant)}::player_slot,${num(cursor.layerOrder)})`:sql``} order by m.completed_at,m.id,p.slot,l.layer_order limit ${limit}`),signal);
   const identities=keysetPages((cursor,limit)=>db.execute(sql`select m.id "matchId",m.completed_at "_completedAt",ps.slot participant,coalesce(i.display_name,'已刪除身份') "displayName",i.student_name "studentName",ps.class_name_snapshot "className",i.student_number "studentNumber",case ps.slot when 'player1' then m.player1_device_name else m.player2_device_name end "deviceName",ps.identity_status_snapshot "identityStatus" from matches m join match_participant_snapshots ps on ps.match_id=m.id left join identities i on i.id=ps.identity_id_at_start where ${where} ${cursor?sql`and (m.completed_at,m.id,ps.slot)>(${date(cursor._completedAt)},${text(cursor.matchId)}::uuid,${text(cursor.participant)}::player_slot)`:sql``} order by m.completed_at,m.id,ps.slot limit ${limit}`),signal);
   async function* usage(){for(const row of await usageAnalytics(db,filters,"day",cutoff.toISOString()))yield{period:"day",date:row.date,activeDevices:row.activeDevices,designs:row.designs,rooms:row.rooms,completedMatches:row.completedMatches};}
   const parameterPreview=await parameterPerformance(db,filters,{limit:1,offset:0,order:"stable",asOf:cutoff.toISOString()}),parameterTotal=parameterPreview[0]?.totalGroups??0,parameterCap=100_000;
   async function* parameters(){for(let offset=0;offset<parameterCap;offset+=PAGE){const limit=Math.min(PAGE,parameterCap-offset),batch=await parameterPerformance(db,filters,{limit,offset,order:"stable",asOf:cutoff.toISOString()});for(const row of batch)yield{dimension:row.dimension,value:JSON.stringify(row.value),sampleSize:num(row.sampleSize),averageScore:num(row.averageScore),winRate:num(row.winRate),opponentAverageStrength:num(row.opponentAverageStrength),expectedWinRate:num(row.expectedWinRate),outcomeResidual:num(row.outcomeResidual),performanceModelVersion:row.performanceModelVersion,physicsModelVersion:row.physicsModelVersion};if(batch.length<limit)break;}}
   const snapshot:ExportSnapshot={metadata:{cutoff,performanceModelVersions:Array.isArray(versions?.performance)?versions.performance.map(String):[],physicsModelVersions:Array.isArray(versions?.physics)?versions.physics.map(String):[],rowCounts:{matches:num(countRow?.matches??0),rounds:num(countRow?.rounds??0),designs:num(countRow?.designs??0),identities:num(countRow?.identities??0),parameters:Math.min(parameterTotal,parameterCap)},...(parameterTotal>parameterCap?{truncated:[`參數分析最多 ${parameterCap} 列（完整 ${parameterTotal} 列）`]}:{})},sheets:{matches,rounds,designs,identities,usage:usage(),parameters:parameters()}};return consume(snapshot);
 });return result as unknown as T;}
}
export const createProductionExportDataSource=(client:DatabaseClient)=>new PostgresExportDataSource(client);
