import { createReadStream } from "node:fs";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import type { Writable } from "node:stream";
import ExcelJS from "exceljs";
import type { FastifyInstance } from "fastify";
import { analyticsFiltersSchema, type AnalyticsFilters } from "../analytics/usage";
import { authenticateAdminRead, durableAudit, type AdminAuthService } from "../auth/admin-auth";
import { ExportBusyError, ExportLifecycleManager, ExportStorageError, type ExportLease } from "./lifecycle";

type Cell=string|number|boolean|Date|null|undefined;type Row=Readonly<Record<string,Cell>>;
class ExportStageError extends Error{readonly code:string;override readonly cause:unknown;constructor(code:string,cause:unknown){super(code);this.name="ExportStageError";this.code=code;this.cause=cause;}}
const exportStage=async<T>(code:string,operation:()=>Promise<T>):Promise<T>=>{try{return await operation();}catch(error){if(error instanceof ExportStageError||error instanceof ExportStorageError)throw error;throw new ExportStageError(code,error);}};
export type ExportSheetKey="matches"|"rounds"|"designs"|"identities"|"usage"|"parameters";
export type ExportMetadata=Readonly<{cutoff:Date;performanceModelVersions:readonly string[];physicsModelVersions:readonly string[];rowCounts?:Readonly<Partial<Record<ExportSheetKey,number>>>;truncated?:readonly string[]}>;
export type ExportSnapshot=Readonly<{metadata:ExportMetadata;sheets:Readonly<Record<ExportSheetKey,AsyncIterable<Row>>>}>;
export interface ExportDataSource { withSnapshot<T>(filters:AnalyticsFilters,signal:AbortSignal|undefined,consume:(snapshot:ExportSnapshot)=>Promise<T>):Promise<T>; }
export type ExportDataset=Readonly<Record<ExportSheetKey,readonly Row[]>>;
async function* iterable(rows:readonly Row[]){yield* rows;}
export function inMemoryExportDataSource(dataset:ExportDataset,metadata:ExportMetadata={cutoff:new Date(),performanceModelVersions:[],physicsModelVersions:[]}):ExportDataSource{return{withSnapshot:async(_filters,signal,consume)=>{abort(signal);return consume({metadata,sheets:{matches:iterable(dataset.matches),rounds:iterable(dataset.rounds),designs:iterable(dataset.designs),identities:iterable(dataset.identities),usage:iterable(dataset.usage),parameters:iterable(dataset.parameters)}});}};}
type Column=Readonly<{key:string;header:string;width:number}>;type Spec=Readonly<{name:string;key:ExportSheetKey;columns:readonly Column[]}>;
const c=(key:string,header:string,width=16):Column=>({key,header,width});
export const SHEETS:readonly Spec[]=[
 {name:"對戰紀錄",key:"matches",columns:[c("matchId","對戰 ID",38),c("completedAt","完成時間（香港）",21),c("roomCode","房間碼",12),c("player1","玩家 1",18),c("player2","玩家 2",18),c("winner","勝方",12),c("player1BattleScore","玩家 1 對戰分"),c("player1ChallengeScore","玩家 1 挑戰分"),c("player1TotalScore","玩家 1 總分"),c("player2BattleScore","玩家 2 對戰分"),c("player2ChallengeScore","玩家 2 挑戰分"),c("player2TotalScore","玩家 2 總分"),c("performanceModelVersion","表現模型版本",18),c("physicsModelVersion","物理模型版本",18)]},
 {name:"逐輪結果",key:"rounds",columns:[c("matchId","對戰 ID",38),c("round","輪次",10),c("launchGradeA","玩家 1 發射判定",18),c("launchGradeB","玩家 2 發射判定",18),c("winner","勝方",12),c("scoreA","玩家 1 輪分"),c("scoreB","玩家 2 輪分")]},
 {name:"陀螺參數",key:"designs",columns:[c("designId","設計 ID",38),c("matchId","對戰 ID",38),c("participant","玩家位置"),c("position","層位置"),c("layerOrder","層次排序"),c("shape","形狀"),c("pointsLabel","邊數／尖角／波瓣標籤",22),c("pointsValue","邊數／尖角／波瓣數值",22),c("diameterMm","直徑 (mm)"),c("actualAreaMm2","實際面積 (mm²)",18),c("rotationDeg","旋轉角度"),c("cornerRoundness","圓角比例"),c("screwCount","螺絲孔數量"),c("totalMassG","總重量 (g)"),c("metalDiscDiameterMm","底部金屬貼片直徑 (mm)",24),c("centerOfMassXMm","重心 X (mm)"),c("centerOfMassYMm","重心 Y (mm)"),c("eccentricityMm","偏心距 (mm)"),c("momentOfInertia","轉動慣量"),c("performanceModelVersion","表現模型版本",18)]},
 {name:"身份及裝置狀態",key:"identities",columns:[c("matchId","對戰 ID",38),c("participant","玩家位置"),c("displayName","顯示名稱",18),c("studentName","學生姓名",18),c("className","班別",10),c("studentNumber","學號",10),c("deviceName","裝置名稱",22),c("identityStatus","識別狀態")]},
 {name:"使用量統計",key:"usage",columns:[c("period","統計週期"),c("date","香港日期"),c("activeDevices","活躍裝置"),c("designs","設計數量"),c("rooms","房間數量"),c("completedMatches","完成對戰")]},
 {name:"參數分析",key:"parameters",columns:[c("dimension","參數類別",18),c("value","參數值",32),c("sampleSize","樣本數"),c("averageScore","平均分"),c("winRate","勝率"),c("opponentAverageStrength","對手平均強度",18),c("expectedWinRate","預期勝率"),c("outcomeResidual","表現差值"),c("performanceModelVersion","表現模型版本",18),c("physicsModelVersion","物理模型版本",18)]}
] as const;
const MAX_CELL=32_767,MAX_ROWS=500_000;
function xmlText(value:string):string{let result="";for(const character of value){const point=character.codePointAt(0)!;const range=point===0x9||point===0xa||point===0xd||(point>=0x20&&point<=0xd7ff)||(point>=0xe000&&point<=0xfffd)||(point>=0x10000&&point<=0x10ffff),noncharacter=(point>=0xfdd0&&point<=0xfdef)||(point&0xfffe)===0xfffe;if(range&&!noncharacter)result+=character;}return result;}
function safe(value:Cell):Cell{if(value instanceof Date)return new Date(value.getTime()+8*60*60_000);if(typeof value==="number"){if(!Number.isFinite(value))throw new Error("INVALID_EXPORT_NUMBER");return value;}if(typeof value!=="string")return value;const text=xmlText(value),escaped=/^\s*[=+\-@]/u.test(text)?`'${text}`:text;if(Array.from(escaped).length>MAX_CELL)throw new RangeError("EXPORT_CELL_LIMIT");return escaped;}
function abort(signal?:AbortSignal){if(signal?.aborted)throw signal.reason instanceof Error?signal.reason:new Error("EXPORT_ABORTED");}
function metadataRows(filters:AnalyticsFilters,meta:ExportMetadata,generatedAt:Date):readonly (readonly Cell[])[]{return [["匯出資料","STEAM 陀螺模擬器教師紀錄"],["產生時間（香港）",safe(generatedAt)],["資料截止時間（香港）",safe(meta.cutoff)],["日期範圍",`${filters.from} 至 ${filters.to}`],["篩選條件",`班別=${filters.className??"全部"}; 身份=${filters.identityStatus??"全部"}; 指定表現模型=${filters.performanceModelVersion??"全部"}; 指定物理模型=${filters.physicsModelVersion??"全部"}`],["實際模型版本",`表現=${meta.performanceModelVersions.join(",")||"無"}; 物理=${meta.physicsModelVersions.join(",")||"無"}${meta.truncated?.length?`; 截短=${meta.truncated.join(",")}`:""}`]];}
export async function writeWorkbookFile(target:string|Writable,source:ExportDataSource,filtersInput:AnalyticsFilters,options:Readonly<{generatedAt?:Date;signal?:AbortSignal;maxRowsPerSheet?:number}>={}):Promise<void>{const filters=analyticsFiltersSchema.parse(filtersInput),limit=options.maxRowsPerSheet??MAX_ROWS;if(!Number.isSafeInteger(limit)||limit<2||limit>MAX_ROWS)throw new RangeError("INVALID_EXPORT_ROW_LIMIT");abort(options.signal);await exportStage("EXPORT_SNAPSHOT_FAILED",()=>source.withSnapshot(filters,options.signal,async snapshot=>{for(const spec of SHEETS){const headerRows=spec.key==="matches"?8:1,count=snapshot.metadata.rowCounts?.[spec.key];if(count!==undefined&&(!Number.isSafeInteger(count)||count<0||count>limit-headerRows))throw new RangeError(`EXPORT_ROW_LIMIT:${spec.name}`);}const book=new ExcelJS.stream.xlsx.WorkbookWriter({...(typeof target==="string"?{filename:target}:{stream:target}),useStyles:true,useSharedStrings:false});book.creator="STEAM 陀螺模擬器";book.created=options.generatedAt??new Date();let stage="EXPORT_WORKBOOK_INIT_FAILED";try{for(const spec of SHEETS){stage=`EXPORT_SHEET_${spec.key.toUpperCase()}_FAILED`;abort(options.signal);const first=spec.key==="matches",headerRow=first?8:1,sheet=book.addWorksheet(spec.name,{views:[{state:"frozen",ySplit:headerRow}]});sheet.columns=spec.columns.map(x=>({key:x.key,width:x.width}));if(first){for(const values of metadataRows(filters,snapshot.metadata,book.created))sheet.addRow([...values]).commit();sheet.addRow([]).commit();}const header=sheet.getRow(headerRow);header.values=spec.columns.map(x=>x.header);header.font={bold:true};header.commit();sheet.autoFilter={from:{row:headerRow,column:1},to:{row:headerRow,column:spec.columns.length}};let count=headerRow;for await(const item of snapshot.sheets[spec.key]){abort(options.signal);if(++count>limit)throw new RangeError(`EXPORT_ROW_LIMIT:${spec.name}`);const values:Record<string,Cell>={};for(const column of spec.columns)values[column.key]=safe(item[column.key]);const row=sheet.addRow(values);row.eachCell(cell=>{if(cell.value instanceof Date)cell.numFmt="yyyy-mm-dd hh:mm:ss";});row.commit();}sheet.commit();}stage="EXPORT_WORKBOOK_COMMIT_FAILED";await book.commit();}catch(error){(book as unknown as {stream?:{destroy:(e:Error)=>void}}).stream?.destroy(error instanceof Error?error:new Error("EXPORT_FAILED"));throw new ExportStageError(stage,error);}}));}
/** Small-file helper for tests only; production never buffers XLSX output. */
export async function buildWorkbookBuffer(source:ExportDataSource,filters:AnalyticsFilters,options:Readonly<{generatedAt?:Date;signal?:AbortSignal;maxRowsPerSheet?:number}>={}):Promise<Buffer>{const dir=await mkdtemp(join(tmpdir(),"steam-top-export-test-")),path=join(dir,"test.xlsx");try{await writeWorkbookFile(path,source,filters,options);return await readFile(path);}finally{await rm(dir,{recursive:true,force:true});}}
const fileName=(f:AnalyticsFilters)=>`STEAM-top-${f.from}-${f.to}.xlsx`;
export function registerExportRoutes(app:FastifyInstance,auth:AdminAuthService,source:ExportDataSource,lifecycle=new ExportLifecycleManager({reportError:error=>auth.report("admin.export.lifecycle",error)}),auditWaitMs=2_000):void{app.addHook("onReady",()=>lifecycle.initialize());app.addHook("preClose",()=>lifecycle.close());app.get("/api/admin/export.xlsx",async(request,reply)=>{
 const current=await authenticateAdminRead(request,reply,auth);if(!current)return;const parsed=analyticsFiltersSchema.safeParse(request.query);if(!parsed.success)return reply.code(400).send({error:"INVALID_FILTERS"});const common={adminUserId:current.user.id,adminSessionId:current.session.id,details:{filters:parsed.data,parameterRowCap:100_000,worksheetRowCap:MAX_ROWS,cellOverflowPolicy:"reject"}} as const;
 let lease:ExportLease;try{lease=await lifecycle.acquire();}catch(error){const reason=error instanceof ExportBusyError?"busy":error instanceof ExportStorageError?"storage":"internal";try{await durableAudit(auth.store,{...common,action:"admin.export.xlsx.admission",outcome:"denied",details:{...common.details,reason,requestId:request.id}});}catch(auditError){auth.report("admin.export.xlsx.admission.audit",auditError,request.id);}if(error instanceof ExportBusyError)return reply.code(429).send({error:"EXPORT_BUSY"});if(error instanceof ExportStorageError)return reply.code(507).send({error:"EXPORT_STORAGE_UNAVAILABLE"});auth.report("admin.export.xlsx.admission",error,request.id);return reply.code(500).send({error:"EXPORT_ADMISSION_FAILED"});}let finalized=false,finalPromise:Promise<void>|undefined;const controller=new AbortController();let shutdownAbort:()=>void;const auditFinal=(action:string,outcome:"success"|"failure")=>{if(finalPromise)return finalPromise;if(finalized)return Promise.resolve();finalized=true;finalPromise=(async()=>{lease.signal.removeEventListener("abort",shutdownAbort);try{await lease.finalize();}catch(cleanupError){auth.report("admin.export.xlsx.cleanup",cleanupError,request.id);}const durable=durableAudit(auth.store,{...common,action,outcome}).catch(e=>auth.report("admin.export.xlsx.audit",e,request.id));lifecycle.trackFinalizer(durable);await Promise.race([durable,new Promise<void>(resolve=>{const timer=setTimeout(()=>{auth.report("admin.export.xlsx.audit_pending_timeout",new Error("EXPORT_AUDIT_PENDING_TIMEOUT"),request.id);resolve();},auditWaitMs);timer.unref();})]);})();return lifecycle.trackFinalizer(finalPromise);};shutdownAbort=()=>{controller.abort(lease.signal.reason);void auditFinal("admin.export.xlsx.aborted","failure");};lease.signal.addEventListener("abort",shutdownAbort,{once:true});
 const onAborted=()=>controller.abort(new Error("CLIENT_ABORTED"));const onClose=()=>{if(!reply.raw.writableEnded){controller.abort(new Error("CLIENT_DISCONNECTED"));void auditFinal("admin.export.xlsx.aborted","failure");}};request.raw.once("aborted",onAborted);reply.raw.once("close",onClose);
 try{await durableAudit(auth.store,{...common,action:"admin.export.xlsx.started",outcome:"success"});const output=lease.openOutput();await writeWorkbookFile(output.stream,source,parsed.data,{signal:controller.signal});await output.done;await lifecycle.validateFile(lease.file);const stream=createReadStream(lease.file);stream.once("error",error=>{controller.abort(error);auth.report("admin.export.xlsx.stream",error,request.id);void auditFinal("admin.export.xlsx.failed","failure");});reply.raw.once("finish",()=>{void auditFinal("admin.export.xlsx.succeeded","success");});return reply.header("Cache-Control","private, no-store").header("Content-Type","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet").header("Content-Disposition",`attachment; filename="${fileName(parsed.data)}"`).send(stream);
 }catch(error){const aborted=controller.signal.aborted,storage=error instanceof ExportStorageError;auth.report("admin.export.xlsx",error,request.id);await auditFinal(aborted?"admin.export.xlsx.aborted":storage?"admin.export.xlsx.failed.storage":"admin.export.xlsx.failed","failure");if(!reply.sent)return reply.code(storage?507:503).send({error:aborted?"EXPORT_ABORTED":storage?"EXPORT_STORAGE_UNAVAILABLE":"EXPORT_UNAVAILABLE"});}
 finally{request.raw.off("aborted",onAborted);if(reply.raw.writableEnded)reply.raw.off("close",onClose);}
 });}
