import ExcelJS from "exceljs";
import Fastify from "fastify";
import fastifyCookie from "@fastify/cookie";
import { describe, expect, it } from "vitest";
import { AdminAuthService, InMemoryAdminStore, registerAdminAuthRoutes, type AuditInput } from "../auth/admin-auth";
import { buildWorkbookBuffer, inMemoryExportDataSource, registerExportRoutes, type ExportDataSource, type ExportDataset } from "./workbook";
import { ExportLifecycleManager } from "./lifecycle";
import { mkdir, mkdtemp, readdir, rm, utimes, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

const filters = { from: "2026-08-01", to: "2026-08-31", className: "1A" } as const;
const dataset:ExportDataset = {
  matches: [{ matchId:"m1",completedAt:new Date("2026-08-02T03:04:05Z"),roomCode:"ABCD",player1:"陳同學",player2:"=HYPERLINK(\"x\")",winner:"player1",player1BattleScore:2,player1ChallengeScore:.25,player1TotalScore:2.25,player2BattleScore:1,player2ChallengeScore:0,player2TotalScore:1,performanceModelVersion:"p1",physicsModelVersion:"v1" }],
  rounds:[{matchId:"m1",round:1,launchGradeA:"Perfect",launchGradeB:"Good",winner:"player1",scoreA:1,scoreB:0}],
  designs:[{designId:"d1",matchId:"m1",participant:"player1",position:"top",layerOrder:1,shape:"circle",pointsLabel:"不適用",pointsValue:null,diameterMm:50,actualAreaMm2:1900,rotationDeg:0,cornerRoundness:.2,screwCount:3,metalDiscDiameterMm:20,totalMassG:41.2,momentOfInertia:123.4,performanceModelVersion:"p1"}],
  identities:[{matchId:"m1",participant:"player1",displayName:"陳同學",studentName:"陳同學",className:"1A",studentNumber:"01",deviceName:"iPad-01",identityStatus:"iclass"}],
  usage:[{period:"day",date:"2026-08-02",activeDevices:1,designs:1,rooms:1,completedMatches:1}],
  parameters:[{dimension:"形狀",value:"circle",sampleSize:12,averageScore:1.5,winRate:.6,opponentAverageStrength:55,expectedWinRate:.52,outcomeResidual:.08,performanceModelVersion:"p1",physicsModelVersion:"v1"}]
};
const source=inMemoryExportDataSource(dataset,{cutoff:new Date("2026-08-29T03:00:00Z"),performanceModelVersions:["p1"],physicsModelVersions:["v1"]});

describe("teacher Excel export",()=>{
  it("exports the six required sheets with typed values, presentation controls, no formulas and safe strings",async()=>{
    const bytes=await buildWorkbookBuffer(source,filters,{generatedAt:new Date("2026-08-29T04:00:00Z")});
    const book=new ExcelJS.Workbook();await book.xlsx.load(bytes as never);
    expect(book.worksheets.map(s=>s.name)).toEqual(["對戰紀錄","逐輪結果","陀螺參數","身份及裝置狀態","使用量統計","參數分析"]);
    expect(book.getWorksheet("對戰紀錄")!.views[0]).toMatchObject({state:"frozen",ySplit:8});for(const sheet of book.worksheets){expect(sheet.autoFilter).toBeTruthy();sheet.eachRow(row=>row.eachCell(cell=>expect(typeof cell.value==="object"&&cell.value!==null&&"formula" in cell.value).toBe(false)));}
    expect(book.getWorksheet("對戰紀錄")!.getCell("B9").value).toBeInstanceOf(Date);expect((book.getWorksheet("對戰紀錄")!.getCell("B9").value as Date).getUTCHours()).toBe(11);
    expect(book.getWorksheet("對戰紀錄")!.getCell("E9").value).toBe("'=HYPERLINK(\"x\")");
    expect(typeof book.getWorksheet("陀螺參數")!.getCell("I2").value).toBe("number");expect(book.getWorksheet("對戰紀錄")!.getCell("A1").value).toBe("匯出資料");
    expect(book.worksheets.flatMap(sheet=>sheet.getRow(sheet.name==="對戰紀錄"?8:1).values as string[]).join("|").toLowerCase()).not.toMatch(/token|ip address|mac address|user-agent/u);
  });

  it("streams a large dataset and supports cancellation",async()=>{
    const many=inMemoryExportDataSource({...dataset,matches:Array.from({length:100_000},(_,i)=>({...dataset.matches[0]!,matchId:`m${i}`}))});
    expect((await buildWorkbookBuffer(many,filters)).byteLength).toBeGreaterThan(100_000);
    const controller=new AbortController();controller.abort(new Error("cancelled"));await expect(buildWorkbookBuffer(source,filters,{signal:controller.signal})).rejects.toThrow("cancelled");
  },30_000);

  it("protects the GET route with admin auth and download headers",async()=>{
    const store=new InMemoryAdminStore(),auth=new AdminAuthService(store,{allowedOrigins:["https://school.test"],secureCookies:false,csrfSecret:Buffer.alloc(32,1)});await auth.bootstrap("admin","test-password-2026");
    const app=Fastify();await app.register(fastifyCookie);registerAdminAuthRoutes(app,auth);registerExportRoutes(app,auth,source);await app.ready();
    expect((await app.inject({method:"GET",url:"/api/admin/export.xlsx?from=2026-08-01&to=2026-08-31",headers:{host:"school.test"}})).statusCode).toBe(401);
    const login=await app.inject({method:"POST",url:"/api/admin/login",headers:{host:"school.test",origin:"https://school.test","sec-fetch-site":"same-origin","content-type":"application/json"},payload:{username:"admin",password:"test-password-2026"}});const cookie=`${login.cookies[0]!.name}=${login.cookies[0]!.value}`;
    const result=await app.inject({method:"GET",url:"/api/admin/export.xlsx?from=2026-08-01&to=2026-08-31",headers:{host:"school.test",cookie}});
    expect(result.statusCode).toBe(200);expect(result.headers["cache-control"]).toBe("private, no-store");expect(result.headers["content-disposition"]).toMatch(/^attachment; filename="STEAM-top-/);expect(result.headers["content-type"]).toContain("spreadsheetml");
    await app.close();expect(store.auditEntries.some(row=>row.action==="admin.export.xlsx.started")).toBe(true);expect(store.auditEntries.some(row=>row.action==="admin.export.xlsx.succeeded")).toBe(true);
  });

  it("completes a real HTTP socket download without treating normal close as abort",async()=>{const store=new InMemoryAdminStore(),auth=new AdminAuthService(store,{allowedOrigins:["http://127.0.0.1"],secureCookies:false,csrfSecret:Buffer.alloc(32,3)});await auth.bootstrap("admin","test-password-2026");const app=Fastify();await app.register(fastifyCookie);registerAdminAuthRoutes(app,auth);registerExportRoutes(app,auth,source);await app.listen({host:"127.0.0.1",port:0});const address=app.server.address();if(!address||typeof address==="string")throw new Error("NO_TEST_ADDRESS");const origin=`http://127.0.0.1:${address.port}`;(auth as unknown as { _unused?:never });await app.close();
    // Rebuild with the actual ephemeral origin because the guard validates Host and Origin together.
    const liveStore=new InMemoryAdminStore(),liveAuth=new AdminAuthService(liveStore,{allowedOrigins:[origin],secureCookies:false,csrfSecret:Buffer.alloc(32,4)});await liveAuth.bootstrap("admin","test-password-2026");const live=Fastify();await live.register(fastifyCookie);registerAdminAuthRoutes(live,liveAuth);registerExportRoutes(live,liveAuth,source);await live.listen({host:"127.0.0.1",port:address.port});const login=await fetch(`${origin}/api/admin/login`,{method:"POST",headers:{origin,"sec-fetch-site":"same-origin","content-type":"application/json"},body:JSON.stringify({username:"admin",password:"test-password-2026"})}),cookie=login.headers.get("set-cookie")!.split(";",1)[0]!,response=await fetch(`${origin}/api/admin/export.xlsx?from=2026-08-01&to=2026-08-31`,{headers:{cookie}});expect(response.status).toBe(200);expect((await response.arrayBuffer()).byteLength).toBeGreaterThan(1_000);await live.close();expect(liveStore.auditEntries.some(row=>row.action==="admin.export.xlsx.succeeded")).toBe(true);expect(liveStore.auditEntries.some(row=>row.action==="admin.export.xlsx.aborted")).toBe(false);
  },30_000);

  it("rejects invalid filters and returns a safe audited error when generation fails",async()=>{
    const store=new InMemoryAdminStore(),auth=new AdminAuthService(store,{allowedOrigins:["https://school.test"],secureCookies:false,csrfSecret:Buffer.alloc(32,2)});await auth.bootstrap("admin","test-password-2026");const failing:ExportDataSource={async withSnapshot(){throw new Error("secret database URL");}};
    const app=Fastify();await app.register(fastifyCookie);registerAdminAuthRoutes(app,auth);registerExportRoutes(app,auth,failing);await app.ready();const login=await app.inject({method:"POST",url:"/api/admin/login",headers:{host:"school.test",origin:"https://school.test","sec-fetch-site":"same-origin","content-type":"application/json"},payload:{username:"admin",password:"test-password-2026"}}),cookie=`${login.cookies[0]!.name}=${login.cookies[0]!.value}`,headers={host:"school.test",cookie};
    expect((await app.inject({method:"GET",url:"/api/admin/export.xlsx?from=bad&to=2026-08-31",headers})).statusCode).toBe(400);const failed=await app.inject({method:"GET",url:"/api/admin/export.xlsx?from=2026-08-01&to=2026-08-31",headers});expect(failed.statusCode).toBe(503);expect(failed.json()).toEqual({error:"EXPORT_UNAVAILABLE"});expect(store.auditEntries.at(-1)).toMatchObject({action:"admin.export.xlsx.failed",outcome:"failure"});expect(JSON.stringify(store.auditEntries)).not.toContain("secret database URL");await app.close();
  });

  it("durably audits busy, storage, and unexpected admission rejection without a started event",async()=>{const run=async(manager:ExportLifecycleManager)=>{const store=new InMemoryAdminStore(),auth=new AdminAuthService(store,{allowedOrigins:["https://school.test"],secureCookies:false,csrfSecret:Buffer.alloc(32,5)});await auth.bootstrap("admin","test-password-2026");const app=Fastify();await app.register(fastifyCookie);registerAdminAuthRoutes(app,auth);registerExportRoutes(app,auth,source,manager);await app.ready();const login=await app.inject({method:"POST",url:"/api/admin/login",headers:{host:"school.test",origin:"https://school.test","sec-fetch-site":"same-origin","content-type":"application/json"},payload:{username:"admin",password:"test-password-2026"}}),cookie=`${login.cookies[0]!.name}=${login.cookies[0]!.value}`,response=await app.inject({method:"GET",url:"/api/admin/export.xlsx?from=2026-08-01&to=2026-08-31",headers:{host:"school.test",cookie}});await app.close();expect(store.auditEntries.some(row=>row.action==="admin.export.xlsx.started")).toBe(false);expect(store.auditEntries.at(-1)).toMatchObject({action:"admin.export.xlsx.admission",outcome:"denied"});return response.statusCode;};const parent=await mkdtemp(join(tmpdir(),"export-admission-test-"));try{expect(await run(new ExportLifecycleManager({root:join(parent,"busy"),legacyRoot:parent,minFreeBytes:1,maxConcurrent:0}))).toBe(429);expect(await run(new ExportLifecycleManager({root:join(parent,"storage"),legacyRoot:parent,minFreeBytes:Number.MAX_SAFE_INTEGER}))).toBe(507);const broken=new ExportLifecycleManager({root:join(parent,"broken"),legacyRoot:parent,minFreeBytes:1});broken.acquire=async()=>{throw new Error("secret admission failure");};expect(await run(broken)).toBe(500);}finally{await rm(parent,{recursive:true,force:true});}},30_000);

  it("returns audited 507 when ExcelJS exceeds the live byte monitor and releases all resources",async()=>{const parent=await mkdtemp(join(tmpdir(),"export-route-cap-test-")),root=join(parent,"private"),manager=new ExportLifecycleManager({root,legacyRoot:parent,minFreeBytes:1,maxFileBytes:512,maxTempBytes:1_024});try{const store=new InMemoryAdminStore(),auth=new AdminAuthService(store,{allowedOrigins:["https://school.test"],secureCookies:false,csrfSecret:Buffer.alloc(32,6)});await auth.bootstrap("admin","test-password-2026");const app=Fastify();await app.register(fastifyCookie);registerAdminAuthRoutes(app,auth);registerExportRoutes(app,auth,source,manager);await app.ready();const login=await app.inject({method:"POST",url:"/api/admin/login",headers:{host:"school.test",origin:"https://school.test","sec-fetch-site":"same-origin","content-type":"application/json"},payload:{username:"admin",password:"test-password-2026"}}),cookie=`${login.cookies[0]!.name}=${login.cookies[0]!.value}`,result=await app.inject({method:"GET",url:"/api/admin/export.xlsx?from=2026-08-01&to=2026-08-31",headers:{host:"school.test",cookie}});expect(result.statusCode).toBe(507);expect(result.json()).toEqual({error:"EXPORT_STORAGE_UNAVAILABLE"});expect(store.auditEntries.some(row=>row.action==="admin.export.xlsx.failed.storage"&&row.outcome==="failure")).toBe(true);expect(manager.activeCount).toBe(0);expect(await readdir(root)).toHaveLength(0);const retry=await manager.acquire();await retry.finalize();await app.close();}finally{await rm(parent,{recursive:true,force:true});}},30_000);

  it("deletes temp data before bounded wait while a durable final audit remains pending",async()=>{class PendingFinalStore extends InMemoryAdminStore{override async audit(input:AuditInput){if(input.action==="admin.export.xlsx.succeeded")return new Promise<void>(()=>undefined);return super.audit(input);}}const parent=await mkdtemp(join(tmpdir(),"export-audit-pending-test-")),root=join(parent,"private"),events:unknown[]=[],manager=new ExportLifecycleManager({root,legacyRoot:parent,minFreeBytes:1,closeTimeoutMs:50,reportError:error=>events.push(error)});try{const store=new PendingFinalStore(),logs:unknown[]=[],auth=new AdminAuthService(store,{allowedOrigins:["https://school.test"],secureCookies:false,csrfSecret:Buffer.alloc(32,7),logError:event=>logs.push(event)});await auth.bootstrap("admin","test-password-2026");const app=Fastify();await app.register(fastifyCookie);registerAdminAuthRoutes(app,auth);registerExportRoutes(app,auth,source,manager,10);await app.ready();const login=await app.inject({method:"POST",url:"/api/admin/login",headers:{host:"school.test",origin:"https://school.test","sec-fetch-site":"same-origin","content-type":"application/json"},payload:{username:"admin",password:"test-password-2026"}}),cookie=`${login.cookies[0]!.name}=${login.cookies[0]!.value}`,response=await app.inject({method:"GET",url:"/api/admin/export.xlsx?from=2026-08-01&to=2026-08-31",headers:{host:"school.test",cookie}});expect(response.statusCode).toBe(200);await app.close();expect(await readdir(root)).toHaveLength(0);expect(logs.some(value=>JSON.stringify(value).includes("audit_pending_timeout"))).toBe(true);expect(events.some(value=>String(value).includes("EXPORT_CLOSE_TIMEOUT"))).toBe(true);}finally{await rm(parent,{recursive:true,force:true});}},30_000);

  it("sanitizes forbidden XML code points and lone surrogates while preserving valid supplementary text",async()=>{const text="\uFFFF\uD800=安全\uDC00😀\t換行\n保留\r",unicode=inMemoryExportDataSource({...dataset,matches:[{...dataset.matches[0]!,player2:text}]});const bytes=await buildWorkbookBuffer(unicode,filters),book=new ExcelJS.Workbook();await book.xlsx.load(bytes as never);expect(book.getWorksheet("對戰紀錄")!.getCell("E9").value).toBe("'=安全😀\t換行\n保留\n");});

  it("wires default lifecycle janitor telemetry through sanitized admin reporting",async()=>{const root=join(tmpdir(),"steam-top-exports-private"),dir=join(root,`export-invalid-default-${Date.now()}`);await mkdir(dir,{recursive:true});await writeFile(join(dir,".active.json"),'{"pid":"private-name"}');await utimes(dir,new Date(0),new Date(0));const logs:unknown[]=[],store=new InMemoryAdminStore(),auth=new AdminAuthService(store,{allowedOrigins:["https://school.test"],secureCookies:false,csrfSecret:Buffer.alloc(32,8),logError:event=>logs.push(event)});await auth.bootstrap("admin","test-password-2026");const app=Fastify();await app.register(fastifyCookie);registerAdminAuthRoutes(app,auth);registerExportRoutes(app,auth,source);await app.ready();await app.close();expect(logs.some(value=>JSON.stringify(value).includes("admin.export.lifecycle"))).toBe(true);expect(JSON.stringify(logs)).not.toContain("private-name");await rm(dir,{recursive:true,force:true});});

  it("bounds worksheet rows and rejects oversized formula-like text without silent truncation",async()=>{const hostile="\t=cmd|' /C calc'!A0"+"x".repeat(40_000),bounded=inMemoryExportDataSource({...dataset,matches:[{...dataset.matches[0]!,player2:hostile}]});await expect(buildWorkbookBuffer(bounded,filters)).rejects.toThrow("EXPORT_CELL_LIMIT");await expect(buildWorkbookBuffer(inMemoryExportDataSource({...dataset,matches:[dataset.matches[0]!,dataset.matches[0]!]}),filters,{maxRowsPerSheet:9})).rejects.toThrow("EXPORT_ROW_LIMIT");});
  it("checks the final escaped cell length including the formula-safety prefix",async()=>{const plain="x".repeat(32_767),safeSource=inMemoryExportDataSource({...dataset,matches:[{...dataset.matches[0]!,player2:plain}]});expect((await buildWorkbookBuffer(safeSource,filters)).byteLength).toBeGreaterThan(1_000);const prefixed="="+"x".repeat(32_766),unsafe=inMemoryExportDataSource({...dataset,matches:[{...dataset.matches[0]!,player2:prefixed}]});await expect(buildWorkbookBuffer(unsafe,filters)).rejects.toThrow("EXPORT_CELL_LIMIT");});
});
