DO $catalog$
DECLARE actual text[]; expected text[] := ARRAY[
'deployment_environment:singleton:boolean:NO','deployment_environment:environment:character varying:NO','deployment_environment:restore_allowed:boolean:NO','deployment_environment:restore_target_id:uuid:NO',
'finalize_outbox:nonce:text:NO','finalize_outbox:restore_target_id:uuid:NO','finalize_outbox:app_role:text:NO','finalize_outbox:ledger_rows:bigint:NO','finalize_outbox:state:text:NO','finalize_outbox:created_at:timestamp with time zone:NO','finalize_outbox:deadline_at:timestamp with time zone:YES','finalize_outbox:lease_owner:text:YES','finalize_outbox:lease_generation:bigint:NO','finalize_outbox:ledger_hash:text:YES','finalize_outbox:system_identifier:text:YES','finalize_outbox:database_name:text:YES','finalize_outbox:ready_sha256:text:YES','finalize_outbox:preflight_sha256:text:YES','finalize_outbox:smoke_evidence:jsonb:YES','finalize_outbox:smoke_evidence_payload_b64:text:YES','finalize_outbox:smoke_evidence_sha256:text:YES','finalize_outbox:final_receipt:jsonb:YES','finalize_outbox:final_receipt_payload_b64:text:YES','finalize_outbox:final_receipt_sha256:text:YES','finalize_outbox:final_receipt_signature_b64:text:YES','finalize_outbox:final_receipt_signer_id:text:YES','finalize_outbox:legacy_ready_payload_b64:text:YES','finalize_outbox:legacy_ready_sha256:text:YES','finalize_outbox:legacy_ready_sha_file_b64:text:YES','finalize_outbox:legacy_ready_sha_text_b64:text:YES','finalize_outbox:legacy_ready_signer_id:text:YES','finalize_outbox:legacy_preflight_payload_b64:text:YES','finalize_outbox:legacy_preflight_sha256:text:YES','finalize_outbox:legacy_preflight_signature_b64:text:YES','finalize_outbox:legacy_preflight_signer_id:text:YES','finalize_outbox:observed_at:timestamp with time zone:YES','finalize_outbox:verified_at:timestamp with time zone:YES','finalize_outbox:aborted_at:timestamp with time zone:YES',
'platform_installation:singleton:boolean:NO','platform_installation:host_id:text:NO','platform_installation:bootstrap_digest:text:NO','platform_installation:authorization_nonce:text:NO','platform_installation:claimed_at:timestamp with time zone:NO','platform_installation:generation:bigint:NO',
'promotion_audit:id:bigint:NO','promotion_audit:restore_target_id:uuid:NO','promotion_audit:app_role:text:NO','promotion_audit:cutover_nonce:text:NO','promotion_audit:ledger_rows:bigint:NO','promotion_audit:finalized_at:timestamp with time zone:YES',
'promotion_outbox:nonce:text:NO','promotion_outbox:restore_target_id:uuid:NO','promotion_outbox:system_identifier:text:NO','promotion_outbox:database_name:text:NO','promotion_outbox:app_role:text:NO','promotion_outbox:ledger_rows:bigint:NO','promotion_outbox:state:text:NO','promotion_outbox:created_at:timestamp with time zone:NO'];
BEGIN
SELECT array_agg(table_name||':'||column_name||':'||data_type||':'||is_nullable ORDER BY table_name,ordinal_position) INTO actual FROM information_schema.columns WHERE table_schema='restore_control';
IF actual IS DISTINCT FROM expected THEN RAISE EXCEPTION 'restore_control column/type/nullability drift';END IF;
IF (SELECT nspowner<>current_user::regrole::oid OR nspacl IS NOT NULL FROM pg_namespace WHERE nspname='restore_control') THEN RAISE EXCEPTION 'restore_control schema owner/ACL drift';END IF;
IF EXISTS(SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='restore_control' AND c.relkind IN('r','p','S') AND (c.relowner<>current_user::regrole::oid OR c.relacl IS NOT NULL)) THEN RAISE EXCEPTION 'restore_control relation owner/ACL drift';END IF;
IF EXISTS(SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='restore_control' AND (c.relkind NOT IN('r','p','S','i') OR (c.relkind='i' AND NOT EXISTS(SELECT 1 FROM pg_constraint k WHERE k.conindid=c.oid)))) THEN RAISE EXCEPTION 'restore_control relation/index drift';END IF;
IF EXISTS(SELECT 1 FROM pg_policies WHERE schemaname='restore_control') THEN RAISE EXCEPTION 'restore_control policy drift';END IF;
IF EXISTS(SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid=t.typnamespace WHERE n.nspname='restore_control' AND t.typtype<>'c' AND NOT(t.typtype='b' AND EXISTS(SELECT 1 FROM pg_type e WHERE e.oid=t.typelem AND e.typtype='c'))) THEN RAISE EXCEPTION 'restore_control type drift';END IF;
IF (SELECT count(*) FROM pg_constraint c JOIN pg_class r ON r.oid=c.conrelid JOIN pg_namespace n ON n.oid=r.relnamespace WHERE n.nspname='restore_control')<>17 THEN RAISE EXCEPTION 'restore_control constraint drift';END IF;
IF EXISTS(SELECT 1 FROM pg_constraint c JOIN pg_class r ON r.oid=c.conrelid JOIN pg_namespace n ON n.oid=r.relnamespace WHERE n.nspname='restore_control' AND c.contype NOT IN('p','u','c')) THEN RAISE EXCEPTION 'restore_control FK/constraint kind drift';END IF;
IF (SELECT count(*) FILTER(WHERE c.contype='p')=5 AND count(*) FILTER(WHERE c.contype='u')=2 AND count(*) FILTER(WHERE c.contype='c')=10 FROM pg_constraint c JOIN pg_class r ON r.oid=c.conrelid JOIN pg_namespace n ON n.oid=r.relnamespace WHERE n.nspname='restore_control') IS NOT TRUE THEN RAISE EXCEPTION 'restore_control constraint fingerprint drift';END IF;
SELECT array_agg(r.relname||':'||c.conname||':'||c.contype::text||':'||pg_get_constraintdef(c.oid,false) ORDER BY r.relname,c.conname) INTO actual FROM pg_constraint c JOIN pg_class r ON r.oid=c.conrelid JOIN pg_namespace n ON n.oid=r.relnamespace WHERE n.nspname='restore_control';
IF actual IS DISTINCT FROM ARRAY[
'deployment_environment:deployment_environment_pkey:p:PRIMARY KEY (singleton)','deployment_environment:deployment_environment_restore_guard:c:CHECK ((((environment)::text = ''production''::text) AND (restore_allowed = false)) OR ((environment)::text <> ''production''::text))','deployment_environment:deployment_environment_singleton:c:CHECK ((singleton = true))','deployment_environment:deployment_environment_value:c:CHECK (((environment)::text = ANY ((ARRAY[''production''::character varying, ''staging''::character varying, ''test''::character varying, ''development''::character varying])::text[])))',
'finalize_outbox:finalize_outbox_pkey:p:PRIMARY KEY (nonce)','finalize_outbox:finalize_outbox_state_machine:c:CHECK ((state = ANY (ARRAY[''legacy-committed''::text, ''preflight-recorded''::text, ''connect-granted-pending-smoke''::text, ''smoke-observed''::text, ''verified''::text, ''aborted''::text])))',
'platform_installation:platform_installation_authorization_nonce_check:c:CHECK ((authorization_nonce ~ ''^[a-f0-9]{64}$''::text))','platform_installation:platform_installation_bootstrap_digest_check:c:CHECK ((bootstrap_digest ~ ''^[a-f0-9]{64}$''::text))','platform_installation:platform_installation_generation_check:c:CHECK ((generation > 0))','platform_installation:platform_installation_host_id_bootstrap_digest_authorization_nonce_key:u:UNIQUE (host_id, bootstrap_digest, authorization_nonce)','platform_installation:platform_installation_host_id_check:c:CHECK ((host_id ~ ''^[a-f0-9]{64}$''::text))','platform_installation:platform_installation_pkey:p:PRIMARY KEY (singleton)','platform_installation:platform_installation_singleton_check:c:CHECK (singleton)',
'promotion_audit:promotion_audit_cutover_nonce_key:u:UNIQUE (cutover_nonce)','promotion_audit:promotion_audit_pkey:p:PRIMARY KEY (id)','promotion_outbox:promotion_outbox_pkey:p:PRIMARY KEY (nonce)','promotion_outbox:promotion_outbox_state_check:c:CHECK ((state = ''committed''::text))'] THEN RAISE EXCEPTION 'restore_control per-constraint definition drift: %',actual;END IF;
IF (SELECT array_agg(t.relname||':'||i.relname||':'||ix.indisprimary||':'||ix.indisunique||':'||pg_get_indexdef(i.oid) ORDER BY t.relname,i.relname) FROM pg_index ix JOIN pg_class i ON i.oid=ix.indexrelid JOIN pg_class t ON t.oid=ix.indrelid JOIN pg_namespace n ON n.oid=t.relnamespace WHERE n.nspname='restore_control') IS DISTINCT FROM ARRAY[
'deployment_environment:deployment_environment_pkey:true:true:CREATE UNIQUE INDEX deployment_environment_pkey ON restore_control.deployment_environment USING btree (singleton)','finalize_outbox:finalize_outbox_pkey:true:true:CREATE UNIQUE INDEX finalize_outbox_pkey ON restore_control.finalize_outbox USING btree (nonce)','platform_installation:platform_installation_host_id_bootstrap_digest_authorization_nonce_key:false:true:CREATE UNIQUE INDEX platform_installation_host_id_bootstrap_digest_authorization_nonce_key ON restore_control.platform_installation USING btree (host_id, bootstrap_digest, authorization_nonce)','platform_installation:platform_installation_pkey:true:true:CREATE UNIQUE INDEX platform_installation_pkey ON restore_control.platform_installation USING btree (singleton)','promotion_audit:promotion_audit_cutover_nonce_key:false:true:CREATE UNIQUE INDEX promotion_audit_cutover_nonce_key ON restore_control.promotion_audit USING btree (cutover_nonce)','promotion_audit:promotion_audit_pkey:true:true:CREATE UNIQUE INDEX promotion_audit_pkey ON restore_control.promotion_audit USING btree (id)','promotion_outbox:promotion_outbox_pkey:true:true:CREATE UNIQUE INDEX promotion_outbox_pkey ON restore_control.promotion_outbox USING btree (nonce)'] THEN RAISE EXCEPTION 'restore_control per-index definition drift';END IF;
IF (SELECT count(*) FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='restore_control')<>3 THEN RAISE EXCEPTION 'restore_control function count drift';END IF;
IF (SELECT array_agg(p.proname||':'||l.lanname||':'||p.provolatile||':'||p.proparallel||':'||p.proleakproof||':'||p.prosecdef||':'||coalesce(array_to_string(p.proconfig,','),'') ORDER BY p.proname) FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace JOIN pg_language l ON l.oid=p.prolang WHERE n.nspname='restore_control') IS DISTINCT FROM ARRAY['assert_pristine_platform_installation:plpgsql:v:u:false:false:','deletion_audit_sha256:sql:s:u:false:false:','steam_top_protect_deployment_environment:plpgsql:v:u:false:false:'] THEN RAISE EXCEPTION 'restore_control function safety attribute drift';END IF;
IF EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace JOIN pg_language l ON l.oid=p.prolang WHERE n.nspname='restore_control' AND (p.proowner<>current_user::regrole::oid OR p.prosecdef OR p.proacl IS NOT NULL OR pg_get_function_identity_arguments(p.oid)<>'' OR (p.proname='deletion_audit_sha256' AND (l.lanname<>'sql' OR p.provolatile<>'s' OR p.prorettype<>'text'::regtype OR p.prosrc NOT LIKE '%completedAtMicros%')) OR (p.proname='assert_pristine_platform_installation' AND (l.lanname<>'plpgsql' OR p.prorettype<>'void'::regtype OR p.prosrc NOT LIKE '%durable public schema drift%')) OR (p.proname='steam_top_protect_deployment_environment' AND (l.lanname<>'plpgsql' OR p.prorettype<>'trigger'::regtype OR p.prosrc NOT LIKE '%RESTORE_NONPRODUCTION_DATA%')))) THEN RAISE EXCEPTION 'restore_control function definition/trust drift';END IF;
IF EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='restore_control' AND encode(digest(convert_to(p.prosrc,'UTF8'),'sha256'),'hex')<>CASE p.proname WHEN 'steam_top_protect_deployment_environment' THEN current_setting('steam_top.expected_protect_function_sha') WHEN 'deletion_audit_sha256' THEN current_setting('steam_top.expected_deletion_function_sha') WHEN 'assert_pristine_platform_installation' THEN current_setting('steam_top.expected_pristine_function_sha') ELSE '' END) THEN RAISE EXCEPTION 'restore_control function body fingerprint drift';END IF;
IF EXISTS(SELECT 1 FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='restore_control' AND NOT t.tgisinternal AND (t.tgenabled<>'O' OR pg_get_triggerdef(t.oid) NOT LIKE 'CREATE TRIGGER deployment_environment_% BEFORE % ON restore_control.deployment_environment%')) THEN RAISE EXCEPTION 'restore_control trigger drift';END IF;
IF (SELECT count(*) FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='restore_control' AND NOT t.tgisinternal)<>2 THEN RAISE EXCEPTION 'restore_control trigger count drift';END IF;
IF (SELECT array_agg(t.tgname ORDER BY t.tgname) FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='restore_control' AND NOT t.tgisinternal) IS DISTINCT FROM ARRAY['deployment_environment_is_protected','deployment_environment_truncate_is_protected'] THEN RAISE EXCEPTION 'restore_control trigger identity drift';END IF;
IF (SELECT array_agg(t.tgname||':'||t.tgenabled||':'||pg_get_triggerdef(t.oid,false) ORDER BY t.tgname) FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='restore_control' AND NOT t.tgisinternal) IS DISTINCT FROM ARRAY['deployment_environment_is_protected:O:CREATE TRIGGER deployment_environment_is_protected BEFORE DELETE OR UPDATE ON restore_control.deployment_environment FOR EACH ROW EXECUTE FUNCTION restore_control.steam_top_protect_deployment_environment()','deployment_environment_truncate_is_protected:O:CREATE TRIGGER deployment_environment_truncate_is_protected BEFORE TRUNCATE ON restore_control.deployment_environment FOR EACH STATEMENT EXECUTE FUNCTION restore_control.steam_top_protect_deployment_environment()'] THEN RAISE EXCEPTION 'restore_control trigger definition digest drift';END IF;
IF (SELECT count(*) FROM pg_attrdef d JOIN pg_class c ON c.oid=d.adrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='restore_control')<>11 THEN RAISE EXCEPTION 'restore_control default drift';END IF;
IF NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='restore_control' AND table_name='deployment_environment' AND column_name='environment' AND column_default='''production''::character varying') OR NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='restore_control' AND table_name='platform_installation' AND column_name='generation' AND column_default='1') OR NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='restore_control' AND table_name='finalize_outbox' AND column_name='lease_generation' AND column_default='0') THEN RAISE EXCEPTION 'restore_control default definition drift';END IF;
IF (SELECT array_agg(table_name||':'||column_name||':'||column_default ORDER BY table_name,ordinal_position) FROM information_schema.columns WHERE table_schema='restore_control' AND column_default IS NOT NULL) IS DISTINCT FROM ARRAY['deployment_environment:singleton:true','deployment_environment:environment:''production''::character varying','deployment_environment:restore_allowed:false','deployment_environment:restore_target_id:gen_random_uuid()','finalize_outbox:created_at:clock_timestamp()','finalize_outbox:lease_generation:0','platform_installation:singleton:true','platform_installation:claimed_at:clock_timestamp()','platform_installation:generation:1','promotion_audit:id:nextval(''restore_control.promotion_audit_id_seq''::regclass)','promotion_outbox:created_at:clock_timestamp()'] THEN RAISE EXCEPTION 'restore_control per-default definition drift';END IF;
END $catalog$;
