#!/usr/bin/env bash
set -euo pipefail
[[ $(id -u) -eq 0 && $# -eq 8 ]]||{ echo "host deployment refused" >&2;exit 1;};artifact=$1;env_file=$2;manifest_sha=$3;repository=$4;commit=$5;nonce=$6;receipt=$7;expected_state=$8;[[ $nonce =~ ^[a-f0-9]{64}$ && $receipt == /* && ! -e $receipt && -n ${HOST_RECEIPT_SIGNING_KEY:-} && -n ${PRODUCTION_STATE_TOKEN_FILE:-} && -n ${HOST_RECEIPT_PGSERVICE:-} && -n ${ADMIN_SMOKE_PASSWORD_FILE:-} && -f $PRODUCTION_STATE_TOKEN_FILE && ! -L $PRODUCTION_STATE_TOKEN_FILE && -f $ADMIN_SMOKE_PASSWORD_FILE && ! -L $ADMIN_SMOKE_PASSWORD_FILE && $expected_state =~ ^(none|[1-9][0-9]*\|[a-f0-9]{64})$ ]]||exit 1
script_dir=$(CDPATH= cd -- "$(dirname -- "$0")"&&pwd -P);source "${script_dir%/scripts}/infra/backup/host-trust-guard.sh";for private in "$HOST_RECEIPT_SIGNING_KEY" "$PRODUCTION_STATE_TOKEN_FILE" "$ADMIN_SMOKE_PASSWORD_FILE" "${PGSERVICEFILE:-}" "${PGPASSFILE:-}";do backup_private_file "$private"||{ echo "host private file trust failed" >&2;exit 1;};done;backup_reject_libpq_overrides HOST_RECEIPT_PGSERVICE||exit 1;lock=/var/lock/steam-top-production.lock;mkdir_lock=""
if command -v flock >/dev/null 2>&1;then exec 9>"$lock";flock -n 9||exit 75;else mkdir_lock="$lock.d";mkdir "$mkdir_lock" 2>/dev/null||exit 75;trap 'rmdir "$mkdir_lock" 2>/dev/null||true' EXIT;fi
tmp=$(mktemp -d);trap 'rm -rf "$tmp";[[ -z $mkdir_lock ]]||rmdir "$mkdir_lock" 2>/dev/null||true' EXIT;GH_TOKEN=$(<"$PRODUCTION_STATE_TOKEN_FILE");ADMIN_SMOKE_USERNAME=admin;ADMIN_SMOKE_PASSWORD=$(<"$ADMIN_SMOKE_PASSWORD_FILE");export GH_TOKEN ADMIN_SMOKE_USERNAME ADMIN_SMOKE_PASSWORD
latest=$(gh api "repos/$repository/deployments?environment=production&per_page=1" --jq 'if length==0 then "none" else (.[0].id|tostring)+"|"+.[0].payload.manifestSha256 end');[[ $latest == "$expected_state" ]]||{ echo "protected production state changed" >&2;exit 75;}
node "$script_dir/production-env.mjs" "$env_file" "$tmp/env";origin=$(sed -n 's/^PUBLIC_ORIGIN=//p' "$tmp/env");"$script_dir/deploy-production.sh" "$artifact" "$env_file" "$manifest_sha" "$repository" "$commit";"$script_dir/production-smoke.sh" "$origin"
ids=$(docker compose --project-directory "${script_dir%/scripts}" --env-file "$tmp/env" -f "${script_dir%/scripts}/compose.yaml" ps -q);[[ -n $ids ]];docker inspect $ids >"$tmp/containers.json"
PGSERVICE=$HOST_RECEIPT_PGSERVICE psql -X -v ON_ERROR_STOP=1 -AtF '|' -c "select (select system_identifier from pg_control_system()),current_database(),environment,restore_allowed from restore_control.deployment_environment where singleton"|node -e 'const fs=require("fs"),s=fs.readFileSync(0,"utf8").trim().split("|");if(s.length!==4)process.exit(1);fs.writeFileSync(process.argv[1],JSON.stringify({systemIdentifier:s[0],database:s[1],markerEnvironment:s[2],restoreAllowed:s[3]==="t"})+"\n")' "$tmp/database.json"
node "$script_dir/create-host-deployment-receipt.mjs" "$artifact/release-manifest.json" "$tmp/containers.json" "$tmp/database.json" "$manifest_sha" "$commit" "$nonce" "$origin" "$receipt";chmod 400 "$receipt";ssh-keygen -Y sign -q -f "$HOST_RECEIPT_SIGNING_KEY" -n steam-top-production-deployment "$receipt";chmod 400 "$receipt.sig"
