#!/usr/bin/env bash
set -euo pipefail
exec 3>&1;exec 1>&2
die(){ echo "host deployment refused: $1" >&2;exit 1;}
[[ $(id -u) -eq 0 && $# -eq 8 ]]||die "root and eight arguments required";artifact=$1;env_file=$2;manifest_sha=$3;repository=$4;commit=$5;nonce=$6;expected_state=$7;deployment_id=$8
script_path=$(realpath "$0");script_dir=$(CDPATH= cd -- "$(dirname -- "$script_path")"&&pwd -P);root=$(CDPATH= cd -- "$script_dir/.."&&pwd -P);source "$root/infra/backup/host-trust-guard.sh"
[[ $script_path == /opt/steam-top/scripts/host-deploy-and-receipt.sh ]]||die "installed canonical path required";backup_trusted_root_deployment "$root" "$script_dir" "$root/infra/backup"||die "installed deployment trust";backup_root_file_mode "$script_path" 555||die "installed script mode"
for name in HOST_RECEIPT_SIGNING_KEY PRODUCTION_AUTHORIZATION_DIR HOST_RECEIPT_PGSERVICE ADMIN_SMOKE_SECRET_FILE PGSERVICEFILE PGPASSFILE HOST_RECEIPT_OUTBOX_DIR;do [[ -n ${!name:-} ]]||die "$name required";done
for private in "$HOST_RECEIPT_SIGNING_KEY" "$ADMIN_SMOKE_SECRET_FILE" "$PGSERVICEFILE" "$PGPASSFILE";do backup_private_file "$private"||die "private file trust";done;backup_reject_libpq_overrides HOST_RECEIPT_PGSERVICE||die "libpq boundary"
[[ $nonce =~ ^[a-f0-9]{64}$ && $expected_state =~ ^(none|[1-9][0-9]*\|[a-f0-9]{64})$ && $deployment_id =~ ^[1-9][0-9]*$ ]]||die "state binding";[[ -d $HOST_RECEIPT_OUTBOX_DIR && ! -L $HOST_RECEIPT_OUTBOX_DIR ]]||die "outbox";read -r out_owner out_mode < <(stat -c '%u %a' "$HOST_RECEIPT_OUTBOX_DIR");[[ $out_owner == 0 && $out_mode == 700 ]]||die "outbox mode"
lock=/var/lock/steam-top-production.lock;[[ -f $lock && ! -L $lock ]]||die "precreated lock required";read -r lock_owner lock_mode < <(stat -c '%u %a' "$lock");[[ $lock_owner == 0 && $lock_mode == 600 ]]||die "lock mode";command -v flock >/dev/null||die "Linux flock required";exec 9<>"$lock";flock -n 9||exit 75
tmp=$(mktemp -d);receipt="$HOST_RECEIPT_OUTBOX_DIR/$nonce.json";signature="$receipt.sig";cleanup(){ rm -rf "$tmp";};trap cleanup EXIT INT TERM
[[ ! -e $receipt && ! -e $signature ]]||die "nonce already used";[[ -d $PRODUCTION_AUTHORIZATION_DIR && ! -L $PRODUCTION_AUTHORIZATION_DIR ]]||die "authorization directory";read -r auth_owner auth_mode < <(stat -c '%u %a' "$PRODUCTION_AUTHORIZATION_DIR");[[ $auth_owner == 0 && $auth_mode == 700 ]]||die "authorization directory trust"
authorization="$PRODUCTION_AUTHORIZATION_DIR/$nonce.json";[[ -f $authorization && ! -L $authorization ]]||die "authorization missing";backup_root_file_mode "$authorization" 400||die "authorization trust"
node - "$authorization" "$repository" "$deployment_id" "$nonce" "$manifest_sha" "$commit" "$expected_state" <<'NODE'
const a=require(process.argv[2]);if(a.schemaVersion!==1||a.repository!==process.argv[3]||a.deploymentId!==process.argv[4]||a.nonce!==process.argv[5]||a.manifestSha256!==process.argv[6]||a.commit!==process.argv[7]||a.expectedPreviousState!==process.argv[8])process.exit(1);
NODE
mv "$authorization" "$authorization.consumed";chmod 400 "$authorization.consumed"
node "$script_dir/production-env.mjs" "$env_file" "$tmp/env";origin=$(sed -n 's/^PUBLIC_ORIGIN=//p' "$tmp/env");server_ref=$(sed -n 's/^SERVER_IMAGE=//p' "$tmp/env");web_ref=$(sed -n 's/^WEB_IMAGE=//p' "$tmp/env");db_ref=$(sed -n 's/^DATABASE_IMAGE=//p' "$tmp/env");caddy_repo=$(sed -n 's/^CADDY_IMAGE_REPOSITORY=//p' "$tmp/env");caddy_digest=$(sed -n 's/^CADDY_IMAGE_DIGEST=//p' "$tmp/env");caddy_ref="$caddy_repo@$caddy_digest"
"$script_dir/deploy-production.sh" "$artifact" "$env_file" "$manifest_sha" "$repository" "$commit"
PGSERVICE=$HOST_RECEIPT_PGSERVICE psql -X -v ON_ERROR_STOP=1 -v nonce="$nonce" <<'SQL'
begin;select pg_advisory_xact_lock(1937002751);create table if not exists restore_control.deployment_probe(nonce text primary key check(nonce~'^[a-f0-9]{64}$'),restore_target_id uuid not null,system_identifier text not null,created_at timestamptz not null default clock_timestamp(),consumed_at timestamptz);insert into restore_control.deployment_probe(nonce,restore_target_id,system_identifier)select :'nonce',restore_target_id,(select system_identifier::text from pg_control_system()) from restore_control.deployment_environment where singleton;commit;
SQL
ADMIN_SMOKE_SECRET_FILE="$ADMIN_SMOKE_SECRET_FILE" "$script_dir/production-smoke.sh" "$origin" "$nonce"
ids=$(docker compose --project-directory "$root" --env-file "$tmp/env" -f "$root/compose.yaml" ps -aq);[[ -n $ids ]]||die "no containers";docker inspect $ids >"$tmp/containers.json";docker image inspect "$server_ref" "$web_ref" "$db_ref" "$caddy_ref" >"$tmp/images.json"
PGSERVICE=$HOST_RECEIPT_PGSERVICE psql -X -v ON_ERROR_STOP=1 -AtF '|' -c "select (select system_identifier from pg_control_system()),current_database(),environment,restore_allowed,restore_target_id from restore_control.deployment_environment where singleton"|node -e 'const fs=require("fs"),s=fs.readFileSync(0,"utf8").trim().split("|");if(s.length!==5)process.exit(1);fs.writeFileSync(process.argv[1],JSON.stringify({systemIdentifier:s[0],database:s[1],markerEnvironment:s[2],restoreAllowed:s[3]==="t",restoreTargetId:s[4]})+"\n")' "$tmp/database.json"
node "$script_dir/create-host-deployment-receipt.mjs" "$artifact/release-manifest.json" "$tmp/containers.json" "$tmp/images.json" "$tmp/database.json" "$caddy_ref" "$manifest_sha" "$commit" "$nonce" "$origin" "$receipt";ssh-keygen -Y sign -q -f "$HOST_RECEIPT_SIGNING_KEY" -n steam-top-production-deployment "$receipt";chmod 400 "$receipt" "$signature"
printf 'RECEIPT-BEGIN %s\n' "$nonce" >&3;base64 <"$receipt" >&3;printf 'RECEIPT-SIGNATURE\n' >&3;base64 <"$signature" >&3;printf 'RECEIPT-END %s\n' "$nonce" >&3
