#!/usr/bin/env bash
set -euo pipefail
[[ $(id -u) -ne 0 && -n ${RUNNER_TEMP:-} && ${GITHUB_SHA:-} =~ ^[a-f0-9]{40}$ ]]||exit 2
root=$(CDPATH= cd -- "$(dirname -- "$0")/.."&&pwd -P);manifest="$RUNNER_TEMP/canonical-runtime.sha256";node "$root/scripts/create-runtime-files-manifest.mjs" "$root" "$manifest";runtime_sha=$("$root/scripts/portable-sha256.sh" digest "$manifest")
for install_root in /opt/steam-top "/opt/steam-top/releases/$runtime_sha";do sudo install -d -o root -g root -m 0755 "$install_root";while read -r _ mode path;do sudo install -D -o root -g root -m "$mode" "$root/$path" "$install_root/$path";done <"$manifest";sudo install -o root -g root -m 0444 "$manifest" "$install_root/runtime-files.sha256";node - "$install_root" "$runtime_sha" "$GITHUB_SHA" "$RUNNER_TEMP/canonical-runtime-receipt.json" <<'NODE'
const fs=require("fs"),[installRoot,runtimeManifestSha256,commit,out]=process.argv.slice(2);fs.writeFileSync(out,JSON.stringify({schemaVersion:1,purpose:"steam-top-runtime-install",installRoot,runtimeManifestSha256,commit,sealedAt:new Date().toISOString()})+"\n",{mode:0o444});
NODE
sudo install -o root -g root -m 0444 "$RUNNER_TEMP/canonical-runtime-receipt.json" "$install_root/runtime-install-receipt.json";sudo find "$install_root" -type d -exec chown root:root {} +;sudo find "$install_root" -type d -exec chmod 0555 {} +;sudo env RUNTIME_INSTALL_MANIFEST_SHA256="$runtime_sha" "$install_root/scripts/verify-runtime-install.sh" "$install_root";done
archive="$RUNNER_TEMP/canonical-bootstrap.tar.gz";"$root/infra/bootstrap/create-package.sh" "$archive";mkdir "$RUNNER_TEMP/canonical-bootstrap-unpack";tar -xzf "$archive" -C "$RUNNER_TEMP/canonical-bootstrap-unpack";bootstrap_sha=$("$root/scripts/portable-sha256.sh" digest "$RUNNER_TEMP/canonical-bootstrap-unpack/bootstrap-files.sha256");archive_sha=$("$root/scripts/portable-sha256.sh" digest "$archive");ssh-keygen -q -t ed25519 -N '' -f "$RUNNER_TEMP/canonical-bootstrap-source";ssh-keygen -Y sign -q -f "$RUNNER_TEMP/canonical-bootstrap-source" -n steam-top-bootstrap-source "$archive";printf 'bootstrap-ci %s\n' "$(<"$RUNNER_TEMP/canonical-bootstrap-source.pub")" >"$RUNNER_TEMP/canonical-bootstrap-allowed"
node - "$RUNNER_TEMP/canonical-bootstrap-trust.json" "$bootstrap_sha" "${GITHUB_REPOSITORY:-school/steam-top}" "$GITHUB_SHA" <<'NODE'
const fs=require("fs"),[out,bootstrapSha256,repository,workflowSha]=process.argv.slice(2);fs.writeFileSync(out,JSON.stringify({schemaVersion:1,purpose:"steam-top-bootstrap-trust",bootstrapSha256,repository,workflowIdentity:`${repository}/.github/workflows/db.yml`,workflowRef:"refs/heads/main",workflowSha,deploymentPurpose:"production",githubTokenFile:"/run/steam-top-canonical-ci/github-token",hostReceiptOutbox:"/run/steam-top-canonical-ci/outbox",hostReceiptAllowedSigners:"/run/steam-top-canonical-ci/host-allowed",hostReceiptSignerId:"host@test",ledgerAllowedSigners:"/run/steam-top-canonical-ci/ledger-allowed",ledgerSignerId:"host@test",productionStateDir:"/run/steam-top-canonical-ci/state",productionStateSigningKey:"/run/steam-top-canonical-ci/state-key",productionStateAllowedSigners:"/run/steam-top-canonical-ci/state-allowed",productionStateSignerId:"host@test"})+"\n",{mode:0o600});
NODE
sudo env EXPECTED_BOOTSTRAP_ARCHIVE_SHA256="$archive_sha" BOOTSTRAP_ALLOWED_SIGNERS_FILE="$RUNNER_TEMP/canonical-bootstrap-allowed" "$root/infra/bootstrap/install-bootstrap.sh" "$archive" "$archive.sig" bootstrap-ci "$RUNNER_TEMP/canonical-bootstrap-trust.json";printf 'RUNTIME_INSTALL_MANIFEST_SHA256=%s\n' "$runtime_sha"
