#!/usr/bin/env bash
set -euo pipefail
[[ $(id -u) -eq 0 && $# -eq 1 ]]||exit 2;/opt/steam-top-bootstrap/verify-bootstrap.sh;bundle=$1;config=/etc/steam-top-bootstrap/trust.json;[[ -f $bundle && ! -L $bundle ]]||exit 1;lock=/var/lock/steam-top-production.lock;[[ -f $lock && ! -L $lock ]]||exit 1;read -r lock_owner lock_mode < <(stat -c '%u %a' "$lock");[[ $lock_owner == 0 && $lock_mode == 600 ]]||exit 1;exec 9<>"$lock";flock -n 9||exit 75
mapfile -t values < <(node - "$config" "$bundle" <<'NODE'
const c=require(process.argv[2]),a=require(process.argv[3]),paths=["githubTokenFile","hostReceiptOutbox","hostReceiptAllowedSigners","productionStateDir","productionStateSigningKey"];for(const k of paths)if(typeof c[k]!=="string"||!c[k].startsWith("/"))process.exit(1);if(!/^[A-Za-z0-9@._-]+$/.test(c.hostReceiptSignerId)||a.schemaVersion!==1||a.purpose!=="production-deployment-authorization"||a.repository!==c.repository)process.exit(1);for(const k of ["repository","githubTokenFile","hostReceiptOutbox","hostReceiptAllowedSigners","hostReceiptSignerId","productionStateDir","productionStateSigningKey"])console.log(c[k]);console.log(a.deploymentId);console.log(a.nonce);
NODE
);repository=${values[0]};token=${values[1]};outbox=${values[2]};allowed=${values[3]};signer=${values[4]};state_dir=${values[5]};state_key=${values[6]};deployment_id=${values[7]};nonce=${values[8]};receipt_root="$outbox/receipts/$nonce";[[ -d $receipt_root && ! -L $receipt_root && -L $receipt_root/current ]]||exit 1;receipt_generation=$(realpath "$receipt_root/current");[[ $receipt_generation == "$receipt_root/"* ]]||exit 1;receipt="$receipt_generation/payload.json";receipt_sig="$receipt.sig";ledger_root="$outbox/deployment-ledger";tmpdir=$(mktemp -d);trap 'rm -rf "$tmpdir"' EXIT
for file in "$token" "$allowed" "$state_key" "$receipt" "$receipt_sig";do [[ -f $file && ! -L $file ]]||exit 1;done;ssh-keygen -Y verify -q -f "$allowed" -I "$signer" -n steam-top-production-deployment -s "$receipt_sig" <"$receipt"||exit 1
runtime=$(realpath /opt/steam-top/current);node "$runtime/scripts/inspect-signed-generation-chain.mjs" "$ledger_root" steam-top-host-deployment-ledger >"$tmpdir/ledger.json";while IFS=$'\t' read -r payload signature;do ssh-keygen -Y verify -q -f "$allowed" -I "$signer" -n steam-top-host-deployment-ledger -s "$signature" <"$payload"||exit 1;done < <(node -e 'for(const x of require(process.argv[1]).generations)console.log(`${x.payloadPath}\t${x.signaturePath}`)' "$tmpdir/ledger.json");ledger=$(node -e 'const h=require(process.argv[1]).head;if(!h)process.exit(1);process.stdout.write(h.payloadPath)' "$tmpdir/ledger.json")
GH_TOKEN=$(<"$token");export GH_TOKEN;latest=$(gh api "repos/$repository/deployments?environment=production&per_page=1" --jq '.[0] | (.id|tostring)+"|"+.payload.nonce+"|"+.payload.manifestSha256');expected_latest=$(node -p '`${require(process.argv[1]).deploymentId}|${require(process.argv[1]).nonce}|${require(process.argv[1]).manifestSha256}`' "$bundle");[[ $latest == "$expected_latest" ]]||exit 1
install -d -o root -g root -m 0700 "$state_dir";generations="$state_dir/generations";activations="$state_dir/activations/$nonce";install -d -o root -g root -m 0700 "$generations" "$state_dir/activations" "$activations";activation=;resolve_activation(){ local target;[[ -L $activations/current ]]||return 1;target=$(realpath "$activations/current");[[ $target == "$activations/"* ]]||return 1;activation="$target/payload.json";[[ -f $activation && ! -L $activation && -f $activation.sig && ! -L $activation.sig ]];};resolve_activation||true;emit_activation(){ printf 'RECEIPT-BEGIN %s\n' "$nonce";base64 <"$activation";printf 'RECEIPT-SIGNATURE\n';base64 <"$activation.sig";printf 'RECEIPT-END %s\n' "$nonce";};node "$runtime/scripts/inspect-signed-generation-chain.mjs" "$generations" production >"$tmpdir/state-chain.json";while IFS=$'\t' read -r payload signature;do ssh-keygen -Y verify -q -f <(printf 'state %s\n' "$(ssh-keygen -y -f "$state_key")") -I state -n steam-top-protected-deployment-state -s "$signature" <"$payload"||exit 1;done < <(node -e 'for(const x of require(process.argv[1]).generations)console.log(`${x.payloadPath}\t${x.signaturePath}`)' "$tmpdir/state-chain.json");if node - "$tmpdir/state-chain.json" "$deployment_id" "$nonce" <<'NODE'
const h=require(process.argv[2]).head?.payload;process.exit(h&&h.deploymentId===process.argv[3]&&h.nonce===process.argv[4]?0:1)
NODE
then head=$(node -p 'require(process.argv[1]).head.payloadPath' "$tmpdir/state-chain.json");ln -sfn "generations/$(basename "$(dirname "$head")")" "$state_dir/current.next";mv -Tf "$state_dir/current.next" "$state_dir/current";if [[ -z $activation ]];then activation_generation=$(mktemp -d "$activations/.generation.XXXXXX");activation="$activation_generation/payload.json";node - "$activation" "$deployment_id" "$nonce" "$tmpdir/state-chain.json" <<'NODE'
const fs=require("fs"),[path,id,nonce,chain]=process.argv.slice(2),head=require(chain).head;fs.writeFileSync(path,JSON.stringify({schemaVersion:1,purpose:"production-activation-receipt",deploymentId:id,nonce,stateDigest:head.digest,activatedAt:head.payload.activatedAt})+"\n",{flag:"wx",mode:0o400});
NODE
ssh-keygen -Y sign -q -f "$state_key" -n steam-top-production-activation "$activation";chmod 400 "$activation" "$activation.sig";activation_digest=$(sha256sum "$activation"|awk '{print $1}');activation_final="$activations/$activation_digest";mv "$activation_generation" "$activation_final";chmod 500 "$activation_final";ln -s "$(basename "$activation_final")" "$activations/current.next";mv -Tf "$activations/current.next" "$activations/current";activation="$activation_final/payload.json";fi;ssh-keygen -Y verify -q -f <(printf 'state %s\n' "$(ssh-keygen -y -f "$state_key")") -I state -n steam-top-production-activation -s "$activation.sig" <"$activation"||exit 1;node - "$activation" "$deployment_id" "$nonce" "$tmpdir/state-chain.json" <<'NODE'
const a=require(process.argv[2]),h=require(process.argv[5]).head;if(a.schemaVersion!==1||a.purpose!=="production-activation-receipt"||a.deploymentId!==process.argv[3]||a.nonce!==process.argv[4]||a.stateDigest!==h.digest)process.exit(1);
NODE
emit_activation;exit 0;fi;generation=$(mktemp -d "$generations/.generation.XXXXXX");tmp="$generation/payload.json";node - "$bundle" "$receipt" "$ledger" "$tmpdir/state-chain.json" "$tmp" <<'NODE'
const fs=require("fs"),a=require(process.argv[2]),r=require(process.argv[3]),ledger=require(process.argv[4]),chain=require(process.argv[5]),head=chain.head,protectedState=head?`${head.payload.deploymentId}|${head.payload.manifestSha256}`:"none";if(r.schemaVersion!==4||r.purpose!=="production"||r.nonce!==a.nonce||r.manifestDigest!==a.manifestSha256||r.commit!==a.commit||r.smoke?.complete!==true||ledger.schemaVersion!==2||ledger.purpose!=="steam-top-host-deployment-ledger"||ledger.deploymentId!==a.deploymentId||ledger.manifestSha256!==a.manifestSha256||ledger.nonce!==a.nonce||ledger.previousState!==a.expectedPreviousState||protectedState!==a.expectedPreviousState)process.exit(1);fs.writeFileSync(process.argv[6],JSON.stringify({schemaVersion:4,purpose:"production",generationSequence:(head?.sequence??0)+1,previousGenerationDigest:head?.digest??null,deploymentId:a.deploymentId,manifestSha256:a.manifestSha256,commit:a.commit,nonce:a.nonce,expectedPreviousState:a.expectedPreviousState,hostLedgerReceiptSha256:ledger.receiptSha256,smoke:{complete:true},activatedAt:new Date().toISOString()})+"\n",{mode:0o400});
NODE
chmod 400 "$tmp";ssh-keygen -Y sign -q -f "$state_key" -n steam-top-protected-deployment-state "$tmp";chmod 400 "$tmp.sig";sequence=$(node -p 'String(require(process.argv[1]).generationSequence).padStart(20,"0")' "$tmp");digest=$(sha256sum "$tmp"|awk '{print $1}');final="$generations/$sequence-$digest";sync -f "$tmp" "$tmp.sig" "$generation";mv "$generation" "$final";chmod 500 "$final";ln -sfn "generations/$(basename "$final")" "$state_dir/current.next";mv -Tf "$state_dir/current.next" "$state_dir/current";activation_generation=$(mktemp -d "$activations/.generation.XXXXXX");activation="$activation_generation/payload.json";node - "$activation" "$deployment_id" "$nonce" "$digest" "$final/payload.json" <<'NODE'
const fs=require("fs"),[path,id,nonce,stateDigest,state]=process.argv.slice(2);fs.writeFileSync(path,JSON.stringify({schemaVersion:1,purpose:"production-activation-receipt",deploymentId:id,nonce,stateDigest,activatedAt:require(state).activatedAt})+"\n",{flag:"wx",mode:0o400});
NODE
ssh-keygen -Y sign -q -f "$state_key" -n steam-top-production-activation "$activation";chmod 400 "$activation" "$activation.sig";activation_digest=$(sha256sum "$activation"|awk '{print $1}');activation_final="$activations/$activation_digest";mv "$activation_generation" "$activation_final";chmod 500 "$activation_final";ln -s "$(basename "$activation_final")" "$activations/current.next";mv -Tf "$activations/current.next" "$activations/current";activation="$activation_final/payload.json";sync -f "$state_dir";emit_activation
