#!/usr/bin/env bash
set -euo pipefail
[[ $(id -u) -eq 0 && $# -eq 1 ]]||exit 2;/opt/steam-top-bootstrap/verify-bootstrap.sh;bundle=$1;config=/etc/steam-top-bootstrap/trust.json;[[ -f $bundle && ! -L $bundle ]]||exit 1
mapfile -t values < <(node - "$config" "$bundle" <<'NODE'
const c=require(process.argv[2]),a=require(process.argv[3]),paths=["githubTokenFile","hostReceiptOutbox","hostReceiptAllowedSigners","productionStateDir","productionStateSigningKey"];for(const k of paths)if(typeof c[k]!=="string"||!c[k].startsWith("/"))process.exit(1);if(!/^[A-Za-z0-9@._-]+$/.test(c.hostReceiptSignerId)||a.schemaVersion!==1||a.purpose!=="production-deployment-authorization"||a.repository!==c.repository)process.exit(1);for(const k of ["repository","githubTokenFile","hostReceiptOutbox","hostReceiptAllowedSigners","hostReceiptSignerId","productionStateDir","productionStateSigningKey"])console.log(c[k]);console.log(a.deploymentId);console.log(a.nonce);
NODE
);repository=${values[0]};token=${values[1]};outbox=${values[2]};allowed=${values[3]};signer=${values[4]};state_dir=${values[5]};state_key=${values[6]};deployment_id=${values[7]};nonce=${values[8]};receipt="$outbox/$nonce.json";receipt_sig="$receipt.sig";ledger_root="$outbox/deployment-ledger";tmpdir=$(mktemp -d);trap 'rm -rf "$tmpdir"' EXIT
for file in "$token" "$allowed" "$state_key" "$receipt" "$receipt_sig";do [[ -f $file && ! -L $file ]]||exit 1;done;ssh-keygen -Y verify -q -f "$allowed" -I "$signer" -n steam-top-production-deployment -s "$receipt_sig" <"$receipt"||exit 1
runtime=$(realpath /opt/steam-top/current);node "$runtime/scripts/inspect-signed-generation-chain.mjs" "$ledger_root" steam-top-host-deployment-ledger >"$tmpdir/ledger.json";while IFS=$'\t' read -r payload signature;do ssh-keygen -Y verify -q -f "$allowed" -I "$signer" -n steam-top-host-deployment-ledger -s "$signature" <"$payload"||exit 1;done < <(node -e 'for(const x of require(process.argv[1]).generations)console.log(`${x.payloadPath}\t${x.signaturePath}`)' "$tmpdir/ledger.json");ledger=$(node -e 'const h=require(process.argv[1]).head;if(!h)process.exit(1);process.stdout.write(h.payloadPath)' "$tmpdir/ledger.json")
GH_TOKEN=$(<"$token");export GH_TOKEN;latest=$(gh api "repos/$repository/deployments?environment=production&per_page=1" --jq '.[0].id|tostring');[[ $latest == "$deployment_id" ]]||exit 1;status=$(gh api "repos/$repository/deployments/$deployment_id/statuses?per_page=1" --jq '.[0].state');[[ $status == success ]]||exit 1
install -d -o root -g root -m 0700 "$state_dir";tmp=$(mktemp "$state_dir/.production-state.XXXXXX");node - "$bundle" "$receipt" "$ledger" "$tmp" <<'NODE'
const fs=require("fs"),a=require(process.argv[2]),r=require(process.argv[3]),ledger=require(process.argv[4]);if(r.schemaVersion!==4||r.purpose!=="production"||r.nonce!==a.nonce||r.manifestDigest!==a.manifestSha256||r.commit!==a.commit||r.smoke?.complete!==true||ledger.schemaVersion!==1||ledger.purpose!=="steam-top-host-deployment-ledger"||ledger.deploymentId!==a.deploymentId||ledger.manifestSha256!==a.manifestSha256||ledger.nonce!==a.nonce||ledger.previousState!==a.expectedPreviousState)process.exit(1);fs.writeFileSync(process.argv[5],JSON.stringify({schemaVersion:4,purpose:"production",deploymentId:a.deploymentId,manifestSha256:a.manifestSha256,commit:a.commit,nonce:a.nonce,expectedPreviousState:a.expectedPreviousState,hostLedgerReceiptSha256:ledger.receiptSha256,smoke:{complete:true},activatedAt:new Date().toISOString()})+"\n",{mode:0o400});
NODE
chmod 400 "$tmp";ssh-keygen -Y sign -q -f "$state_key" -n steam-top-protected-deployment-state "$tmp";chmod 400 "$tmp.sig";mv "$tmp" "$state_dir/current.json";mv "$tmp.sig" "$state_dir/current.json.sig"
