#!/usr/bin/env bash
set -euo pipefail
source /opt/steam-top-bootstrap/key-custody-guard.sh
[[ $(id -u) -eq 0 && ( $# -eq 4 || $# -eq 5 ) && $1 =~ ^[a-f0-9]{64}$ ]]||exit 2
nonce=$1;shift;tmp=$(mktemp -d);trap 'rm -rf "$tmp"' EXIT;purpose=$(node -p 'const x=require("/etc/steam-top-bootstrap/trust.json").deploymentPurpose??"production";if(!["production","release-integration"].includes(x))process.exit(1);x');lock=/var/lock/steam-top-production.lock;[[ $purpose == release-integration ]]&&lock=/var/lock/steam-top-release-integration.lock;[[ -f $lock && ! -L $lock ]]||exit 1;read -r owner mode < <(stat -c '%u %a' "$lock");[[ $owner == 0 && $mode == 600 ]]||exit 1;exec 9<>"$lock";flock -n 9||exit 75
/opt/steam-top-bootstrap/resolve-production-state.sh "$nonce" >"$tmp/frame";runtime=$(awk '/^STATE-BEGIN /{print $5;exit}' "$tmp/frame")
[[ $runtime == /opt/steam-top/releases/* && -d $runtime && ! -L $runtime ]]||exit 1
awk -v a="$tmp/state.b64" -v b="$tmp/state.sig.b64" -v c="$tmp/activation.b64" -v d="$tmp/activation.sig.b64" '/^STATE-SIGNATURE$/{out=b;next}/^ACTIVATION-RECEIPT$/{out=c;next}/^ACTIVATION-SIGNATURE$/{out=d;next}/^STATE-END /{out="";next}/^STATE-BEGIN /{out=a;next}out!=""{print >out}' "$tmp/frame";for name in state state.sig activation activation.sig;do base64 -d <"$tmp/$name.b64" >"$tmp/$name";chmod 0400 "$tmp/$name";done
"$runtime/scripts/verify-runtime-install.sh" "$runtime"||die "runtime seal"
promotion_nonce=$(node -p 'const x=require(process.argv[1]).promotionNonce;if(!/^[a-f0-9]{64}$/.test(x))process.exit(1);x' "$1");incident=$(node -p 'const x=require("/etc/steam-top-bootstrap/trust.json").cutoverIncidentDir;if(typeof x!=="string"||!x.startsWith("/"))process.exit(1);x');output_dir="$incident/confirmed/$promotion_nonce";install -d -o root -g root -m 0700 "$incident/confirmed" "$output_dir";final="$output_dir/final.json"
env CANONICAL_STATE_RESOLVED=true CANONICAL_DEPLOYMENT_PURPOSE="$purpose" PROMOTE_STATE_DIR="$output_dir" PROTECTED_DEPLOYMENT_STATE_FILE="$tmp/state" PROTECTED_DEPLOYMENT_STATE_SIGNATURE="$tmp/state.sig" ACTIVATION_RECEIPT_FILE="$tmp/activation" ACTIVATION_RECEIPT_SIGNATURE="$tmp/activation.sig" "$runtime/infra/backup/confirm-cutover.sh" "$@" "$final";/opt/steam-top-bootstrap/resolve-production-state.sh "$nonce" >"$tmp/after";cmp -s "$tmp/frame" "$tmp/after"
