#!/usr/bin/env bash
set -euo pipefail
[[ $(id -u) -eq 0 ]]||{ echo "bootstrap deploy requires root" >&2;exit 1;};prepared_argument=;if [[ ${1:-} == --prepared-authorization ]];then [[ $# -eq 10 ]]||exit 2;prepared_argument=$2;shift 2;else [[ $# -eq 8 ]]||exit 2;fi
/opt/steam-top-bootstrap/verify-bootstrap.sh;artifact=$1;bundle=$2;pending=$3;manifest=$4;repository=$5;commit=$6;nonce=$7;expected_and_id=$8;expected=${expected_and_id%|*};deployment_id=${expected_and_id##*|};config=/etc/steam-top-bootstrap/trust.json
mapfile -t paths < <(node - "$config" <<'NODE'
const x=require(process.argv[2]),paths=["githubTokenFile","authorizationDir","productionEnvFile","hostReceiptSigningKey","adminSmokeSecretFile","hostReceiptOutbox","pgServiceFile","pgPassFile","ledgerSigningKey","hostReceiptAllowedSigners","ledgerAllowedSigners"];for(const k of paths)if(typeof x[k]!=="string"||!x[k].startsWith("/"))process.exit(1);for(const k of ["pgServiceName","hostReceiptSignerId","ledgerSignerId"])if(!/^[A-Za-z0-9@._-]+$/.test(x[k]))process.exit(1);for(const k of paths)console.log(x[k]);console.log(x.pgServiceName);console.log(x.hostReceiptSignerId);console.log(x.ledgerSignerId);
NODE
)
prepared="${paths[1]}/$nonce.json";if [[ -n $prepared_argument ]];then [[ $prepared_argument == "$prepared" && -f $prepared && ! -L $prepared && -d ${paths[1]} && ! -L ${paths[1]} ]]||exit 1;read -r po pm < <(stat -c '%u %a' "$prepared");read -r do dm < <(stat -c '%u %a' "${paths[1]}");[[ $po == 0 && $pm == 400 && $do == 0 && $dm == 700 ]]||exit 1;bundle_sha=$(sha256sum "$bundle"|awk '{print $1}');node - "$prepared" "$deployment_id" "$nonce" "$manifest" "$bundle_sha" "$repository" "$commit" "$expected" <<'NODE'
const a=require(process.argv[2]);if(a.state!=="pending"||a.deploymentId!==process.argv[3]||a.nonce!==process.argv[4]||a.manifestSha256!==process.argv[5]||a.authorizationBundleSha256!==process.argv[6]||a.repository!==process.argv[7]||a.commit!==process.argv[8]||a.expectedPreviousState!==process.argv[9]||!/^[a-f0-9]{64}$/.test(a.runtimeManifestSha256))process.exit(1);
NODE
else /opt/steam-top-bootstrap/prepare-release.sh "$artifact" "$bundle" "$pending" "${paths[0]}" "${paths[1]}";fi
read -r runtime_sha deployment_purpose < <(node -e 'const a=require(process.argv[1]);if(!/^[a-f0-9]{64}$/.test(a.runtimeManifestSha256)||!["production","release-integration"].includes(a.deploymentPurpose))process.exit(1);console.log(a.runtimeManifestSha256,a.deploymentPurpose)' "$bundle");core="/opt/steam-top/releases/$runtime_sha/scripts/host-deploy-and-receipt.sh"
exec env HOST_RECEIPT_SIGNING_KEY="${paths[3]}" LEDGER_SIGNING_KEY="${paths[8]}" HOST_RECEIPT_ALLOWED_SIGNERS_FILE="${paths[9]}" LEDGER_ALLOWED_SIGNERS_FILE="${paths[10]}" HOST_RECEIPT_SIGNER_ID="${paths[12]}" LEDGER_SIGNER_ID="${paths[13]}" PRODUCTION_AUTHORIZATION_DIR="${paths[1]}" DEPLOYMENT_AUTHORIZATION_PURPOSE="$deployment_purpose" ADMIN_SMOKE_SECRET_FILE="${paths[4]}" HOST_RECEIPT_OUTBOX_DIR="${paths[5]}" PGSERVICEFILE="${paths[6]}" PGPASSFILE="${paths[7]}" HOST_RECEIPT_PGSERVICE="${paths[11]}" "$core" "$artifact" "${paths[2]}" "$manifest" "$repository" "$commit" "$nonce" "$expected" "$deployment_id"
