#!/usr/bin/env bash
set -euo pipefail
source /opt/steam-top-bootstrap/key-custody-guard.sh
[[ $(id -u) -eq 0 && $# -eq 1 && $1 =~ ^[a-f0-9]{64}$ ]]||exit 2
/opt/steam-top-bootstrap/verify-bootstrap.sh;nonce=$1;config=/etc/steam-top-bootstrap/trust.json
mapfile -t values < <(node - "$config" <<'NODE'
const x=require(process.argv[2]);for(const k of ["productionStateDir","productionStateAllowedSigners"])if(typeof x[k]!=="string"||!x[k].startsWith("/"))process.exit(1);console.log(x.productionStateDir);console.log(x.productionStateAllowedSigners);
NODE
);root=${values[0]};allowed=${values[1]};[[ -d $root && ! -L $root && -L $root/current && -f $allowed && ! -L $allowed ]]||exit 1;inspection=$(mktemp);trap 'rm -f "$inspection"' EXIT;node /opt/steam-top-bootstrap/inspect-generation-chain.mjs "$root/generations" production >"$inspection";generation=$(realpath "$root/current");head=$(node -p 'require(process.argv[1]).head.payloadPath' "$inspection");[[ $generation == "$(dirname "$head")" ]]||exit 1
state="$generation/payload.json";state_sig="$state.sig";activation_root="$root/activations/$nonce";[[ -d $activation_root && ! -L $activation_root && -L $activation_root/current ]]||exit 1;activation_generation=$(realpath "$activation_root/current");[[ $activation_generation == "$activation_root/"* && -d $activation_generation && ! -L $activation_generation ]]||exit 1;activation="$activation_generation/payload.json";activation_sig="$activation.sig";read -r ao am < <(stat -c '%u %a' "$activation_root");read -r go gm < <(stat -c '%u %a' "$activation_generation");[[ $ao == 0 && $am == 700 && $go == 0 && $gm == 500 ]]||exit 1
for file in "$state" "$state_sig" "$activation" "$activation_sig";do [[ -f $file && ! -L $file ]]||exit 1;read -r fo fm < <(stat -c '%u %a' "$file");[[ $fo == 0 && $fm == 400 ]]||exit 1;done;read -r ao am < <(stat -c '%u %a' "$allowed");[[ $ao == 0 && $am == 444 ]]||exit 1;[[ $(basename "$activation_generation") == "$(sha256sum "$activation"|awk '{print $1}')" ]]||exit 1;while IFS=$'\t' read -r payload signature;do key_id=$(node -p 'const x=require(process.argv[1]).signerKeyId;if(!/^[A-Za-z0-9@._-]+$/.test(x))process.exit(1);x' "$payload");ssh-keygen -Y verify -q -f "$allowed" -I "$key_id" -n steam-top-protected-deployment-state -s "$signature" <"$payload";done < <(node -e 'for(const g of require(process.argv[1]).generations)console.log(`${g.payloadPath}\t${g.signaturePath}`)' "$inspection");activation_key_id=$(node -p 'const x=require(process.argv[1]).signerKeyId;if(!/^[A-Za-z0-9@._-]+$/.test(x))process.exit(1);x' "$activation");ssh-keygen -Y verify -q -f "$allowed" -I "$activation_key_id" -n steam-top-production-activation -s "$activation_sig" <"$activation"
node - "$state" "$activation" "$nonce" <<'NODE'
const fs=require("fs"),crypto=require("crypto"),s=require(process.argv[2]),a=require(process.argv[3]),nonce=process.argv[4],digest=crypto.createHash("sha256").update(fs.readFileSync(process.argv[2])).digest("hex");if(s.schemaVersion!==4||s.purpose!=="production"||s.nonce!==nonce||!/^[a-f0-9]{64}$/.test(s.runtimeManifestSha256)||s.runtimeReleasePath!==`/opt/steam-top/releases/${s.runtimeManifestSha256}`||a.schemaVersion!==1||a.purpose!=="production-activation-receipt"||a.nonce!==nonce||a.deploymentId!==s.deploymentId||a.stateDigest!==digest||a.activatedAt!==s.activatedAt)process.exit(1);
NODE
runtime=$(node -p 'require(process.argv[1]).runtimeReleasePath' "$state");[[ -d $runtime && ! -L $runtime && $(realpath /opt/steam-top/current) == "$runtime" ]]||exit 1;runtime_sha=$(basename "$runtime");RUNTIME_INSTALL_MANIFEST_SHA256=$runtime_sha "$runtime/scripts/verify-runtime-install.sh" "$runtime"||exit 1
printf 'STATE-BEGIN %s %s %s %s\n' "$nonce" "$(basename "$generation")" "$(basename "$activation_generation")" "$runtime";base64 <"$state";printf 'STATE-SIGNATURE\n';base64 <"$state_sig";printf 'ACTIVATION-RECEIPT\n';base64 <"$activation";printf 'ACTIVATION-SIGNATURE\n';base64 <"$activation_sig";printf 'STATE-END %s\n' "$nonce"
