#!/usr/bin/env bash
set -euo pipefail
umask 077
die(){ echo "backup failed: $1" >&2;exit 1;}
script_dir=$(CDPATH= cd -- "$(dirname -- "$0")"&&pwd -P)
for name in PGSERVICE PGSERVICEFILE PGPASSFILE BACKUP_DIR AGE_RECIPIENT DELETION_LEDGER_FILE BACKUP_SIGNING_KEY BACKUP_SIGNER_ID BACKUP_ALLOWED_SIGNERS_FILE;do [[ -n ${!name:-} ]]||die "$name is required";done
[[ -z ${DATABASE_URL:-} ]]||die "DATABASE_URL is forbidden; use libpq PGSERVICE/PGPASSFILE"
[[ $PGSERVICE =~ ^[A-Za-z0-9_.-]{1,64}$ && $AGE_RECIPIENT =~ ^age1[0-9a-z]+$ && $BACKUP_SIGNER_ID =~ ^[A-Za-z0-9._@-]{1,128}$ ]]||die "service, recipient or signer is invalid"
while IFS='=' read -r name _;do case "$name" in PGSERVICE|PGSERVICEFILE|PGPASSFILE) :;; PG*)die "libpq override $name is forbidden";;esac;done < <(env)
for command_name in pg_dump age psql ssh-keygen node;do command -v "$command_name" >/dev/null 2>&1||die "$command_name is required";done
secure_file(){ local value=$1 mode uid;[[ -f $value && ! -L $value ]]||die "private key/ledger must be a regular file";if stat -c '%a %u' "$value" >/dev/null 2>&1;then read -r mode uid < <(stat -c '%a %u' "$value");else read -r mode uid < <(stat -f '%Lp %u' "$value");fi;[[ $uid == "$(id -u)" && $((8#$mode & 077)) -eq 0 ]]||die "private file owner/mode is unsafe";}
secure_file "$BACKUP_SIGNING_KEY";secure_file "$DELETION_LEDGER_FILE";secure_file "$PGSERVICEFILE";secure_file "$PGPASSFILE";secure_file "$BACKUP_ALLOWED_SIGNERS_FILE"
DELETION_LEDGER_CLI="$script_dir/../../apps/server/dist/admin/deletion-ledger-cli.js";cli_manifest="$script_dir/trusted-ledger-cli.sha256";if [[ ${APP_ENV:-} == test && ${ALLOW_TEST_LEDGER_CLI_INJECTION:-} == yes ]];then DELETION_LEDGER_CLI=${TEST_DELETION_LEDGER_CLI:?};cli_manifest=${TEST_DELETION_LEDGER_CLI_MANIFEST:?};fi
[[ -f $DELETION_LEDGER_CLI && ! -L $DELETION_LEDGER_CLI && -O $DELETION_LEDGER_CLI && -f $cli_manifest && ! -L $cli_manifest && -O $cli_manifest ]]||die "ledger CLI trust files are unsafe"
if stat -c '%a' "$DELETION_LEDGER_CLI" >/dev/null 2>&1;then cli_mode=$(stat -c '%a' "$DELETION_LEDGER_CLI");manifest_mode=$(stat -c '%a' "$cli_manifest");else cli_mode=$(stat -f '%Lp' "$DELETION_LEDGER_CLI");manifest_mode=$(stat -f '%Lp' "$cli_manifest");fi;[[ $((8#$cli_mode&022)) -eq 0 && $((8#$manifest_mode&022)) -eq 0 ]]||die "ledger CLI trust files are writable by group/world"
read -r trusted_cli_sha trusted_cli_name extra <"$cli_manifest";[[ -z ${extra:-} && $trusted_cli_name == deletion-ledger-cli.js && $trusted_cli_sha =~ ^[a-f0-9]{64}$ ]]||die "ledger CLI trust manifest invalid";if command -v sha256sum >/dev/null 2>&1;then cli_sha=$(sha256sum "$DELETION_LEDGER_CLI"|awk '{print $1}');else cli_sha=$(shasum -a 256 "$DELETION_LEDGER_CLI"|awk '{print $1}');fi;[[ $cli_sha == "$trusted_cli_sha" ]]||die "ledger CLI digest mismatch"
mkdir -p "$BACKUP_DIR";chmod 700 "$BACKUP_DIR";[[ -d $BACKUP_DIR && ! -L $BACKUP_DIR ]]||die "BACKUP_DIR is unsafe";backup_dir=$(CDPATH= cd -- "$BACKUP_DIR"&&pwd -P)
timestamp=$(date -u +%Y%m%dT%H%M%SZ);serial=$(printf '%06d' "$((($$+RANDOM)%1000000))");set_name="steam-top-${timestamp}-${serial}.backup";[[ $set_name =~ ^steam-top-[0-9]{8}T[0-9]{6}Z-[0-9]{6}\.backup$ ]]||die "unsafe set name"
backup_id=$(node -e 'console.log(require("crypto").randomUUID())')
staging=$(mktemp -d "$backup_dir/.staging-XXXXXX");chmod 700 "$staging";final="$backup_dir/$set_name";[[ ! -e $final ]]||die "backup collision"
snapshot_meta="$staging/.snapshot";keeper_pid=""
cleanup(){ if [[ -n $keeper_pid ]];then kill "$keeper_pid" >/dev/null 2>&1||true;wait "$keeper_pid" >/dev/null 2>&1||true;fi;[[ -n ${staging:-} && -d $staging && ! -L $staging ]]&&rm -rf "$staging";};trap cleanup EXIT;trap 'cleanup;exit 130' INT TERM
ledger_metadata=$(node "$DELETION_LEDGER_CLI" snapshot "$DELETION_LEDGER_FILE" "$staging/deletion-ledger.log")
ledger_lines=$(wc -l <"$staging/deletion-ledger.log"|tr -d ' ');if command -v sha256sum >/dev/null 2>&1;then ledger_sha256=$(sha256sum "$staging/deletion-ledger.log"|awk '{print $1}');else ledger_sha256=$(shasum -a 256 "$staging/deletion-ledger.log"|awk '{print $1}');fi
[[ $ledger_metadata == *\"lines\":$ledger_lines* && $ledger_metadata == *\"sha256\":\"$ledger_sha256\"* ]]||die "ledger snapshot metadata mismatch"
psql -X -q -v ON_ERROR_STOP=1 -At -o "$snapshot_meta" -c 'begin isolation level repeatable read read only' -c 'select pg_export_snapshot()' -c 'select current_database()' -c 'select current_schema()' -c 'select count(*) from deletion_audit' -c 'do $keeper$ begin loop perform pg_sleep(60); end loop; end $keeper$' &
keeper_pid=$!;for _ in {1..100};do [[ $(wc -l <"$snapshot_meta") -ge 4 ]]&&break;sleep 0.1;done;[[ $(wc -l <"$snapshot_meta") -ge 4 ]]||die "snapshot keeper failed"
snapshot_id=$(sed -n '1p' "$snapshot_meta");source_database=$(sed -n '2p' "$snapshot_meta");source_schema=$(sed -n '3p' "$snapshot_meta");verification_rows=$(sed -n '4p' "$snapshot_meta");[[ $snapshot_id =~ ^[0-9]+-[0-9A-F]+-[0-9]+$ && $source_database =~ ^[A-Za-z0-9_.-]{1,63}$ && $source_schema =~ ^[A-Za-z_][A-Za-z0-9_]{0,62}$ && $verification_rows =~ ^[0-9]+$ ]]||die "snapshot metadata invalid"
pg_dump --format=custom --snapshot="$snapshot_id" --exclude-schema='restore_control' --no-owner --no-privileges|age --encrypt --recipient "$AGE_RECIPIENT" --output "$staging/dump.age"
kill "$keeper_pid" >/dev/null 2>&1||true;wait "$keeper_pid" >/dev/null 2>&1||true;keeper_pid="";rm "$snapshot_meta"
[[ -s $staging/dump.age ]]||die "encrypted dump empty";if command -v sha256sum >/dev/null 2>&1;then checksum=$(sha256sum "$staging/dump.age"|awk '{print $1}');else checksum=$(shasum -a 256 "$staging/dump.age"|awk '{print $1}');fi
printf '%s  dump.age\n' "$checksum" >"$staging/checksum.sha256"
printf 'format=steam-top-age-pgdump-v4\nbackup_id=%s\nset_name=%s\ncreated_at=%s\nsource_database=%s\nsource_schema=%s\nverification_table=deletion_audit\nverification_rows=%s\nsha256=%s\ndeletion_ledger_lines=%s\ndeletion_ledger_sha256=%s\nsigner_id=%s\n' "$backup_id" "$set_name" "$timestamp" "$source_database" "$source_schema" "$verification_rows" "$checksum" "$ledger_lines" "$ledger_sha256" "$BACKUP_SIGNER_ID" >"$staging/manifest"
{ cat "$staging/manifest";cat "$staging/checksum.sha256";} >"$staging/SIGNED-METADATA";ssh-keygen -Y sign -q -f "$BACKUP_SIGNING_KEY" -n steam-top-backup "$staging/SIGNED-METADATA";mv "$staging/SIGNED-METADATA.sig" "$staging/signature"
for file in dump.age checksum.sha256 manifest SIGNED-METADATA signature deletion-ledger.log;do chmod 600 "$staging/$file";node -e 'const fs=require("fs");const fd=fs.openSync(process.argv[1],"r");fs.fsyncSync(fd);fs.closeSync(fd)' "$staging/$file";done
printf 'complete\n' >"$staging/COMPLETE";chmod 600 "$staging/COMPLETE";node -e 'const fs=require("fs");for(const p of process.argv.slice(1)){const fd=fs.openSync(p,"r");fs.fsyncSync(fd);fs.closeSync(fd)}' "$staging/COMPLETE" "$staging"
mv "$staging" "$final";staging="";node -e 'const fs=require("fs");const fd=fs.openSync(process.argv[1],"r");fs.fsyncSync(fd);fs.closeSync(fd)' "$backup_dir";trap - EXIT INT TERM
if command -v sha256sum >/dev/null 2>&1;then verified_digest=$(sha256sum "$final/manifest"|awk '{print $1}');verified_checksum=$(sha256sum "$final/checksum.sha256"|awk '{print $1}');else verified_digest=$(shasum -a 256 "$final/manifest"|awk '{print $1}');verified_checksum=$(shasum -a 256 "$final/checksum.sha256"|awk '{print $1}');fi;printf 'manifest_sha256=%s\nchecksum_file_sha256=%s\n' "$verified_digest" "$verified_checksum" >"$final/VERIFIED";ssh-keygen -Y sign -q -f "$BACKUP_SIGNING_KEY" -n steam-top-backup-verified "$final/VERIFIED";chmod 600 "$final/VERIFIED" "$final/VERIFIED.sig";node -e 'const fs=require("fs");for(const p of process.argv.slice(1)){const fd=fs.openSync(p,"r");fs.fsyncSync(fd);fs.closeSync(fd)}' "$final/VERIFIED" "$final/VERIFIED.sig" "$final" "$backup_dir"
sets=();seen_ids='|';seen_digests='|';while IFS= read -r candidate;do if "$script_dir/verify-retention-set.sh" "$candidate" "$BACKUP_ALLOWED_SIGNERS_FILE" "$BACKUP_SIGNER_ID" >/dev/null 2>&1;then candidate_id=$(sed -n 's/^backup_id=//p' "$candidate/manifest");candidate_digest=$(sed -n 's/^sha256=//p' "$candidate/manifest");if [[ $seen_ids != *"|$candidate_id|"* && $seen_digests != *"|$candidate_digest|"* ]];then sets+=("$candidate");seen_ids="${seen_ids}${candidate_id}|";seen_digests="${seen_digests}${candidate_digest}|";fi;fi;done < <(find "$backup_dir" -mindepth 1 -maxdepth 1 -type d -name 'steam-top-*.backup' -print|LC_ALL=C sort);excess=$((${#sets[@]}-30));if((excess>0));then for((i=0;i<excess;i++));do old=${sets[$i]};[[ ${old##*/} =~ ^steam-top-[0-9]{8}T[0-9]{6}Z-[0-9]{6}\.backup$ && -d $old && ! -L $old ]]&&rm -rf "$old";done;fi
echo "backup created: $set_name"
