#!/usr/bin/env bash
set -euo pipefail
die(){ echo "cutover finalization refused: $1" >&2;exit 1;}
[[ $(id -u) -eq 0 && $# -eq 3 ]]||die "root and ready/receipt/signature paths required"
[[ ${CANONICAL_STATE_RESOLVED:-} == true ]]||die "canonical bootstrap state resolver required"
ready=$1;cutover=$2;signature=$3;script_dir=$(CDPATH= cd -- "$(dirname -- "$0")"&&pwd -P);root=$(CDPATH= cd -- "$script_dir/../.."&&pwd -P);source "$script_dir/host-trust-guard.sh"
for name in PROMOTE_PGSERVICE PGSERVICEFILE PGPASSFILE CUTOVER_ALLOWED_SIGNERS_FILE CUTOVER_SIGNER_ID PRODUCTION_ENV_FILE PROTECTED_DEPLOYMENT_STATE_FILE PROTECTED_DEPLOYMENT_STATE_SIGNATURE PROTECTED_STATE_ALLOWED_SIGNERS_FILE PROTECTED_STATE_SIGNER_ID ACTIVATION_RECEIPT_FILE ACTIVATION_RECEIPT_SIGNATURE HOST_DEPLOYMENT_RECEIPT_FILE HOST_DEPLOYMENT_RECEIPT_SIGNATURE HOST_RECEIPT_ALLOWED_SIGNERS_FILE HOST_RECEIPT_SIGNER_ID;do [[ -n ${!name:-} ]]||die "$name required";done
[[ -n ${RUNTIME_INSTALL_MANIFEST_SHA256:-} ]]||die "RUNTIME_INSTALL_MANIFEST_SHA256 required";"$root/scripts/verify-runtime-install.sh" "$root"||die "runtime install trust"
backup_reject_libpq_overrides PROMOTE_PGSERVICE||die "libpq overrides";for private in "$PGSERVICEFILE" "$PGPASSFILE" "$CUTOVER_ALLOWED_SIGNERS_FILE" "$PRODUCTION_ENV_FILE" "$PROTECTED_DEPLOYMENT_STATE_FILE" "$PROTECTED_DEPLOYMENT_STATE_SIGNATURE" "$PROTECTED_STATE_ALLOWED_SIGNERS_FILE" "$ACTIVATION_RECEIPT_FILE" "$ACTIVATION_RECEIPT_SIGNATURE" "$HOST_DEPLOYMENT_RECEIPT_FILE" "$HOST_DEPLOYMENT_RECEIPT_SIGNATURE" "$HOST_RECEIPT_ALLOWED_SIGNERS_FILE";do backup_private_file "$private"||die "private file trust";done;backup_trusted_root_deployment "$root" "$script_dir" "$root/apps/server/dist/admin" "$root/scripts"||die "host trust"
for file in "$ready" "$ready.sha256" "$cutover" "$signature";do [[ $file == /* && -f $file && ! -L $file ]]||die "state files unsafe";backup_root_file_mode "$file" 400||die "state file mode";done
[[ $("$root/scripts/portable-sha256.sh" digest "$ready") == "$(<"$ready.sha256")" ]]||die "ready digest mismatch";ssh-keygen -Y verify -q -f "$CUTOVER_ALLOWED_SIGNERS_FILE" -I "$CUTOVER_SIGNER_ID" -n steam-top-cutover-preflight -s "$signature" <"$cutover"||die "cutover signature"
values=$(node -e 'const fs=require("fs"),crypto=require("crypto"),r=JSON.parse(fs.readFileSync(process.argv[1])),c=JSON.parse(fs.readFileSync(process.argv[2])),d=crypto.createHash("sha256").update(fs.readFileSync(process.argv[1])).digest("hex");if(r.schemaVersion!==2||c.schemaVersion!==2||c.purpose!=="production-cutover-preflight"||c.readySha256!==d||c.preflight!=="passed"||c.promotionNonce!==r.promotionNonce||c.systemIdentifier!==r.systemIdentifier||c.database!==r.database||c.appRole!==r.appRole||c.restoreTargetId!==r.restoreTargetId||c.ledgerRows!==r.ledgerRows)process.exit(1);console.log([r.systemIdentifier,r.database,r.appRole,r.restoreTargetId,r.ledgerRows,c.promotionNonce].join("|"))' "$ready" "$cutover")||die "bound cutover receipt"
IFS='|' read -r system_id database role target_id ledger_rows nonce <<EOF
$values
EOF
[[ $database =~ ^[a-z_][a-z0-9_]{0,62}$ && $role =~ ^[a-z_][a-z0-9_]{0,62}$ && $ledger_rows =~ ^[0-9]+$ && $nonce =~ ^[a-f0-9]{64}$ ]]||die "identity"
ssh-keygen -Y verify -q -f "$HOST_RECEIPT_ALLOWED_SIGNERS_FILE" -I "$HOST_RECEIPT_SIGNER_ID" -n steam-top-production-deployment -s "$HOST_DEPLOYMENT_RECEIPT_SIGNATURE" <"$HOST_DEPLOYMENT_RECEIPT_FILE"||die "host receipt signature"
ssh-keygen -Y verify -q -f "$PROTECTED_STATE_ALLOWED_SIGNERS_FILE" -I "$PROTECTED_STATE_SIGNER_ID" -n steam-top-protected-deployment-state -s "$PROTECTED_DEPLOYMENT_STATE_SIGNATURE" <"$PROTECTED_DEPLOYMENT_STATE_FILE"||die "bootstrap sealed production state"
ssh-keygen -Y verify -q -f "$PROTECTED_STATE_ALLOWED_SIGNERS_FILE" -I "$PROTECTED_STATE_SIGNER_ID" -n steam-top-production-activation -s "$ACTIVATION_RECEIPT_SIGNATURE" <"$ACTIVATION_RECEIPT_FILE"||die "activation receipt signature";node - "$PROTECTED_DEPLOYMENT_STATE_FILE" "$ACTIVATION_RECEIPT_FILE" <<'NODE'
const fs=require("fs"),crypto=require("crypto"),s=require(process.argv[2]),a=require(process.argv[3]),digest=crypto.createHash("sha256").update(fs.readFileSync(process.argv[2])).digest("hex");if(a.schemaVersion!==1||a.purpose!=="production-activation-receipt"||a.deploymentId!==s.deploymentId||a.nonce!==s.nonce||a.stateDigest!==digest||a.activatedAt!==s.activatedAt)process.exit(1);
NODE
canonical_env=$(mktemp);trap 'rm -f "$canonical_env"' EXIT;node "$root/scripts/production-env.mjs" "$PRODUCTION_ENV_FILE" "$canonical_env"
node - "$PROTECTED_DEPLOYMENT_STATE_FILE" "$HOST_DEPLOYMENT_RECEIPT_FILE" "$cutover" "$canonical_env" "${CANONICAL_DEPLOYMENT_PURPOSE:-production}" <<'NODE'
const fs=require("fs"),crypto=require("crypto"),state=JSON.parse(fs.readFileSync(process.argv[2])),host=JSON.parse(fs.readFileSync(process.argv[3])),cutover=JSON.parse(fs.readFileSync(process.argv[4])),env=Object.fromEntries(fs.readFileSync(process.argv[5],"utf8").trim().split("\n").map(x=>x.split(/=(.*)/s).slice(0,2))),purpose=process.argv[6],url=new URL(env.DATABASE_URL);url.username="";url.password="";url.searchParams.sort();const databaseUrlSha256=crypto.createHash("sha256").update(url.toString()).digest("hex");if(!["production","release-integration"].includes(purpose)||state.schemaVersion!==4||state.purpose!=="production"||(state.deploymentPurpose??"production")!==purpose||state.smoke?.complete!==true||host.schemaVersion!==4||host.purpose!==purpose||host.smoke?.complete!==true||state.manifestSha256!==cutover.deploymentManifestSha256||host.manifestDigest!==cutover.deploymentManifestSha256||state.nonce!==host.nonce||state.commit!==host.commit||host.publicOrigin!==cutover.publicOrigin||env.PUBLIC_ORIGIN!==cutover.publicOrigin||databaseUrlSha256!==cutover.databaseUrlSha256||host.database?.systemIdentifier!==cutover.systemIdentifier||host.database?.restoreTargetId!==cutover.restoreTargetId||host.database?.markerEnvironment!=="production"||host.database?.restoreAllowed!==false)process.exit(1);
NODE
export PGSERVICE=$PROMOTE_PGSERVICE
committed=f;if [[ $(psql -X -v ON_ERROR_STOP=1 -Atqc "select to_regclass('restore_control.finalize_outbox') is not null") == t ]];then committed=$(psql -X -v ON_ERROR_STOP=1 -v nonce="$nonce" -Atqc "select exists(select 1 from restore_control.finalize_outbox where nonce=:'nonce' and state in ('connect-granted-pending-smoke','verified'))");fi
if [[ $committed == t ]];then echo "cutover provisional grant already recorded";exit 0;fi
actual=$(psql -X -v ON_ERROR_STOP=1 -v target_id="$target_id" -v role="$role" -v expected_rows="$ledger_rows" -AtF '|' -c "select (select system_identifier from pg_control_system()),current_database(),exists(select 1 from restore_control.deployment_environment where singleton and environment='production' and not restore_allowed and restore_target_id=:'target_id'::uuid),has_database_privilege('public',current_database(),'connect'),has_database_privilege(:'role',current_database(),'connect'),(select count(*) from deletion_audit)=:'expected_rows'::bigint")
[[ $actual == "$system_id|$database|t|f|f|t" ]]||die "database marker, ledger, or ACL changed"
psql -X -v ON_ERROR_STOP=1 -v role="$role" -v target_id="$target_id" -v nonce="$nonce" -v ledger_rows="$ledger_rows" <<'SQL'
begin;
select pg_advisory_xact_lock(1937002751);
select case when exists(select 1 from restore_control.finalize_outbox where nonce=:'nonce' and state='preflight-recorded' and restore_target_id=:'target_id'::uuid and app_role=:'role' and ledger_rows=:'ledger_rows'::bigint) then 1 else 1/0 end;
select format('grant connect on database %I to %I',current_database(),:'role') \gexec
create table if not exists restore_control.promotion_audit(id bigserial primary key,restore_target_id uuid not null,app_role text not null,cutover_nonce text not null unique,ledger_rows bigint not null,finalized_at timestamptz);
insert into restore_control.promotion_audit(restore_target_id,app_role,cutover_nonce,ledger_rows) values (:'target_id'::uuid,:'role',:'nonce',:'ledger_rows'::bigint) on conflict(cutover_nonce) do nothing;
update restore_control.finalize_outbox set state='connect-granted-pending-smoke',deadline_at=clock_timestamp()+interval '5 minutes',lease_owner=current_user,lease_generation=lease_generation+1 where nonce=:'nonce' and state='preflight-recorded';
commit;
SQL
provisional="$cutover.provisional";if [[ ! -e $provisional ]];then node - "$cutover" "$provisional" <<'NODE'
const fs=require("fs"),p=require(process.argv[2]);fs.writeFileSync(process.argv[3],JSON.stringify({schemaVersion:1,purpose:"connect-granted-pending-smoke",promotionNonce:p.promotionNonce,restoreTargetId:p.restoreTargetId,systemIdentifier:p.systemIdentifier,createdAt:new Date().toISOString()},null,2)+"\n",{flag:"wx",mode:0o400});
NODE
fi;echo "cutover provisional connect granted; public smoke confirmation required"
