#!/usr/bin/env bash
set -euo pipefail
die(){ echo "cutover receipt refused: $1" >&2;exit 1;}
[[ $(id -u) -eq 0 && $# -eq 2 ]]||die "root and ready/receipt paths required"
[[ ${CANONICAL_STATE_RESOLVED:-} == true ]]||die "canonical bootstrap state resolver required"
ready=$1;receipt=$2;script_dir=$(CDPATH= cd -- "$(dirname -- "$0")"&&pwd -P);root=$(CDPATH= cd -- "$script_dir/../.."&&pwd -P);source "$script_dir/host-trust-guard.sh"
for name in CUTOVER_DATABASE_URL_FILE PUBLIC_ORIGIN DEPLOYMENT_MANIFEST_SHA256 CUTOVER_SIGNING_KEY CUTOVER_ALLOWED_SIGNERS_FILE CUTOVER_SIGNER_ID PROMOTE_PGSERVICE PGSERVICEFILE PGPASSFILE PRODUCTION_ENV_FILE PROTECTED_DEPLOYMENT_STATE_FILE PROTECTED_DEPLOYMENT_STATE_SIGNATURE PROTECTED_STATE_ALLOWED_SIGNERS_FILE PROTECTED_STATE_SIGNER_ID ACTIVATION_RECEIPT_FILE ACTIVATION_RECEIPT_SIGNATURE HOST_DEPLOYMENT_RECEIPT_FILE HOST_DEPLOYMENT_RECEIPT_SIGNATURE HOST_RECEIPT_ALLOWED_SIGNERS_FILE HOST_RECEIPT_SIGNER_ID;do [[ -n ${!name:-} ]]||die "$name required";done
backup_trusted_root_deployment "$root" "$script_dir" "$root/scripts"||die "host trust";source "$root/scripts/key-custody-guard.sh";key_signer_matches_allowed "$CUTOVER_SIGNING_KEY" "$CUTOVER_ALLOWED_SIGNERS_FILE" "$CUTOVER_SIGNER_ID"||die "cutover signer mapping";for private in "$CUTOVER_DATABASE_URL_FILE" "$PGSERVICEFILE" "$PGPASSFILE" "$PRODUCTION_ENV_FILE" "$PROTECTED_DEPLOYMENT_STATE_FILE" "$PROTECTED_DEPLOYMENT_STATE_SIGNATURE" "$PROTECTED_STATE_ALLOWED_SIGNERS_FILE" "$ACTIVATION_RECEIPT_FILE" "$ACTIVATION_RECEIPT_SIGNATURE" "$HOST_DEPLOYMENT_RECEIPT_FILE" "$HOST_DEPLOYMENT_RECEIPT_SIGNATURE" "$HOST_RECEIPT_ALLOWED_SIGNERS_FILE";do backup_private_file "$private"||die "private file trust";done
ssh-keygen -Y verify -q -f "$PROTECTED_STATE_ALLOWED_SIGNERS_FILE" -I "$PROTECTED_STATE_SIGNER_ID" -n steam-top-protected-deployment-state -s "$PROTECTED_DEPLOYMENT_STATE_SIGNATURE" <"$PROTECTED_DEPLOYMENT_STATE_FILE"||die "protected generation signature";ssh-keygen -Y verify -q -f "$PROTECTED_STATE_ALLOWED_SIGNERS_FILE" -I "$PROTECTED_STATE_SIGNER_ID" -n steam-top-production-activation -s "$ACTIVATION_RECEIPT_SIGNATURE" <"$ACTIVATION_RECEIPT_FILE"||die "activation receipt signature";node - "$PROTECTED_DEPLOYMENT_STATE_FILE" "$ACTIVATION_RECEIPT_FILE" <<'NODE'
const crypto=require("crypto"),fs=require("fs"),state=require(process.argv[2]),activation=require(process.argv[3]),digest=crypto.createHash("sha256").update(fs.readFileSync(process.argv[2])).digest("hex");if(activation.schemaVersion!==1||activation.purpose!=="production-activation-receipt"||activation.deploymentId!==state.deploymentId||activation.nonce!==state.nonce||activation.stateDigest!==digest||activation.activatedAt!==state.activatedAt)process.exit(1);
NODE
ssh-keygen -Y verify -q -f "$HOST_RECEIPT_ALLOWED_SIGNERS_FILE" -I "$HOST_RECEIPT_SIGNER_ID" -n steam-top-production-deployment -s "$HOST_DEPLOYMENT_RECEIPT_SIGNATURE" <"$HOST_DEPLOYMENT_RECEIPT_FILE"||die "host receipt signature"
tmp=$(mktemp -d);trap 'rm -rf "$tmp"' EXIT;node "$root/scripts/production-env.mjs" "$PRODUCTION_ENV_FILE" "$tmp/env";canonical_origin=$(sed -n 's/^PUBLIC_ORIGIN=//p' "$tmp/env");[[ $canonical_origin == "$PUBLIC_ORIGIN" ]]||die "origin differs from canonical production env"
node - "$PROTECTED_DEPLOYMENT_STATE_FILE" "$HOST_DEPLOYMENT_RECEIPT_FILE" "$DEPLOYMENT_MANIFEST_SHA256" "$PUBLIC_ORIGIN" "$ready" "$tmp/env" "$CUTOVER_DATABASE_URL_FILE" "${CANONICAL_DEPLOYMENT_PURPOSE:-production}" <<'NODE'
const fs=require("fs"),crypto=require("crypto"),state=JSON.parse(fs.readFileSync(process.argv[2])),host=JSON.parse(fs.readFileSync(process.argv[3])),ready=JSON.parse(fs.readFileSync(process.argv[6])),env=Object.fromEntries(fs.readFileSync(process.argv[7],"utf8").trim().split("\n").map(x=>x.split(/=(.*)/s).slice(0,2))),purpose=process.argv[9];function identity(raw){const u=new URL(raw.trim());if(!/^postgres(?:ql)?:$/.test(u.protocol))process.exit(1);u.username="";u.password="";u.searchParams.sort();return crypto.createHash("sha256").update(u.toString()).digest("hex")}if(!["production","release-integration"].includes(purpose)||state.schemaVersion!==4||state.purpose!=="production"||(state.deploymentPurpose??"production")!==purpose||state.smoke?.complete!==true||host.schemaVersion!==4||host.purpose!==purpose||host.smoke?.complete!==true||state.manifestSha256!==process.argv[4]||host.manifestDigest!==process.argv[4]||host.publicOrigin!==process.argv[5]||env.PUBLIC_ORIGIN!==process.argv[5]||identity(env.DATABASE_URL)!==identity(fs.readFileSync(process.argv[8],"utf8"))||host.nonce!==state.nonce||host.commit!==state.commit||host.database?.markerEnvironment!=="production"||host.database?.restoreAllowed!==false||host.database?.restoreTargetId!==ready.restoreTargetId||host.database?.systemIdentifier!==ready.systemIdentifier)process.exit(1);
NODE
[[ $ready == /* && $receipt == /* && -f $ready && ! -L $ready && ( ! -e $receipt || -f $receipt ) && ! -L $receipt && ( ! -e $receipt.sig || -f $receipt.sig ) && ! -L $receipt.sig ]]||die "unsafe paths";backup_root_file_mode "$ready" 400||die "ready trust"
cutover_nonce=$(node -e 'const r=require(process.argv[1]);if(r.schemaVersion!==2||!/^[a-f0-9]{64}$/.test(r.promotionNonce))process.exit(1);process.stdout.write(r.promotionNonce)' "$ready")||die "promotion nonce"
probe="$receipt.probe.tmp";role=$(node -p 'require(process.argv[1]).appRole' "$ready");expected_rows=$(node -p 'require(process.argv[1]).ledgerRows' "$ready");actual=$(PGSERVICE=$PROMOTE_PGSERVICE psql -X -v ON_ERROR_STOP=1 -v nonce="$cutover_nonce" -v role="$role" -AtF '|' -c "select p.nonce,p.restore_target_id,p.system_identifier,p.created_at,(select environment='production' and not restore_allowed from restore_control.deployment_environment where singleton),(select count(*) from deletion_audit),(not has_database_privilege(:'role',current_database(),'connect')) from restore_control.deployment_probe p where p.nonce=:'nonce'");IFS='|' read -r probe_nonce probe_target probe_system probe_created marker ledger_rows app_revoked <<EOF
$actual
EOF
[[ $probe_nonce == "$cutover_nonce" && $marker == t && $app_revoked == t && $ledger_rows == "$expected_rows" ]]||die "maintenance preflight identity, marker, ledger, or ACL"
printf '{"nonce":"%s","restoreTargetId":"%s","systemIdentifier":"%s","createdAt":"%s"}\n' "$probe_nonce" "$probe_target" "$probe_system" "$probe_created" >"$probe";chmod 400 "$probe";expected="$receipt.expected.$$";node "$root/scripts/create-cutover-receipt.mjs" "$ready" "$CUTOVER_DATABASE_URL_FILE" "$PUBLIC_ORIGIN" "$DEPLOYMENT_MANIFEST_SHA256" "$cutover_nonce" "$probe" "$PRODUCTION_ENV_FILE" "$expected";rm -f "$probe"
if [[ -f $receipt ]];then cmp -s "$expected" "$receipt"||die "existing cutover receipt conflict";rm -f "$expected";backup_root_file_mode "$receipt" 400||die "existing receipt trust";else mv "$expected" "$receipt";chmod 400 "$receipt";fi
if [[ -f $receipt.sig ]];then backup_root_file_mode "$receipt.sig" 400||die "existing signature trust";ssh-keygen -Y verify -q -f "$CUTOVER_ALLOWED_SIGNERS_FILE" -I "$CUTOVER_SIGNER_ID" -n steam-top-cutover-preflight -s "$receipt.sig" <"$receipt"||die "existing receipt signature";else ssh-keygen -Y sign -q -f "$CUTOVER_SIGNING_KEY" -n steam-top-cutover-preflight "$receipt";chmod 400 "$receipt.sig";ssh-keygen -Y verify -q -f "$CUTOVER_ALLOWED_SIGNERS_FILE" -I "$CUTOVER_SIGNER_ID" -n steam-top-cutover-preflight -s "$receipt.sig" <"$receipt"||die "cutover post-sign verify";fi
PGSERVICE=$PROMOTE_PGSERVICE psql -X -v ON_ERROR_STOP=1 -v nonce="$cutover_nonce" -v target="$probe_target" -v role="$role" -v rows="$ledger_rows" -c "create table if not exists restore_control.finalize_outbox(nonce text primary key,restore_target_id uuid not null,app_role text not null,ledger_rows bigint not null,state text not null,created_at timestamptz not null default clock_timestamp());insert into restore_control.finalize_outbox values(:'nonce',:'target'::uuid,:'role',:'rows'::bigint,'preflight-recorded',clock_timestamp()) on conflict(nonce) do update set state='preflight-recorded' where restore_control.finalize_outbox.state='preflight-recorded'" >/dev/null
[[ $(PGSERVICE=$PROMOTE_PGSERVICE psql -X -Atqc "select state from restore_control.finalize_outbox where nonce='$cutover_nonce'") == preflight-recorded ]]||die "preflight outbox transition"
