#!/usr/bin/env bash
set -euo pipefail
die(){ echo "cutover receipt refused: $1" >&2;exit 1;}
[[ $(id -u) -eq 0 && $# -eq 2 ]]||die "root and ready/receipt paths required"
[[ ${CANONICAL_STATE_RESOLVED:-} == true ]]||die "canonical bootstrap state resolver required"
ready=$1;receipt=$2;script_dir=$(CDPATH= cd -- "$(dirname -- "$0")"&&pwd -P);root=$(CDPATH= cd -- "$script_dir/../.."&&pwd -P);source "$script_dir/host-trust-guard.sh"
for name in CUTOVER_DATABASE_URL_FILE PUBLIC_ORIGIN DEPLOYMENT_MANIFEST_SHA256 CUTOVER_SIGNING_KEY PROMOTE_PGSERVICE PGSERVICEFILE PGPASSFILE ADMIN_SMOKE_SECRET_FILE PRODUCTION_ENV_FILE PROTECTED_DEPLOYMENT_STATE_FILE PROTECTED_DEPLOYMENT_STATE_SIGNATURE PROTECTED_STATE_ALLOWED_SIGNERS_FILE PROTECTED_STATE_SIGNER_ID ACTIVATION_RECEIPT_FILE ACTIVATION_RECEIPT_SIGNATURE HOST_DEPLOYMENT_RECEIPT_FILE HOST_DEPLOYMENT_RECEIPT_SIGNATURE HOST_RECEIPT_ALLOWED_SIGNERS_FILE HOST_RECEIPT_SIGNER_ID;do [[ -n ${!name:-} ]]||die "$name required";done
backup_trusted_root_deployment "$root" "$script_dir" "$root/scripts"||die "host trust";for private in "$CUTOVER_SIGNING_KEY" "$CUTOVER_DATABASE_URL_FILE" "$PGSERVICEFILE" "$PGPASSFILE" "$ADMIN_SMOKE_SECRET_FILE" "$PRODUCTION_ENV_FILE" "$PROTECTED_DEPLOYMENT_STATE_FILE" "$PROTECTED_DEPLOYMENT_STATE_SIGNATURE" "$PROTECTED_STATE_ALLOWED_SIGNERS_FILE" "$ACTIVATION_RECEIPT_FILE" "$ACTIVATION_RECEIPT_SIGNATURE" "$HOST_DEPLOYMENT_RECEIPT_FILE" "$HOST_DEPLOYMENT_RECEIPT_SIGNATURE" "$HOST_RECEIPT_ALLOWED_SIGNERS_FILE";do backup_private_file "$private"||die "private file trust";done
ssh-keygen -Y verify -q -f "$PROTECTED_STATE_ALLOWED_SIGNERS_FILE" -I "$PROTECTED_STATE_SIGNER_ID" -n steam-top-protected-deployment-state -s "$PROTECTED_DEPLOYMENT_STATE_SIGNATURE" <"$PROTECTED_DEPLOYMENT_STATE_FILE"||die "protected generation signature";ssh-keygen -Y verify -q -f "$PROTECTED_STATE_ALLOWED_SIGNERS_FILE" -I "$PROTECTED_STATE_SIGNER_ID" -n steam-top-production-activation -s "$ACTIVATION_RECEIPT_SIGNATURE" <"$ACTIVATION_RECEIPT_FILE"||die "activation receipt signature";node - "$PROTECTED_DEPLOYMENT_STATE_FILE" "$ACTIVATION_RECEIPT_FILE" <<'NODE'
const crypto=require("crypto"),fs=require("fs"),state=require(process.argv[2]),activation=require(process.argv[3]),digest=crypto.createHash("sha256").update(fs.readFileSync(process.argv[2])).digest("hex");if(activation.schemaVersion!==1||activation.purpose!=="production-activation-receipt"||activation.deploymentId!==state.deploymentId||activation.nonce!==state.nonce||activation.stateDigest!==digest||activation.activatedAt!==state.activatedAt)process.exit(1);
NODE
ssh-keygen -Y verify -q -f "$HOST_RECEIPT_ALLOWED_SIGNERS_FILE" -I "$HOST_RECEIPT_SIGNER_ID" -n steam-top-production-deployment -s "$HOST_DEPLOYMENT_RECEIPT_SIGNATURE" <"$HOST_DEPLOYMENT_RECEIPT_FILE"||die "host receipt signature"
tmp=$(mktemp -d);trap 'rm -rf "$tmp"' EXIT;node "$root/scripts/production-env.mjs" "$PRODUCTION_ENV_FILE" "$tmp/env";canonical_origin=$(sed -n 's/^PUBLIC_ORIGIN=//p' "$tmp/env");[[ $canonical_origin == "$PUBLIC_ORIGIN" ]]||die "origin differs from canonical production env"
node - "$PROTECTED_DEPLOYMENT_STATE_FILE" "$HOST_DEPLOYMENT_RECEIPT_FILE" "$DEPLOYMENT_MANIFEST_SHA256" "$PUBLIC_ORIGIN" "$ready" "$tmp/env" "$CUTOVER_DATABASE_URL_FILE" <<'NODE'
const fs=require("fs"),crypto=require("crypto"),state=JSON.parse(fs.readFileSync(process.argv[2])),host=JSON.parse(fs.readFileSync(process.argv[3])),ready=JSON.parse(fs.readFileSync(process.argv[6])),env=Object.fromEntries(fs.readFileSync(process.argv[7],"utf8").trim().split("\n").map(x=>x.split(/=(.*)/s).slice(0,2)));function identity(raw){const u=new URL(raw.trim());if(!/^postgres(?:ql)?:$/.test(u.protocol))process.exit(1);u.username="";u.password="";u.searchParams.sort();return crypto.createHash("sha256").update(u.toString()).digest("hex")}if(state.schemaVersion!==4||state.purpose!=="production"||state.smoke?.complete!==true||host.schemaVersion!==4||host.purpose!=="production"||host.smoke?.complete!==true||state.manifestSha256!==process.argv[4]||host.manifestDigest!==process.argv[4]||host.publicOrigin!==process.argv[5]||env.PUBLIC_ORIGIN!==process.argv[5]||identity(env.DATABASE_URL)!==identity(fs.readFileSync(process.argv[8],"utf8"))||host.nonce!==state.nonce||host.commit!==state.commit||host.database?.markerEnvironment!=="production"||host.database?.restoreAllowed!==false||host.database?.restoreTargetId!==ready.restoreTargetId||host.database?.systemIdentifier!==ready.systemIdentifier)process.exit(1);
NODE
[[ $ready == /* && $receipt == /* && -f $ready && ! -L $ready && ( ! -e $receipt || -f $receipt ) && ! -L $receipt && ( ! -e $receipt.sig || -f $receipt.sig ) && ! -L $receipt.sig ]]||die "unsafe paths";backup_root_file_mode "$ready" 400||die "ready trust"
cutover_nonce=$(node -e 'const r=require(process.argv[1]);if(r.schemaVersion!==2||!/^[a-f0-9]{64}$/.test(r.promotionNonce))process.exit(1);process.stdout.write(r.promotionNonce)' "$ready")||die "promotion nonce"
probe="$receipt.probe.tmp";PGSERVICE=$PROMOTE_PGSERVICE psql -X -v ON_ERROR_STOP=1 -v nonce="$cutover_nonce" <<'SQL'
begin;select pg_advisory_xact_lock(1937002751);create table if not exists restore_control.deployment_probe(nonce text primary key,restore_target_id uuid not null,system_identifier text not null,created_at timestamptz not null default clock_timestamp(),consumed_at timestamptz);alter table restore_control.deployment_probe add column if not exists state text not null default 'pending';alter table restore_control.deployment_probe add column if not exists observed_at timestamptz;alter table restore_control.deployment_probe add column if not exists receipt_signed_at timestamptz;insert into restore_control.deployment_probe(nonce,restore_target_id,system_identifier,state)select :'nonce',restore_target_id,(select system_identifier::text from pg_control_system()),'pending' from restore_control.deployment_environment where singleton on conflict(nonce) do nothing;commit;
SQL
probe_state=$(PGSERVICE=$PROMOTE_PGSERVICE psql -X -v ON_ERROR_STOP=1 -v nonce="$cutover_nonce" -Atqc "select state from restore_control.deployment_probe where nonce=:'nonce'")
case $probe_state in pending) observed=false;;public-observed|receipt-signed) observed=true;;*) die "invalid deployment probe state";;esac
ADMIN_SMOKE_SECRET_FILE="$ADMIN_SMOKE_SECRET_FILE" PRODUCTION_SMOKE_PROBE_ALREADY_OBSERVED=$observed PRODUCTION_SMOKE_PROBE_OUTPUT="$probe" "$root/scripts/production-smoke.sh" "$PUBLIC_ORIGIN" "$cutover_nonce";if [[ ! -f $probe ]];then PGSERVICE=$PROMOTE_PGSERVICE psql -X -v ON_ERROR_STOP=1 -v nonce="$cutover_nonce" -AtF '|' -c "select nonce,restore_target_id,system_identifier,created_at from restore_control.deployment_probe where nonce=:'nonce' and state in ('public-observed','receipt-signed')"|node -e 'const fs=require("fs"),s=fs.readFileSync(0,"utf8").trim().split("|");if(s.length!==4)process.exit(1);fs.writeFileSync(process.argv[1],JSON.stringify({nonce:s[0],restoreTargetId:s[1],systemIdentifier:s[2],createdAt:new Date(s[3]).toISOString()})+"\n",{mode:0o400})' "$probe";fi;expected="$receipt.expected.$$";node "$root/scripts/create-cutover-receipt.mjs" "$ready" "$CUTOVER_DATABASE_URL_FILE" "$PUBLIC_ORIGIN" "$DEPLOYMENT_MANIFEST_SHA256" "$cutover_nonce" "$probe" "$expected";rm -f "$probe"
if [[ -f $receipt ]];then cmp -s "$expected" "$receipt"||die "existing cutover receipt conflict";rm -f "$expected";backup_root_file_mode "$receipt" 400||die "existing receipt trust";else mv "$expected" "$receipt";chmod 400 "$receipt";fi
allowed="$tmp/cutover-signers";printf 'cutover %s\n' "$(ssh-keygen -y -f "$CUTOVER_SIGNING_KEY")" >"$allowed";if [[ -f $receipt.sig ]];then backup_root_file_mode "$receipt.sig" 400||die "existing signature trust";ssh-keygen -Y verify -q -f "$allowed" -I cutover -n steam-top-cutover -s "$receipt.sig" <"$receipt"||die "existing receipt signature";else ssh-keygen -Y sign -q -f "$CUTOVER_SIGNING_KEY" -n steam-top-cutover "$receipt";chmod 400 "$receipt.sig";fi
PGSERVICE=$PROMOTE_PGSERVICE psql -X -v ON_ERROR_STOP=1 -v nonce="$cutover_nonce" -c "update restore_control.deployment_probe set state='receipt-signed',receipt_signed_at=coalesce(receipt_signed_at,clock_timestamp()) where nonce=:'nonce' and state in ('public-observed','receipt-signed')" >/dev/null
