#!/usr/bin/env bash
set -euo pipefail
: "${TEST_DATABASE_URL:?}";script_dir=$(CDPATH= cd -- "$(dirname -- "$0")"&&pwd -P);root=$(CDPATH= cd -- "$script_dir/../.."&&pwd -P);tmp=$(mktemp -d);app_uid=$(id -u);db="steam_top_promote_${RANDOM}_$$";app_role="steam_top_app_${RANDOM}_$$";base=${TEST_DATABASE_URL%/*};url="$base/$db";breaker=""
cleanup(){ [[ -z $breaker ]]||kill "$breaker" >/dev/null 2>&1||true;dropdb --if-exists --force --maintenance-db="$TEST_DATABASE_URL" "$db" >/dev/null 2>&1||true;psql "$TEST_DATABASE_URL" -v role="$app_role" -Atc "select format('drop role if exists %I',:'role')"|psql "$TEST_DATABASE_URL" >/dev/null 2>&1||true;sudo rm -rf "$tmp";};trap cleanup EXIT
createdb --maintenance-db="$TEST_DATABASE_URL" "$db";psql "$TEST_DATABASE_URL" -v ON_ERROR_STOP=1 -v role="$app_role" -Atc "select format('create role %I',:'role')"|psql "$TEST_DATABASE_URL" -v ON_ERROR_STOP=1;psql "$url" -v ON_ERROR_STOP=1 -f "$root/drizzle/0000_steam_top_pre_first_deploy.sql" >/dev/null;target=00000000-0000-4000-8000-000000000099;psql "$url" -v ON_ERROR_STOP=1 -c "begin;set local steam_top.configure_restore_target='RESTORE_NONPRODUCTION_DATA';update restore_control.deployment_environment set environment='test',restore_allowed=true,restore_target_id='$target' where singleton;commit;" >/dev/null
node - "$TEST_DATABASE_URL" "$db" "$tmp/service" "$tmp/pass" <<'NODE'
const fs=require('fs'),[raw,db,service,pass]=process.argv.slice(2),u=new URL(raw),host=u.hostname,port=u.port||'5432',user=decodeURIComponent(u.username),password=decodeURIComponent(u.password),common=`host=${host}\nport=${port}\nuser=${user}\n`;fs.writeFileSync(service,`[target]\n${common}dbname=${db}\n[maintenance]\n${common}dbname=postgres\n`,{mode:0o600});fs.writeFileSync(pass,`${host}:${port}:*:${user}:${password}\n`,{mode:0o600});
NODE
export PGSERVICEFILE="$tmp/service" PGPASSFILE="$tmp/pass";: >"$tmp/ledger";chmod 600 "$tmp/ledger";ssh-keygen -q -t ed25519 -N '' -f "$tmp/signing";signer=promotion@test;printf '%s %s\n' "$signer" "$(<"$tmp/signing.pub")" >"$tmp/signers";chmod 600 "$tmp/signing" "$tmp/signers";age-keygen -o "$tmp/age" 2>"$tmp/age.log";recipient=$(awk '/public key:/{print $4}' "$tmp/age.log")
PGSERVICE=target BACKUP_DIR="$tmp/backups" AGE_RECIPIENT="$recipient" DELETION_LEDGER_FILE="$tmp/ledger" BACKUP_SIGNING_KEY="$tmp/signing" BACKUP_SIGNER_ID="$signer" BACKUP_ALLOWED_SIGNERS_FILE="$tmp/signers" "$script_dir/backup.sh" >/dev/null;backup=$(find "$tmp/backups" -maxdepth 1 -type d -name 'steam-top-*.backup' -print -quit);mkdir "$tmp/state";sudo chown -R root:root "$tmp";sudo chown "$app_uid" "$tmp/ledger";sudo chmod 711 "$tmp";sudo chmod 700 "$tmp/state";sudo chmod 600 "$tmp/service" "$tmp/pass" "$tmp/ledger" "$tmp/signers"
promote_env=(APP_UID="$app_uid" PROMOTION_NONCE="$(printf 3%.0s {1..64})" PROMOTE_PGSERVICE=target PROMOTE_MAINTENANCE_PGSERVICE=maintenance PROMOTE_APP_ROLE="$app_role" PGSERVICEFILE="$tmp/service" PGPASSFILE="$tmp/pass" PROMOTE_CONFIRM_DATABASE="$db" RESTORE_ALLOWED_TARGET_ID="$target" DELETION_LEDGER_FILE="$tmp/ledger" BACKUP_ALLOWED_SIGNERS_FILE="$tmp/signers" BACKUP_SIGNER_ID="$signer" PROMOTE_CONFIRM=PROMOTE_VERIFIED_RESTORE_TO_PRODUCTION)
sudo env "${promote_env[@]}" PROMOTE_STATE_DIR="$tmp/state" "$script_dir/promote-restored-target.sh" "$backup";[[ $(stat -c '%u %a' "$tmp/ledger") == "$app_uid 600" ]]
[[ -f $tmp/state/promotion-ready ]];[[ $(psql "$url" -Atqc "select has_database_privilege('public',current_database(),'connect')||'|'||has_database_privilege('$app_role',current_database(),'connect')") == 'f|f' ]]
sudo cp "$tmp/state/promotion-ready" "$tmp/original-ready";sudo cp "$tmp/state/promotion-ready.sha256" "$tmp/original-ready.sha256";sudo ssh-keygen -q -t ed25519 -N '' -f "$tmp/cutover-signing";cutover_signer=cutover@test;sudo sh -c "printf '%s %s\n' '$cutover_signer' \"\$(cat '$tmp/cutover-signing.pub')\" >'$tmp/cutover-signers'";sudo chmod 600 "$tmp/cutover-signing" "$tmp/cutover-signers"
cutover="$tmp/state/cutover.json";cutover_nonce=$(printf 2%.0s {1..64});manifest_sha=$(printf 1%.0s {1..64});system_id=$(psql "$url" -Atqc "select system_identifier from pg_control_system()")
printf '%s\n' "$url"|sudo tee "$tmp/database-url" >/dev/null;printf '{"nonce":"%s","restoreTargetId":"%s","systemIdentifier":"%s"}\n' "$cutover_nonce" "$target" "$system_id"|sudo tee "$tmp/probe.json" >/dev/null;sudo chmod 600 "$tmp/database-url" "$tmp/probe.json"
sudo node "$root/scripts/create-cutover-receipt.mjs" "$tmp/state/promotion-ready" "$tmp/database-url" https://steam-top.test "$manifest_sha" "$cutover_nonce" "$tmp/probe.json" "$cutover";sudo ssh-keygen -Y sign -q -f "$tmp/cutover-signing" -n steam-top-cutover "$cutover";sudo chmod 400 "$cutover" "$cutover.sig"
finalize_env=(PROMOTE_PGSERVICE=target PGSERVICEFILE="$tmp/service" PGPASSFILE="$tmp/pass" CUTOVER_ALLOWED_SIGNERS_FILE="$tmp/cutover-signers" CUTOVER_SIGNER_ID="$cutover_signer")
sudo chmod 600 "$tmp/state/promotion-ready";sudo sh -c "printf tamper >>'$tmp/state/promotion-ready'";sudo chmod 400 "$tmp/state/promotion-ready";if sudo env "${finalize_env[@]}" "$script_dir/finalize-cutover.sh" "$tmp/state/promotion-ready" "$cutover" "$cutover.sig";then exit 1;fi;[[ $(psql "$url" -Atqc "select has_database_privilege('$app_role',current_database(),'connect')") == f ]]
sudo cp "$tmp/original-ready" "$tmp/state/promotion-ready";sudo cp "$tmp/original-ready.sha256" "$tmp/state/promotion-ready.sha256";sudo chmod 400 "$tmp/state/promotion-ready" "$tmp/state/promotion-ready.sha256";sudo env "${finalize_env[@]}" "$script_dir/finalize-cutover.sh" "$tmp/state/promotion-ready" "$cutover" "$cutover.sig";[[ $(psql "$url" -Atqc "select count(*) from restore_control.promotion_audit") == 1 ]];sudo "$script_dir/reconcile-finalize-outbox.sh" "$tmp/state/promotion-ready" "$cutover" "$cutover.sig" "$cutover_nonce";[[ $(psql "$url" -Atqc "select count(*) from restore_control.promotion_audit") == 1 ]]
sudo mkdir -m 700 "$tmp/state-marker";if sudo env "${promote_env[@]}" PROMOTION_NONCE="$(printf 4%.0s {1..64})" PROMOTE_STATE_DIR="$tmp/state-marker" "$script_dir/promote-restored-target.sh" "$backup";then exit 1;fi;[[ ! -e $tmp/state-marker/promotion-ready ]];[[ $(psql "$url" -Atqc "select datallowconn||'|'||has_database_privilege('public',datname,'connect')||'|'||has_database_privilege('$app_role',datname,'connect') from pg_database where datname=current_database()") == 't|f|t' ]]
sudo mkdir -m 700 "$tmp/state-maintenance";if sudo env "${promote_env[@]}" PROMOTION_NONCE="$(printf 5%.0s {1..64})" PROMOTE_MAINTENANCE_PGSERVICE=target PROMOTE_STATE_DIR="$tmp/state-maintenance" "$script_dir/promote-restored-target.sh" "$backup";then exit 1;fi;[[ ! -e $tmp/state-maintenance/promotion-ready ]]
psql "$url" -v ON_ERROR_STOP=1 -c "begin;set local steam_top.configure_restore_target='RESTORE_NONPRODUCTION_DATA';update restore_control.deployment_environment set environment='test',restore_allowed=true where singleton;commit;" >/dev/null;sudo mkdir -m 700 "$tmp/state-recovery";(for _ in $(seq 1 500);do [[ $(psql "$TEST_DATABASE_URL" -Atqc "select datallowconn from pg_database where datname='$db'") == f ]]&&{ sudo sh -c "printf '[broken]\n' >'$tmp/service'";exit;};sleep 0.01;done;exit 1) & breaker=$!;set +e;sudo env "${promote_env[@]}" PROMOTION_NONCE="$(printf 6%.0s {1..64})" PROMOTE_STATE_DIR="$tmp/state-recovery" "$script_dir/promote-restored-target.sh" "$backup";rc=$?;set -e;wait "$breaker"||true;breaker="";[[ $rc -eq 70 ]];incident=$(find "$tmp/state-recovery" -name 'RECOVERY-REQUIRED.*' -print -quit);[[ -n $incident ]];[[ $(stat -c '%u %a' "$incident") == '0 600' ]];grep -q 'phase=post-commit' "$incident"
