#!/usr/bin/env bash
set -euo pipefail
: "${TEST_DATABASE_URL:?}";script_dir=$(CDPATH= cd -- "$(dirname -- "$0")"&&pwd -P);root=$(CDPATH= cd -- "$script_dir/../.."&&pwd -P);tmp=$(mktemp -d);app_uid=$(id -u);db="steam_top_promote_${RANDOM}_$$";app_role="steam_top_app_${RANDOM}_$$";parent_role="steam_top_parent_${RANDOM}_$$";base=${TEST_DATABASE_URL%/*};url="$base/$db";breaker=""
cleanup(){ [[ -z $breaker ]]||kill "$breaker" >/dev/null 2>&1||true;dropdb --if-exists --force --maintenance-db="$TEST_DATABASE_URL" "$db" >/dev/null 2>&1||true;for role in "$app_role" "$parent_role" "${operator_role:-}";do [[ -z $role ]]||psql "$TEST_DATABASE_URL" -v role="$role" -Atc "select format('drop role if exists %I',:'role')"|psql "$TEST_DATABASE_URL" >/dev/null 2>&1||true;done;sudo rm -rf "$tmp";};trap cleanup EXIT
createdb --maintenance-db="$TEST_DATABASE_URL" "$db";for role in "$app_role" "$parent_role";do psql "$TEST_DATABASE_URL" -v ON_ERROR_STOP=1 -v role="$role" -Atc "select format('create role %I',:'role')"|psql "$TEST_DATABASE_URL" -v ON_ERROR_STOP=1;done;psql "$url" -v ON_ERROR_STOP=1 -f "$root/drizzle/0000_steam_top_pre_first_deploy.sql" >/dev/null;target=00000000-0000-4000-8000-000000000099;psql "$url" -v ON_ERROR_STOP=1 -c "begin;set local steam_top.configure_restore_target='RESTORE_NONPRODUCTION_DATA';update restore_control.deployment_environment set environment='test',restore_allowed=true,restore_target_id='$target' where singleton;commit;" >/dev/null
operator_role="steam_top_operator_${RANDOM}_$$";operator_password="fixture-operator-password";psql "$TEST_DATABASE_URL" -v ON_ERROR_STOP=1 -v role="$operator_role" -v password="$operator_password" -Atc "select format('create role %I login password %L',:'role',:'password')"|psql "$TEST_DATABASE_URL" -v ON_ERROR_STOP=1;psql "$TEST_DATABASE_URL" -v ON_ERROR_STOP=1 -v role="$operator_role" -c "grant pg_signal_backend to :\"role\"";psql "$url" -v ON_ERROR_STOP=1 -v role="$operator_role" -c "grant all on schema public,restore_control to :\"role\";grant all on all tables in schema public,restore_control to :\"role\";grant all on all sequences in schema public,restore_control to :\"role\"";psql "$TEST_DATABASE_URL" -v ON_ERROR_STOP=1 -v db="$db" -v role="$operator_role" -Atc "select format('alter database %I owner to %I',:'db',:'role')"|psql "$TEST_DATABASE_URL" -v ON_ERROR_STOP=1
node - "$TEST_DATABASE_URL" "$db" "$tmp/service" "$tmp/pass" "$operator_role" "$operator_password" <<'NODE'
const fs=require('fs'),[raw,db,service,pass,operator,password]=process.argv.slice(2),u=new URL(raw),host=u.hostname,port=u.port||'5432',admin=decodeURIComponent(u.username),adminPassword=decodeURIComponent(u.password),common=`host=${host}\nport=${port}\nuser=${operator}\n`;fs.writeFileSync(service,`[target]\n${common}dbname=${db}\n[maintenance]\n${common}dbname=postgres\n[wrong-cluster]\nhost=${host}\nport=5433\nuser=${admin}\ndbname=postgres\n`,{mode:0o600});fs.writeFileSync(pass,`${host}:${port}:*:${operator}:${password}\n${host}:5433:*:${admin}:${adminPassword}\n`,{mode:0o600});
NODE
export PGSERVICEFILE="$tmp/service" PGPASSFILE="$tmp/pass";: >"$tmp/ledger";chmod 600 "$tmp/ledger";ssh-keygen -q -t ed25519 -N '' -f "$tmp/signing";signer=promotion@test;printf '%s %s\n' "$signer" "$(<"$tmp/signing.pub")" >"$tmp/signers";chmod 600 "$tmp/signing" "$tmp/signers";age-keygen -o "$tmp/age" 2>"$tmp/age.log";recipient=$(awk '/public key:/{print $4}' "$tmp/age.log")
PGSERVICE=target BACKUP_DIR="$tmp/backups" AGE_RECIPIENT="$recipient" DELETION_LEDGER_FILE="$tmp/ledger" BACKUP_SIGNING_KEY="$tmp/signing" BACKUP_SIGNER_ID="$signer" BACKUP_ALLOWED_SIGNERS_FILE="$tmp/signers" "$script_dir/backup.sh" >/dev/null;backup=$(find "$tmp/backups" -maxdepth 1 -type d -name 'steam-top-*.backup' -print -quit);mkdir "$tmp/state";sudo chown -R root:root "$tmp";sudo chown "$app_uid" "$tmp/ledger";sudo chmod 711 "$tmp";sudo chmod 700 "$tmp/state";sudo chmod 600 "$tmp/service" "$tmp/pass" "$tmp/ledger" "$tmp/signers"
promote_env=(APP_UID="$app_uid" PROMOTION_NONCE="$(printf 3%.0s {1..64})" PROMOTE_PGSERVICE=target PROMOTE_MAINTENANCE_PGSERVICE=maintenance PROMOTE_APP_ROLE="$app_role" PGSERVICEFILE="$tmp/service" PGPASSFILE="$tmp/pass" PROMOTE_CONFIRM_DATABASE="$db" RESTORE_ALLOWED_TARGET_ID="$target" DELETION_LEDGER_FILE="$tmp/ledger" BACKUP_ALLOWED_SIGNERS_FILE="$tmp/signers" BACKUP_SIGNER_ID="$signer" PROMOTE_CONFIRM=PROMOTE_VERIFIED_RESTORE_TO_PRODUCTION RUNTIME_INSTALL_MANIFEST_SHA256="$RUNTIME_INSTALL_MANIFEST_SHA256")
psql "$TEST_DATABASE_URL" -v ON_ERROR_STOP=1 -v db="$db" -v parent="$parent_role" -v app="$app_role" -Atc "select format('grant connect on database %I to %I',:'db',:'parent');select format('grant %I to %I',:'parent',:'app')"|psql "$TEST_DATABASE_URL" -v ON_ERROR_STOP=1;sudo mkdir -m 700 "$tmp/state-inherited";if sudo env "${promote_env[@]}" PROMOTION_NONCE="$(printf 8%.0s {1..64})" PROMOTE_STATE_DIR="$tmp/state-inherited" "$script_dir/promote-restored-target.sh" "$backup";then exit 1;fi;[[ ! -e $tmp/state-inherited/promotion-ready ]];[[ $(psql "$url" -Atqc "select datallowconn||'|'||(select environment from restore_control.deployment_environment where singleton)||'|'||has_database_privilege('$app_role',current_database(),'connect')") == 't|test|t' ]];psql "$TEST_DATABASE_URL" -v ON_ERROR_STOP=1 -v db="$db" -v parent="$parent_role" -v app="$app_role" -Atc "select format('revoke %I from %I',:'parent',:'app');select format('revoke connect on database %I from %I',:'db',:'parent')"|psql "$TEST_DATABASE_URL" -v ON_ERROR_STOP=1
sudo env "${promote_env[@]}" PROMOTE_STATE_DIR="$tmp/state" "$script_dir/promote-restored-target.sh" "$backup";[[ $(stat -c '%u %a' "$tmp/ledger") == "$app_uid 600" ]]
[[ -f $tmp/state/promotion-ready ]];[[ $(psql "$url" -Atqc "select has_database_privilege('public',current_database(),'connect')||'|'||has_database_privilege('$app_role',current_database(),'connect')") == 'f|f' ]];[[ $(psql "$url" -Atqc "select count(*) from restore_control.promotion_outbox where nonce='$(printf 3%.0s {1..64})' and state='committed'") == 1 ]]
sudo rm -f "$tmp/state/promotion-ready.sha256";if sudo env PROMOTE_PGSERVICE=target PGSERVICEFILE="$tmp/service" PGPASSFILE="$tmp/pass" RUNTIME_INSTALL_MANIFEST_SHA256="$RUNTIME_INSTALL_MANIFEST_SHA256" "$script_dir/reconcile-promotion-ready.sh" "$tmp/state" "$(printf 3%.0s {1..64})";then exit 1;fi
sudo rm -f "$tmp/state/promotion-ready";[[ $(psql "$url" -Atqc "select count(*) from restore_control.promotion_outbox where nonce='$(printf 3%.0s {1..64})' and state='committed'") == 1 ]];sudo env PROMOTE_PGSERVICE=target PGSERVICEFILE="$tmp/service" PGPASSFILE="$tmp/pass" RUNTIME_INSTALL_MANIFEST_SHA256="$RUNTIME_INSTALL_MANIFEST_SHA256" "$script_dir/reconcile-promotion-ready.sh" "$tmp/state" "$(printf 3%.0s {1..64})";[[ -f $tmp/state/promotion-ready && -f $tmp/state/promotion-ready.sha256 ]]
sudo cp "$tmp/state/promotion-ready" "$tmp/original-ready";sudo cp "$tmp/state/promotion-ready.sha256" "$tmp/original-ready.sha256";sudo ssh-keygen -q -t ed25519 -N '' -f "$tmp/cutover-signing";cutover_signer=cutover@test;sudo sh -c "printf '%s %s\n' '$cutover_signer' \"\$(cat '$tmp/cutover-signing.pub')\" >'$tmp/cutover-signers'";sudo chmod 600 "$tmp/cutover-signing" "$tmp/cutover-signers"
cutover="$tmp/state/cutover.json";cutover_nonce=$(printf 3%.0s {1..64});manifest_sha=$(printf 1%.0s {1..64});system_id=$(psql "$url" -Atqc "select system_identifier from pg_control_system()")
printf '%s\n' "$url"|sudo tee "$tmp/database-url" >/dev/null;printf '{"nonce":"%s","restoreTargetId":"%s","systemIdentifier":"%s","createdAt":"2026-01-01T00:00:00.000Z"}\n' "$cutover_nonce" "$target" "$system_id"|sudo tee "$tmp/probe.json" >/dev/null;sudo chmod 600 "$tmp/database-url" "$tmp/probe.json"
sudo node "$root/scripts/create-cutover-receipt.mjs" "$tmp/state/promotion-ready" "$tmp/database-url" https://steam-top.test "$manifest_sha" "$cutover_nonce" "$tmp/probe.json" "$cutover";sudo ssh-keygen -Y sign -q -f "$tmp/cutover-signing" -n steam-top-cutover "$cutover";sudo chmod 400 "$cutover" "$cutover.sig"
sudo ssh-keygen -q -t ed25519 -N '' -f "$tmp/host-signing";host_signer=host@test;sudo sh -c "printf '%s %s\n' '$host_signer' \"\$(cat '$tmp/host-signing.pub')\" >'$tmp/host-signers'"
sudo sh -c "printf 'PUBLIC_ORIGIN=https://steam-top.test\nDATABASE_URL=%s\n' '$url' >'$tmp/production.env'"
sudo node - "$tmp/protected-state.json" "$tmp/host-receipt.json" "$manifest_sha" "$cutover_nonce" "$target" "$system_id" <<'NODE'
const fs=require("fs"),[state,host,manifest,nonce,target,system]=process.argv.slice(2),commit="a".repeat(40);fs.writeFileSync(state,JSON.stringify({schemaVersion:4,purpose:"production",deploymentId:"1",activatedAt:"2026-01-01T00:00:00.000Z",smoke:{complete:true},manifestSha256:manifest,nonce,commit})+"\n");fs.writeFileSync(host,JSON.stringify({schemaVersion:4,purpose:"production",smoke:{complete:true},manifestDigest:manifest,nonce,commit,publicOrigin:"https://steam-top.test",database:{systemIdentifier:system,restoreTargetId:target,markerEnvironment:"production",restoreAllowed:false}})+"\n");
NODE
sudo ssh-keygen -Y sign -q -f "$tmp/host-signing" -n steam-top-production-deployment "$tmp/host-receipt.json";sudo chmod 600 "$tmp/host-signing" "$tmp/host-signers" "$tmp/production.env" "$tmp/protected-state.json" "$tmp/host-receipt.json" "$tmp/host-receipt.json.sig"
sudo ssh-keygen -Y sign -q -f "$tmp/host-signing" -n steam-top-protected-deployment-state "$tmp/protected-state.json";sudo chmod 600 "$tmp/protected-state.json.sig"
sudo node - "$tmp/protected-state.json" "$tmp/activation.json" <<'NODE'
const fs=require("fs"),crypto=require("crypto"),s=require(process.argv[2]),digest=crypto.createHash("sha256").update(fs.readFileSync(process.argv[2])).digest("hex");fs.writeFileSync(process.argv[3],JSON.stringify({schemaVersion:1,purpose:"production-activation-receipt",deploymentId:s.deploymentId,nonce:s.nonce,stateDigest:digest,activatedAt:s.activatedAt})+"\n");
NODE
sudo ssh-keygen -Y sign -q -f "$tmp/host-signing" -n steam-top-production-activation "$tmp/activation.json";sudo chmod 600 "$tmp/activation.json" "$tmp/activation.json.sig"
psql "$url" -v ON_ERROR_STOP=1 -v nonce="$cutover_nonce" -v target="$target" -v system="$system_id" -c "create table if not exists restore_control.deployment_probe(nonce text primary key,restore_target_id uuid not null,system_identifier text not null,state text not null,consumed_at timestamptz);insert into restore_control.deployment_probe values(:'nonce',:'target'::uuid,:'system','receipt-signed',null) on conflict(nonce) do update set state='receipt-signed'" >/dev/null
finalize_env=(CANONICAL_STATE_RESOLVED=true PROMOTE_PGSERVICE=target PGSERVICEFILE="$tmp/service" PGPASSFILE="$tmp/pass" CUTOVER_ALLOWED_SIGNERS_FILE="$tmp/cutover-signers" CUTOVER_SIGNER_ID="$cutover_signer" RUNTIME_INSTALL_MANIFEST_SHA256="$RUNTIME_INSTALL_MANIFEST_SHA256" PRODUCTION_ENV_FILE="$tmp/production.env" PROTECTED_DEPLOYMENT_STATE_FILE="$tmp/protected-state.json" PROTECTED_DEPLOYMENT_STATE_SIGNATURE="$tmp/protected-state.json.sig" PROTECTED_STATE_ALLOWED_SIGNERS_FILE="$tmp/host-signers" PROTECTED_STATE_SIGNER_ID="$host_signer" ACTIVATION_RECEIPT_FILE="$tmp/activation.json" ACTIVATION_RECEIPT_SIGNATURE="$tmp/activation.json.sig" HOST_DEPLOYMENT_RECEIPT_FILE="$tmp/host-receipt.json" HOST_DEPLOYMENT_RECEIPT_SIGNATURE="$tmp/host-receipt.json.sig" HOST_RECEIPT_ALLOWED_SIGNERS_FILE="$tmp/host-signers" HOST_RECEIPT_SIGNER_ID="$host_signer")
sudo chmod 600 "$tmp/state/promotion-ready";sudo sh -c "printf tamper >>'$tmp/state/promotion-ready'";sudo chmod 400 "$tmp/state/promotion-ready";if sudo env "${finalize_env[@]}" "$script_dir/finalize-cutover.sh" "$tmp/state/promotion-ready" "$cutover" "$cutover.sig";then exit 1;fi;[[ $(psql "$url" -Atqc "select has_database_privilege('$app_role',current_database(),'connect')") == f ]]
sudo cp "$tmp/original-ready" "$tmp/state/promotion-ready";sudo cp "$tmp/original-ready.sha256" "$tmp/state/promotion-ready.sha256";sudo chmod 400 "$tmp/state/promotion-ready" "$tmp/state/promotion-ready.sha256";sudo touch "$tmp/state/promotion-ready.finalized.$cutover_nonce";sudo chmod 400 "$tmp/state/promotion-ready.finalized.$cutover_nonce";if sudo env "${finalize_env[@]}" "$script_dir/finalize-cutover.sh" "$tmp/state/promotion-ready" "$cutover" "$cutover.sig";then exit 1;fi;[[ $(psql "$url" -Atqc "select count(*) from restore_control.promotion_audit") == 1 ]];[[ $(psql "$url" -Atqc "select count(*) from restore_control.finalize_outbox where nonce='$cutover_nonce' and state='committed'") == 1 ]];[[ $(psql "$url" -Atqc "select has_database_privilege('$app_role',current_database(),'connect')") == t ]];sudo rm -f "$tmp/state/promotion-ready.finalized.$cutover_nonce";sudo env "${finalize_env[@]}" "$script_dir/finalize-cutover.sh" "$tmp/state/promotion-ready" "$cutover" "$cutover.sig";sudo "$script_dir/reconcile-finalize-outbox.sh" "$tmp/state/promotion-ready" "$cutover" "$cutover.sig" "$cutover_nonce";[[ $(psql "$url" -Atqc "select count(*) from restore_control.promotion_audit") == 1 ]]
sudo mkdir -m 700 "$tmp/state-marker";if sudo env "${promote_env[@]}" PROMOTION_NONCE="$(printf 4%.0s {1..64})" PROMOTE_STATE_DIR="$tmp/state-marker" "$script_dir/promote-restored-target.sh" "$backup";then exit 1;fi;[[ ! -e $tmp/state-marker/promotion-ready ]];[[ $(psql "$url" -Atqc "select datallowconn||'|'||has_database_privilege('public',datname,'connect')||'|'||has_database_privilege('$app_role',datname,'connect') from pg_database where datname=current_database()") == 't|f|t' ]]
sudo mkdir -m 700 "$tmp/state-maintenance";if sudo env "${promote_env[@]}" PROMOTION_NONCE="$(printf 5%.0s {1..64})" PROMOTE_MAINTENANCE_PGSERVICE=target PROMOTE_STATE_DIR="$tmp/state-maintenance" "$script_dir/promote-restored-target.sh" "$backup";then exit 1;fi;[[ ! -e $tmp/state-maintenance/promotion-ready ]]
sudo mkdir -m 700 "$tmp/state-wrong-cluster";if sudo env "${promote_env[@]}" PROMOTION_NONCE="$(printf 7%.0s {1..64})" PROMOTE_MAINTENANCE_PGSERVICE=wrong-cluster PROMOTE_STATE_DIR="$tmp/state-wrong-cluster" "$script_dir/promote-restored-target.sh" "$backup";then exit 1;fi;[[ ! -e $tmp/state-wrong-cluster/promotion-ready ]];[[ ! -e $tmp/state-wrong-cluster/RECOVERY-REQUIRED ]]
psql "$url" -v ON_ERROR_STOP=1 -c "begin;set local steam_top.configure_restore_target='RESTORE_NONPRODUCTION_DATA';update restore_control.deployment_environment set environment='test',restore_allowed=true where singleton;commit;" >/dev/null;sudo mkdir -m 700 "$tmp/state-recovery";(for _ in $(seq 1 500);do [[ $(psql "$TEST_DATABASE_URL" -Atqc "select datallowconn from pg_database where datname='$db'") == f ]]&&{ sudo sh -c "printf '[broken]\n' >'$tmp/service'";exit;};sleep 0.01;done;exit 1) & breaker=$!;set +e;sudo env "${promote_env[@]}" PROMOTION_NONCE="$(printf 6%.0s {1..64})" PROMOTE_STATE_DIR="$tmp/state-recovery" "$script_dir/promote-restored-target.sh" "$backup";rc=$?;set -e;wait "$breaker"||true;breaker="";[[ $rc -eq 70 ]];incident=$(find "$tmp/state-recovery" -name 'RECOVERY-REQUIRED.*' -print -quit);[[ -n $incident ]];[[ $(stat -c '%u %a' "$incident") == '0 600' ]];grep -q 'phase=post-commit' "$incident"
