#!/usr/bin/env bash
set -euo pipefail
[[ ${1:-} == --hook && -n ${CANONICAL_STATE_NONCE:-} && -n ${CANONICAL_HOST_RECEIPT_FILE:-} ]]||return 2
sudo rm -f "$cutover" "$cutover.sig";canonical_env=/opt/steam-top/.release-integration/production.env;canonical_db_url=$(sudo sed -n 's/^DATABASE_URL=//p' "$canonical_env");printf '%s\n' "$canonical_db_url"|sudo tee "$tmp/database-url" >/dev/null;sudo chmod 0600 "$tmp/database-url";runtime=/opt/steam-top/releases/$RUNTIME_INSTALL_MANIFEST_SHA256;sudo docker compose -p steam-top-release-integration --project-directory "$runtime" --env-file "$canonical_env" -f "$runtime/compose.yaml" -f "$runtime/compose.release-integration.yaml" stop server
record_env=(SMOKE_INTEGRATION_MODE=true PROMOTE_PGSERVICE=target PGSERVICEFILE="$tmp/service" PGPASSFILE="$tmp/pass" CUTOVER_DATABASE_URL_FILE="$tmp/database-url" PUBLIC_ORIGIN="$public_origin" DEPLOYMENT_MANIFEST_SHA256="$manifest_sha" CUTOVER_SIGNING_KEY="$tmp/cutover-signing" CUTOVER_ALLOWED_SIGNERS_FILE="$tmp/cutover-signers" CUTOVER_SIGNER_ID="$cutover_signer" ADMIN_SMOKE_SECRET_FILE=/opt/steam-top/.release-integration/secrets/admin-smoke.json PRODUCTION_ENV_FILE="$canonical_env" HOST_DEPLOYMENT_RECEIPT_FILE="$CANONICAL_HOST_RECEIPT_FILE" HOST_DEPLOYMENT_RECEIPT_SIGNATURE="$CANONICAL_HOST_RECEIPT_FILE.sig" HOST_RECEIPT_ALLOWED_SIGNERS_FILE=/opt/steam-top/.release-integration/secrets/host-allowed-signers HOST_RECEIPT_SIGNER_ID=host-ci PROTECTED_STATE_ALLOWED_SIGNERS_FILE=/opt/steam-top/.release-integration/secrets/state-allowed-signers PROTECTED_STATE_SIGNER_ID=state-ci RUNTIME_INSTALL_MANIFEST_SHA256="$RUNTIME_INSTALL_MANIFEST_SHA256")
sudo env "${record_env[@]}" /opt/steam-top-bootstrap/record-cutover-current.sh "$CANONICAL_STATE_NONCE" "$tmp/state/promotion-ready" "$cutover"
sudo env SMOKE_INTEGRATION_MODE=true "${finalize_env[@]}" PRODUCTION_ENV_FILE="$canonical_env" HOST_DEPLOYMENT_RECEIPT_FILE="$CANONICAL_HOST_RECEIPT_FILE" HOST_DEPLOYMENT_RECEIPT_SIGNATURE="$CANONICAL_HOST_RECEIPT_FILE.sig" HOST_RECEIPT_ALLOWED_SIGNERS_FILE=/opt/steam-top/.release-integration/secrets/host-allowed-signers HOST_RECEIPT_SIGNER_ID=host-ci PROTECTED_STATE_ALLOWED_SIGNERS_FILE=/opt/steam-top/.release-integration/secrets/state-allowed-signers PROTECTED_STATE_SIGNER_ID=state-ci /opt/steam-top-bootstrap/finalize-current.sh "$CANONICAL_STATE_NONCE" "$tmp/state/promotion-ready" "$cutover" "$cutover.sig"
[[ $(psql "$url" -Atqc "select state from restore_control.finalize_outbox where nonce='$cutover_nonce'") == connect-granted-pending-smoke ]]
durable=/opt/steam-top/.release-integration/cutover/$cutover_nonce;sudo install -d -o root -g root -m 0700 "$durable";for pair in "$tmp/state/promotion-ready:promotion-ready" "$tmp/state/promotion-ready.sha256:promotion-ready.sha256" "$cutover:preflight.json" "$cutover.sig:preflight.json.sig" "$tmp/cutover-signers:cutover-signers";do sudo install -o root -g root -m 0400 "${pair%%:*}" "$durable/${pair#*:}";done
set -E;abort_pending(){ rc=$?;trap - ERR;sudo env "${record_env[@]}" CUTOVER_ALLOWED_SIGNERS_FILE="$durable/cutover-signers" PROMOTE_STATE_DIR="$durable" /opt/steam-top-bootstrap/abort-cutover-current.sh "$CANONICAL_STATE_NONCE" "$durable/promotion-ready" "$durable/preflight.json" "$durable/preflight.json.sig" >/dev/null 2>&1||true;return "$rc";};trap abort_pending ERR
sudo docker compose -p steam-top-release-integration --project-directory "$runtime" --env-file "$canonical_env" -f "$runtime/compose.yaml" -f "$runtime/compose.release-integration.yaml" up -d --force-recreate --wait server
smoke_probe=$(mktemp /tmp/steam-top-public-smoke.XXXXXX);rm -f "$smoke_probe";sudo env SMOKE_INTEGRATION_MODE=true ADMIN_SMOKE_SECRET_FILE=/opt/steam-top/.release-integration/secrets/admin-smoke.json PRODUCTION_SMOKE_PROBE_OUTPUT="$smoke_probe" "$runtime/scripts/production-smoke.sh" "$public_origin" "$cutover_nonce"
final="$tmp/state/final-cutover.json";sudo env "${record_env[@]}" PROMOTE_STATE_DIR="$tmp/state" /opt/steam-top-bootstrap/confirm-cutover-current.sh "$CANONICAL_STATE_NONCE" "$tmp/state/promotion-ready" "$cutover" "$cutover.sig" "$smoke_probe" "$final"
[[ $(psql "$url" -Atqc "select state from restore_control.finalize_outbox where nonce='$cutover_nonce'") == verified ]];[[ $(psql "$url" -Atqc 'select count(*) from restore_control.promotion_audit where finalized_at is not null') == 1 ]];[[ -f $final && -f $final.sig ]];trap - ERR;sudo rm -f "$smoke_probe";sudo rm -rf "$durable";return 0
