#!/usr/bin/env bash
set -euo pipefail
: "${TEST_DATABASE_URL:?}";script_dir=$(CDPATH= cd -- "$(dirname -- "$0")"&&pwd -P);root=$(CDPATH= cd -- "$script_dir/../.."&&pwd -P);tmp=$(mktemp -d);db="steam_top_promote_${RANDOM}_$$";app_role="steam_top_app_${RANDOM}_$$";base=${TEST_DATABASE_URL%/*};url="$base/$db"
cleanup(){ dropdb --if-exists --force --maintenance-db="$TEST_DATABASE_URL" "$db" >/dev/null 2>&1||true;psql "$TEST_DATABASE_URL" -v role="$app_role" -Atc "select format('drop role if exists %I',:'role')"|psql "$TEST_DATABASE_URL" >/dev/null 2>&1||true;sudo rm -rf "$tmp";};trap cleanup EXIT
createdb --maintenance-db="$TEST_DATABASE_URL" "$db";psql "$TEST_DATABASE_URL" -v ON_ERROR_STOP=1 -v role="$app_role" -Atc "select format('create role %I',:'role')"|psql "$TEST_DATABASE_URL" -v ON_ERROR_STOP=1;psql "$url" -v ON_ERROR_STOP=1 -f "$root/drizzle/0000_steam_top_pre_first_deploy.sql" >/dev/null;target=00000000-0000-4000-8000-000000000099;psql "$url" -v ON_ERROR_STOP=1 -c "begin;set local steam_top.configure_restore_target='RESTORE_NONPRODUCTION_DATA';update restore_control.deployment_environment set environment='test',restore_allowed=true,restore_target_id='$target' where singleton;commit;" >/dev/null
node - "$TEST_DATABASE_URL" "$db" "$tmp/service" "$tmp/pass" <<'NODE'
const fs=require('fs'),[raw,db,service,pass]=process.argv.slice(2),u=new URL(raw),host=u.hostname,port=u.port||'5432',user=decodeURIComponent(u.username),password=decodeURIComponent(u.password),common=`host=${host}\nport=${port}\nuser=${user}\n`;fs.writeFileSync(service,`[target]\n${common}dbname=${db}\n[maintenance]\n${common}dbname=postgres\n`,{mode:0o600});fs.writeFileSync(pass,`${host}:${port}:*:${user}:${password}\n`,{mode:0o600});
NODE
export PGSERVICEFILE="$tmp/service" PGPASSFILE="$tmp/pass";: >"$tmp/ledger";chmod 600 "$tmp/ledger";ssh-keygen -q -t ed25519 -N '' -f "$tmp/signing";signer=promotion@test;printf '%s %s\n' "$signer" "$(<"$tmp/signing.pub")" >"$tmp/signers";chmod 600 "$tmp/signing" "$tmp/signers";age-keygen -o "$tmp/age" 2>"$tmp/age.log";recipient=$(awk '/public key:/{print $4}' "$tmp/age.log")
PGSERVICE=target BACKUP_DIR="$tmp/backups" AGE_RECIPIENT="$recipient" DELETION_LEDGER_FILE="$tmp/ledger" BACKUP_SIGNING_KEY="$tmp/signing" BACKUP_SIGNER_ID="$signer" BACKUP_ALLOWED_SIGNERS_FILE="$tmp/signers" "$script_dir/backup.sh" >/dev/null;backup=$(find "$tmp/backups" -maxdepth 1 -type d -name 'steam-top-*.backup' -print -quit);mkdir "$tmp/state";sudo chown -R root:root "$tmp";sudo chmod 700 "$tmp/state";sudo chmod 600 "$tmp/service" "$tmp/pass" "$tmp/ledger" "$tmp/signers"
sudo env PROMOTE_PGSERVICE=target PROMOTE_MAINTENANCE_PGSERVICE=maintenance PROMOTE_APP_ROLE="$app_role" PROMOTE_STATE_DIR="$tmp/state" PGSERVICEFILE="$tmp/service" PGPASSFILE="$tmp/pass" PROMOTE_CONFIRM_DATABASE="$db" RESTORE_ALLOWED_TARGET_ID="$target" DELETION_LEDGER_FILE="$tmp/ledger" BACKUP_ALLOWED_SIGNERS_FILE="$tmp/signers" BACKUP_SIGNER_ID="$signer" PROMOTE_CONFIRM=PROMOTE_VERIFIED_RESTORE_TO_PRODUCTION "$script_dir/promote-restored-target.sh" "$backup"
[[ -f $tmp/state/promotion-ready ]];[[ $(psql "$url" -Atqc "select has_database_privilege('public',current_database(),'connect')||'|'||has_database_privilege('$app_role',current_database(),'connect')") == 'f|f' ]]
sudo cp "$tmp/state/promotion-ready" "$tmp/original-ready";sudo cp "$tmp/state/promotion-ready.sha256" "$tmp/original-ready.sha256";sudo chmod 600 "$tmp/state/promotion-ready";sudo sh -c "printf tamper >>'$tmp/state/promotion-ready'";sudo chmod 400 "$tmp/state/promotion-ready";if sudo env CUTOVER_CONFIRM=DATABASE_URL_CUTOVER_SUCCEEDED PROMOTE_PGSERVICE=target PGSERVICEFILE="$tmp/service" PGPASSFILE="$tmp/pass" "$script_dir/finalize-cutover.sh" "$tmp/state/promotion-ready";then exit 1;fi;[[ $(psql "$url" -Atqc "select has_database_privilege('$app_role',current_database(),'connect')") == f ]]
sudo cp "$tmp/original-ready" "$tmp/state/promotion-ready";sudo chmod 600 "$tmp/state/promotion-ready";sudo node -e 'const fs=require("fs"),p=process.argv[1],x=JSON.parse(fs.readFileSync(p));x.systemIdentifier="0";fs.writeFileSync(p,JSON.stringify(x)+"\n")' "$tmp/state/promotion-ready";sudo "$root/scripts/portable-sha256.sh" digest "$tmp/state/promotion-ready"|sudo tee "$tmp/state/promotion-ready.sha256" >/dev/null;sudo chmod 400 "$tmp/state/promotion-ready" "$tmp/state/promotion-ready.sha256";if sudo env CUTOVER_CONFIRM=DATABASE_URL_CUTOVER_SUCCEEDED PROMOTE_PGSERVICE=target PGSERVICEFILE="$tmp/service" PGPASSFILE="$tmp/pass" "$script_dir/finalize-cutover.sh" "$tmp/state/promotion-ready";then exit 1;fi
sudo cp "$tmp/original-ready" "$tmp/state/promotion-ready";sudo cp "$tmp/original-ready.sha256" "$tmp/state/promotion-ready.sha256";sudo chmod 400 "$tmp/state/promotion-ready" "$tmp/state/promotion-ready.sha256";sudo env CUTOVER_CONFIRM=DATABASE_URL_CUTOVER_SUCCEEDED PROMOTE_PGSERVICE=target PGSERVICEFILE="$tmp/service" PGPASSFILE="$tmp/pass" "$script_dir/finalize-cutover.sh" "$tmp/state/promotion-ready";[[ $(psql "$url" -Atqc "select count(*) from restore_control.promotion_audit") == 1 ]];if sudo env CUTOVER_CONFIRM=DATABASE_URL_CUTOVER_SUCCEEDED PROMOTE_PGSERVICE=target PGSERVICEFILE="$tmp/service" PGPASSFILE="$tmp/pass" "$script_dir/finalize-cutover.sh" "$tmp/state/promotion-ready";then exit 1;fi
sudo mkdir -m 700 "$tmp/state-marker";if sudo env PROMOTE_PGSERVICE=target PROMOTE_MAINTENANCE_PGSERVICE=maintenance PROMOTE_APP_ROLE="$app_role" PROMOTE_STATE_DIR="$tmp/state-marker" PGSERVICEFILE="$tmp/service" PGPASSFILE="$tmp/pass" PROMOTE_CONFIRM_DATABASE="$db" RESTORE_ALLOWED_TARGET_ID="$target" DELETION_LEDGER_FILE="$tmp/ledger" BACKUP_ALLOWED_SIGNERS_FILE="$tmp/signers" BACKUP_SIGNER_ID="$signer" PROMOTE_CONFIRM=PROMOTE_VERIFIED_RESTORE_TO_PRODUCTION "$script_dir/promote-restored-target.sh" "$backup";then exit 1;fi;[[ ! -e $tmp/state-marker/promotion-ready ]];[[ $(psql "$url" -Atqc "select datallowconn||'|'||has_database_privilege('public',datname,'connect')||'|'||has_database_privilege('$app_role',datname,'connect') from pg_database where datname=current_database()") == 't|f|t' ]]
sudo mkdir -m 700 "$tmp/state-maintenance";if sudo env PROMOTE_PGSERVICE=target PROMOTE_MAINTENANCE_PGSERVICE=target PROMOTE_APP_ROLE="$app_role" PROMOTE_STATE_DIR="$tmp/state-maintenance" PGSERVICEFILE="$tmp/service" PGPASSFILE="$tmp/pass" PROMOTE_CONFIRM_DATABASE="$db" RESTORE_ALLOWED_TARGET_ID="$target" DELETION_LEDGER_FILE="$tmp/ledger" BACKUP_ALLOWED_SIGNERS_FILE="$tmp/signers" BACKUP_SIGNER_ID="$signer" PROMOTE_CONFIRM=PROMOTE_VERIFIED_RESTORE_TO_PRODUCTION "$script_dir/promote-restored-target.sh" "$backup";then exit 1;fi;[[ ! -e $tmp/state-maintenance/promotion-ready ]]
psql "$url" -v ON_ERROR_STOP=1 -c "begin;set local steam_top.configure_restore_target='RESTORE_NONPRODUCTION_DATA';update restore_control.deployment_environment set environment='test',restore_allowed=true where singleton;commit;" >/dev/null;sudo mkdir -m 700 "$tmp/state-recovery";(while [[ $(psql "$TEST_DATABASE_URL" -Atqc "select datallowconn from pg_database where datname='$db'") == t ]];do sleep 0.01;done;sudo sh -c "printf '[broken]\n' >'$tmp/service'") & breaker=$!;set +e;sudo env PROMOTE_PGSERVICE=target PROMOTE_MAINTENANCE_PGSERVICE=maintenance PROMOTE_APP_ROLE="$app_role" PROMOTE_STATE_DIR="$tmp/state-recovery" PGSERVICEFILE="$tmp/service" PGPASSFILE="$tmp/pass" PROMOTE_CONFIRM_DATABASE="$db" RESTORE_ALLOWED_TARGET_ID="$target" DELETION_LEDGER_FILE="$tmp/ledger" BACKUP_ALLOWED_SIGNERS_FILE="$tmp/signers" BACKUP_SIGNER_ID="$signer" PROMOTE_CONFIRM=PROMOTE_VERIFIED_RESTORE_TO_PRODUCTION "$script_dir/promote-restored-target.sh" "$backup";rc=$?;set -e;wait "$breaker"||true;[[ $rc -eq 70 ]];incident=$(find "$tmp/state-recovery" -name 'RECOVERY-REQUIRED.*' -print -quit);[[ -n $incident ]];[[ $(stat -c '%u %a' "$incident") == '0 600' ]];grep -q 'phase=post-commit' "$incident"
