#!/usr/bin/env bash
set -euo pipefail

: "${TEST_DATABASE_URL:?}" "${RUNTIME_INSTALL_MANIFEST_SHA256:?}"
script_dir=$(CDPATH= cd -- "$(dirname -- "$0")"&&pwd -P);root=$(CDPATH= cd -- "$script_dir/../.."&&pwd -P);bootstrap=/opt/steam-top-bootstrap;activate=/opt/steam-top-bootstrap/activate-production-state.sh;fixture=""
if [[ ${1:-} == --hook ]];then
  fixture=$(sudo node -e 'const c=require("/etc/steam-top-bootstrap/trust.json"),p=c.hostReceiptOutbox;if(typeof p!=="string"||!/^\/run\/[a-z0-9-]+\/outbox$/.test(p))process.exit(1);process.stdout.write(p.slice(0,-7))')
  echo "canonical hook checkpoint: entered"
  sudo install -d -o root -g root -m 0700 "$fixture/outbox/receipts/$cutover_nonce" "$fixture/outbox/deployment-ledger"
  receipt_digest=$(sudo "$root/scripts/portable-sha256.sh" digest "$tmp/host-receipt.json");receipt_generation="$fixture/outbox/receipts/$cutover_nonce/$receipt_digest";sudo install -d -o root -g root -m 0500 "$receipt_generation";sudo install -o root -g root -m 0400 "$tmp/host-receipt.json" "$receipt_generation/payload.json";sudo install -o root -g root -m 0400 "$tmp/host-receipt.json.sig" "$receipt_generation/payload.json.sig";sudo ln -s "$receipt_digest" "$fixture/outbox/receipts/$cutover_nonce/current"
  for key in ledger-old-key ledger-key state-key evidence-key legacy-key;do sudo test -f "$fixture/$key"||sudo ssh-keygen -q -t ed25519 -N '' -f "$fixture/$key";done;old_ledger="$fixture/ledger-old.json";sudo node - "$old_ledger" <<'NODE'
require("fs").writeFileSync(process.argv[2],JSON.stringify({schemaVersion:2,purpose:"steam-top-host-deployment-ledger",signerKeyId:"ledger-ci-old",sequence:1,previousDigest:null,deploymentId:"999",manifestSha256:"9".repeat(64),receiptSha256:"8".repeat(64),nonce:"7".repeat(64),previousState:"none"})+"\n",{mode:0o400});
NODE
  sudo ssh-keygen -Y sign -q -f "$fixture/ledger-old-key" -n steam-top-host-deployment-ledger "$old_ledger";old_digest=$(sudo "$root/scripts/portable-sha256.sh" digest "$old_ledger");old_generation="$fixture/outbox/deployment-ledger/00000000000000000001-$old_digest";sudo install -d -o root -g root -m 0500 "$old_generation";sudo install -o root -g root -m 0400 "$old_ledger" "$old_generation/payload.json";sudo install -o root -g root -m 0400 "$old_ledger.sig" "$old_generation/payload.json.sig";ledger="$fixture/ledger.json";sudo node - "$ledger" "$receipt_digest" "$cutover_nonce" "$manifest_sha" "$old_digest" <<'NODE'
const fs=require("fs"),[out,receiptSha256,nonce,manifestSha256,previousDigest]=process.argv.slice(2);fs.writeFileSync(out,JSON.stringify({schemaVersion:2,purpose:"steam-top-host-deployment-ledger",signerKeyId:"ledger-ci",sequence:2,previousDigest,deploymentId:"1",manifestSha256,receiptSha256,nonce,previousState:"none"})+"\n",{mode:0o400});
NODE
  sudo ssh-keygen -Y sign -q -f "$fixture/ledger-key" -n steam-top-host-deployment-ledger "$ledger";ledger_digest=$(sudo "$root/scripts/portable-sha256.sh" digest "$ledger");ledger_generation="$fixture/outbox/deployment-ledger/00000000000000000002-$ledger_digest";sudo install -d -o root -g root -m 0500 "$ledger_generation";sudo install -o root -g root -m 0400 "$ledger" "$ledger_generation/payload.json";sudo install -o root -g root -m 0400 "$ledger.sig" "$ledger_generation/payload.json.sig"
  echo "canonical hook checkpoint: receipt and ledger generations"
  printf 'host@test %s\n' "$(sudo cat "$tmp/host-signing.pub")"|sudo tee "$fixture/host-allowed" >/dev/null;{ printf 'ledger-ci-old %s\n' "$(sudo ssh-keygen -y -f "$fixture/ledger-old-key")";printf 'ledger-ci %s\n' "$(sudo ssh-keygen -y -f "$fixture/ledger-key")";}|sudo tee "$fixture/ledger-allowed" >/dev/null;printf 'state-ci %s\n' "$(sudo ssh-keygen -y -f "$fixture/state-key")"|sudo tee "$fixture/state-allowed" >/dev/null;printf 'evidence-ci %s\n' "$(sudo ssh-keygen -y -f "$fixture/evidence-key")"|sudo tee "$fixture/evidence-allowed" >/dev/null;printf 'legacy-ci %s\n' "$(sudo ssh-keygen -y -f "$fixture/legacy-key")"|sudo tee "$fixture/legacy-allowed" >/dev/null;for key in ledger-old-key ledger-key state-key evidence-key legacy-key;do sudo chown root:root "$fixture/$key";sudo chmod 0400 "$fixture/$key";done;for allowed_file in host-allowed ledger-allowed state-allowed evidence-allowed legacy-allowed;do sudo chown root:root "$fixture/$allowed_file";sudo chmod 0444 "$fixture/$allowed_file";done
  echo "canonical hook checkpoint: trust files"
  printf '%s\n' functional-fixture|sudo tee "$fixture/github-token" >/dev/null;sudo chmod 0400 "$fixture/github-token"
  bundle="$fixture/authorization.json";sudo node - "$bundle" "$RUNTIME_INSTALL_MANIFEST_SHA256" "$manifest_sha" "$cutover_nonce" "${GITHUB_REPOSITORY:-school/steam-top}" <<'NODE'
  const fs=require("fs"),[out,runtimeManifestSha256,manifestSha256,nonce,repository]=process.argv.slice(2);fs.writeFileSync(out,JSON.stringify({schemaVersion:1,purpose:"production-deployment-authorization",deploymentPurpose:"production",deploymentEnvironment:"production",repository,deploymentId:"1",nonce,manifestSha256,runtimeManifestSha256,commit:"a".repeat(40),expectedPreviousState:"none"})+"\n",{mode:0o400});
NODE
  echo "canonical hook checkpoint: authorization bundle"
  sudo install -d -o root -g root -m 0555 "$fixture/bin";sudo node - "$fixture/bin/gh" "$cutover_nonce" "$manifest_sha" "${GITHUB_REPOSITORY:-school/steam-top}" "$fixture" <<'NODE'
const fs=require("fs"),[out,nonce,manifest,repo,fixture]=process.argv.slice(2);fs.writeFileSync(out,`#!/usr/bin/env bash\nset -euo pipefail\n[[ \${GH_TOKEN:-} == functional-fixture && \$# -eq 4 && \$1 == api && \$2 == 'repos/${repo}/deployments?environment=production&per_page=1' && \$3 == --jq ]]||exit 64\nprintf '%s\\n' '1|${nonce}|${manifest}'\nprintf '%q ' \"\$@\" >>${fixture}/gh.calls\nprintf '\\n' >>${fixture}/gh.calls\n`,{mode:0o555});
NODE
  sudo chown root:root "$fixture/bin/gh";sudo chmod 0555 "$fixture/bin/gh"
  echo "canonical hook checkpoint: gh fixture"
  sudo env PS4='+activate:${LINENO}: ' PATH="$fixture/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" bash -x "$activate" "$bundle" |sudo tee "$tmp/activation.frame" >/dev/null
  sudo grep -Fq "environment=production" "$fixture/gh.calls"
  echo "canonical hook checkpoint: first activation"
  sudo cp "$fixture/ledger-allowed" "$fixture/ledger-allowed.with-old";sudo sed -i '/^ledger-ci-old /d' "$fixture/ledger-allowed";if sudo env PATH="$fixture/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" "$activate" "$bundle" >/dev/null 2>&1;then echo "old ledger signer removal unexpectedly accepted" >&2;exit 1;fi;sudo mv "$fixture/ledger-allowed.with-old" "$fixture/ledger-allowed";sudo chown root:root "$fixture/ledger-allowed";sudo chmod 0444 "$fixture/ledger-allowed"
  echo "canonical hook checkpoint: activation and signer removal"
  [[ $(realpath /opt/steam-top/current) == "/opt/steam-top/releases/$RUNTIME_INSTALL_MANIFEST_SHA256" ]]||{ echo "runtime current mismatch" >&2;exit 1;}
  legacy_nonce=$(printf d%.0s {1..64});legacy_dir="$fixture/legacy";sudo install -d -o root -g root -m 0700 "$legacy_dir";sudo node - "$tmp/state/promotion-ready" "$legacy_dir/ready" "$legacy_nonce" <<'NODE'
const fs=require("fs"),r=JSON.parse(fs.readFileSync(process.argv[2],"utf8"));r.promotionNonce=process.argv[4];fs.writeFileSync(process.argv[3],JSON.stringify(r,null,2)+"\n");
NODE
  sudo sed 's/^\[target\]/[cutover-ci]/' "$tmp/service"|sudo tee "$fixture/pg_service.conf" >/dev/null;sudo install -o root -g root -m 0400 "$tmp/pass" "$fixture/pgpass";sudo chown root:root "$fixture/pg_service.conf";sudo chmod 0400 "$fixture/pg_service.conf"
  json_field(){ sudo node -e 'const [p,k]=process.argv.slice(1),x=JSON.parse(require("fs").readFileSync(p,"utf8"));process.stdout.write(String(x[k]))' "$1" "$2";};legacy_ready_sha=$(sudo "$root/scripts/portable-sha256.sh" digest "$legacy_dir/ready");printf '%s\n' "$legacy_ready_sha"|sudo tee "$legacy_dir/ready.sha256" >/dev/null;legacy_rows=$(json_field "$legacy_dir/ready" ledgerRows);legacy_system=$(json_field "$legacy_dir/ready" systemIdentifier);legacy_role=$(json_field "$legacy_dir/ready" appRole);legacy_target=$(json_field "$legacy_dir/ready" restoreTargetId);legacy_db=$(json_field "$legacy_dir/ready" database)
  sudo node - "$legacy_dir/receipt.json" "$legacy_ready_sha" "$legacy_nonce" "$legacy_system" "$legacy_db" "$legacy_role" "$legacy_target" "$legacy_rows" <<'NODE'
const fs=require("fs"),[out,readySha256,promotionNonce,systemIdentifier,database,appRole,restoreTargetId,rows]=process.argv.slice(2);fs.writeFileSync(out,JSON.stringify({schemaVersion:2,purpose:"production",readySha256,systemIdentifier,database,appRole,restoreTargetId,ledgerRows:Number(rows),databaseUrlSha256:"a".repeat(64),deploymentManifestSha256:"b".repeat(64),publicOrigin:"https://steam-top.test",publicSmoke:"passed",promotionNonce,createdAt:"2026-01-01T00:00:00.000Z"})+"\n");
NODE
  sudo ssh-keygen -Y sign -q -f "$fixture/legacy-key" -n steam-top-cutover "$legacy_dir/receipt.json";sudo chmod 0440 "$legacy_dir/receipt.json" "$legacy_dir/receipt.json.sig" "$legacy_dir/ready" "$legacy_dir/ready.sha256";psql "$url" -v nonce="$legacy_nonce" -v target="$legacy_target" -v role="$legacy_role" -v rows="$legacy_rows" -v system="$legacy_system" -f - <<<"insert into restore_control.finalize_outbox(nonce,restore_target_id,app_role,ledger_rows,ledger_hash,state,system_identifier,database_name) values(:'nonce',:'target'::uuid,:'role',:'rows',restore_control.deletion_audit_sha256(),'legacy-committed',:'system',current_database())" >/dev/null
  sudo cp "$legacy_dir/receipt.json.sig" "$legacy_dir/bad.sig";sudo sh -c "printf invalid-signature >'$legacy_dir/bad.sig'";sudo chmod 0440 "$legacy_dir/bad.sig";if sudo /opt/steam-top-bootstrap/import-legacy-cutover-current.sh "$cutover_nonce" "$legacy_nonce" "$legacy_dir/receipt.json" "$legacy_dir/bad.sig" "$legacy_dir/ready" "$legacy_dir/ready.sha256";then exit 1;fi;[[ $(psql "$url" -Atqc "select state from restore_control.finalize_outbox where nonce='$legacy_nonce'") == legacy-committed ]]
  sudo chmod 0444 "$legacy_dir/receipt.json";if sudo /opt/steam-top-bootstrap/import-legacy-cutover-current.sh "$cutover_nonce" "$legacy_nonce" "$legacy_dir/receipt.json" "$legacy_dir/receipt.json.sig" "$legacy_dir/ready" "$legacy_dir/ready.sha256";then exit 1;fi;sudo chmod 0440 "$legacy_dir/receipt.json"
  sudo node - "$legacy_dir/receipt.json" "$legacy_dir/wrong-target.json" <<'NODE'
const fs=require("fs"),x=require(process.argv[2]);x.restoreTargetId="00000000-0000-4000-8000-000000000001";fs.writeFileSync(process.argv[3],JSON.stringify(x)+"\n");
NODE
  sudo ssh-keygen -Y sign -q -f "$fixture/legacy-key" -n steam-top-cutover "$legacy_dir/wrong-target.json";sudo chmod 0440 "$legacy_dir/wrong-target.json" "$legacy_dir/wrong-target.json.sig";if sudo /opt/steam-top-bootstrap/import-legacy-cutover-current.sh "$cutover_nonce" "$legacy_nonce" "$legacy_dir/wrong-target.json" "$legacy_dir/wrong-target.json.sig" "$legacy_dir/ready" "$legacy_dir/ready.sha256";then exit 1;fi;[[ $(psql "$url" -Atqc "select state from restore_control.finalize_outbox where nonce='$legacy_nonce'") == legacy-committed ]]
  sudo /opt/steam-top-bootstrap/import-legacy-cutover-current.sh "$cutover_nonce" "$legacy_nonce" "$legacy_dir/receipt.json" "$legacy_dir/receipt.json.sig" "$legacy_dir/ready" "$legacy_dir/ready.sha256";[[ $(psql "$url" -Atqc "select state||'|'||(final_receipt_payload_b64 is not null)||'|'||(final_receipt_signature_b64 is not null)||'|'||(legacy_ready_payload_b64 is not null)||'|'||(legacy_ready_sha_text_b64 is not null)||'|'||(ledger_hash=restore_control.deletion_audit_sha256()) from restore_control.finalize_outbox where nonce='$legacy_nonce'") == 'verified|true|true|true|true|true' ]]
  echo "canonical hook checkpoint: legacy import"
  sudo install -o root -g root -m 0400 "$fixture/state-allowed" "$tmp/canonical-state-signers"
  sudo install -o root -g root -m 0400 "$tmp/cutover-signing" "$fixture/cutover-signing"
  sudo install -o root -g root -m 0444 "$tmp/cutover-signers" "$fixture/cutover-signers"
  finalize_env+=(PROTECTED_STATE_ALLOWED_SIGNERS_FILE="$tmp/canonical-state-signers" PROTECTED_STATE_SIGNER_ID=state-ci)
  sudo rm -f "$cutover" "$cutover.sig";record_env=(PROMOTE_PGSERVICE=target PGSERVICEFILE="$tmp/service" PGPASSFILE="$tmp/pass" CUTOVER_DATABASE_URL_FILE="$tmp/database-url" PUBLIC_ORIGIN="$public_origin" DEPLOYMENT_MANIFEST_SHA256="$manifest_sha" CUTOVER_SIGNING_KEY="$tmp/cutover-signing" CUTOVER_ALLOWED_SIGNERS_FILE="$tmp/cutover-signers" CUTOVER_SIGNER_ID="$cutover_signer" PRODUCTION_ENV_FILE="$tmp/production.env" HOST_DEPLOYMENT_RECEIPT_FILE="$tmp/host-receipt.json" HOST_DEPLOYMENT_RECEIPT_SIGNATURE="$tmp/host-receipt.json.sig" HOST_RECEIPT_ALLOWED_SIGNERS_FILE="$tmp/host-signers" HOST_RECEIPT_SIGNER_ID="$host_signer" PROTECTED_STATE_ALLOWED_SIGNERS_FILE="$tmp/canonical-state-signers" PROTECTED_STATE_SIGNER_ID=state-ci RUNTIME_INSTALL_MANIFEST_SHA256="$RUNTIME_INSTALL_MANIFEST_SHA256")
  sudo env "${record_env[@]}" CUTOVER_SIGNING_KEY="$fixture/cutover-signing" CUTOVER_ALLOWED_SIGNERS_FILE="$fixture/cutover-signers" /opt/steam-top-bootstrap/record-cutover-current.sh "$cutover_nonce" "$tmp/state/promotion-ready" "$cutover"
  echo "canonical hook checkpoint: cutover recorded"
  PGSERVICE=target psql -X -v ON_ERROR_STOP=1 -c 'select pg_advisory_lock(1937002751);select pg_sleep(3);select pg_advisory_unlock(1937002751)' >/dev/null & blocker=$!;for _ in $(seq 1 100);do [[ $(PGSERVICE=target psql -X -Atqc "select exists(select 1 from pg_locks where locktype='advisory' and granted)") == t ]]&&break;sleep .02;done;sudo env "${finalize_env[@]}" /opt/steam-top-bootstrap/finalize-current.sh "$cutover_nonce" "$tmp/state/promotion-ready" "$cutover" "$cutover.sig" & finalizer=$!;for _ in $(seq 1 100);do sudo flock -n /var/lock/steam-top-production.lock true >/dev/null 2>&1||break;sleep .02;done;set +e;sudo "$bootstrap/activate-production-state.sh" "$bundle" >/dev/null 2>&1;activation_b=$?;set -e;[[ $activation_b -eq 75 ]]||{ echo "expected activation B to be locked out" >&2;exit 1;};wait "$blocker";wait "$finalizer";[[ $(psql "$url" -Atqc 'select count(*) from restore_control.promotion_audit') == 1 ]];return 0
fi
for entry in activate-production-state.sh record-cutover-current.sh finalize-current.sh;do [[ -x "$bootstrap/$entry" ]]||exit 1;done;[[ -x "$script_dir/promote-restored-target.sh" ]];canonical_existing_database=${CANONICAL_EXISTING_DATABASE:-$(psql "$TEST_DATABASE_URL" -Atqc 'select current_database()')};CANONICAL_CUTOVER_HOOK="$root/infra/backup/test-canonical-cutover-full.sh" CANONICAL_EXISTING_DATABASE="$canonical_existing_database" CANONICAL_APP_ROLE=${CANONICAL_APP_ROLE:-steam_top_app} CANONICAL_PUBLIC_ORIGIN=${CANONICAL_PUBLIC_ORIGIN:-https://localhost} "$script_dir/test-promotion-full.sh"
