import { createHash, createHmac, randomBytes, timingSafeEqual } from "node:crypto";
import { z } from "zod";

const MAX_TOKEN_BYTES = 2_048, MAX_LIFETIME_MS = 300_000;
const B64URL = /^[A-Za-z0-9_-]+$/u;
const headerSchema = z.strictObject({ alg: z.literal("HS256"), typ: z.literal("JWT"), kid: z.string().min(1).max(32), v: z.literal(1) });
const claimsSchema = z.strictObject({ v:z.literal(1), iat:z.number().int().nonnegative(), exp:z.number().int().positive(), jti:z.string().regex(/^[A-Za-z0-9_-]{43}$/u), aud:z.string().min(1).max(64) });
const digest = (value:string) => createHash("sha256").update(value,"ascii").digest("hex");
const safeEqual = (a:string,b:string) => { const x=Buffer.from(a,"hex"),y=Buffer.from(b,"hex"); return x.length===32&&y.length===32&&timingSafeEqual(x,y); };

export type StoredWebClipExchange = Readonly<{ identityId:string; sessionId:string; tokenHash:string; committedAt:Date }>;
export interface TokenNonceStore {
  readonly durable?:boolean;
  issue(input:Readonly<{jtiHash:string;deviceId:string;issuedAt:Date;expiresAt:Date}>):Promise<void>;
  lookup(jtiHash:string,now:Date):Promise<string|null>;
  exchange<T extends StoredWebClipExchange>(input:Readonly<{jtiHash:string;attemptHash:string;now:Date}>,create:(transaction?:unknown)=>Promise<T>):Promise<Readonly<{status:"committed"|"recovered";result:T}>|Readonly<{status:"replay"|"missing"}>>;
  pruneExpired(before:Date,batchSize:number):Promise<number>;
}
type RecordValue={deviceId:string;issuedAt:Date;expiresAt:Date;usedAt?:Date;attemptHash?:string;result?:StoredWebClipExchange};
export class InMemoryTokenNonceStore implements TokenNonceStore {
  readonly durable=false; readonly #records=new Map<string,RecordValue>(); #tail=Promise.resolve();
  async issue(input:Readonly<{jtiHash:string;deviceId:string;issuedAt:Date;expiresAt:Date}>){if(this.#records.has(input.jtiHash))throw new Error("DEVICE_TOKEN_NONCE_COLLISION");this.#records.set(input.jtiHash,{...input});}
  async lookup(key:string,now:Date){const r=this.#records.get(key);return !r||r.expiresAt<=now?null:r.deviceId;}
  async exchange<T extends StoredWebClipExchange>(input:Readonly<{jtiHash:string;attemptHash:string;now:Date}>,create:(transaction?:unknown)=>Promise<T>){let release!:()=>void;const prior=this.#tail;this.#tail=new Promise<void>(r=>{release=r;});await prior;try{const row=this.#records.get(input.jtiHash);if(!row||row.expiresAt<=input.now)return{status:"missing" as const};if(row.usedAt){if(!row.attemptHash||!safeEqual(row.attemptHash,input.attemptHash)||!row.result)return{status:"replay" as const};return{status:"recovered" as const,result:row.result as T};}const result=await create();row.usedAt=input.now;row.attemptHash=input.attemptHash;row.result=result;return{status:"committed" as const,result};}finally{release();}}
  async pruneExpired(before:Date,batch:number){let n=0;for(const[k,r]of this.#records){if(n>=batch)break;if(r.expiresAt<=before){this.#records.delete(k);n++;}}return n;}
}
const encode=(v:unknown)=>Buffer.from(JSON.stringify(v),"utf8").toString("base64url");
function decode(value:string):unknown{if(!B64URL.test(value))throw new Error("INVALID_DEVICE_TOKEN");const b=Buffer.from(value,"base64url");if(b.toString("base64url")!==value)throw new Error("INVALID_DEVICE_TOKEN");try{return JSON.parse(b.toString("utf8"));}catch{throw new Error("INVALID_DEVICE_TOKEN");}}
export type VerifiedWebClipToken=Readonly<{deviceId:string;expiresAt:Date}>;
export type WebClipExchangeHandle=Readonly<{deviceId:string;expiresAt:Date;attemptHash:string;cookieToken:string;tokenHash:string}>;
export class WebClipTokenService {
  readonly #keys:Readonly<Record<string,Uint8Array>>;readonly #activeKeyId:string;readonly #audience:string;readonly #store:TokenNonceStore;readonly #now:()=>number;readonly #exchangeKey:Uint8Array;
  readonly #verified=new WeakMap<object,Readonly<{jti:string;jtiHash:string}>>();readonly #handles=new WeakMap<object,string>();
  constructor(input:Readonly<{keys:Readonly<Record<string,Uint8Array>>;activeKeyId:string;audience:string;nonceStore:TokenNonceStore;exchangeKey?:Uint8Array;now?:()=>number;production?:boolean}>){if(!input.keys[input.activeKeyId])throw new TypeError("WEBCLIP_ACTIVE_KEY_MISSING");for(const s of Object.values(input.keys))if(s.byteLength<32)throw new TypeError("WEBCLIP_SECRET_TOO_SHORT");const ek=input.exchangeKey??new Uint8Array(32).fill(165);if(ek.byteLength<32)throw new TypeError("WEBCLIP_EXCHANGE_SECRET_TOO_SHORT");for(const s of Object.values(input.keys))if(Buffer.from(s).equals(Buffer.from(ek)))throw new TypeError("WEBCLIP_EXCHANGE_KEY_REUSED");if((input.production??process.env.NODE_ENV==="production")&&input.nonceStore.durable!==true)throw new TypeError("WEBCLIP_DURABLE_NONCE_STORE_REQUIRED");this.#keys=Object.freeze(Object.fromEntries(Object.entries(input.keys).map(([k,v])=>[k,Uint8Array.from(v)])));this.#activeKeyId=input.activeKeyId;this.#exchangeKey=Uint8Array.from(ek);this.#audience=z.string().min(1).max(64).parse(input.audience);this.#store=input.nonceStore;this.#now=input.now??Date.now;}
  async issue(deviceId:string,lifetimeMs=MAX_LIFETIME_MS){const clean=z.string().trim().min(1).max(128).refine(v=>!/[\u0000-\u001f\u007f]/u.test(v)).parse(deviceId);if(!Number.isSafeInteger(lifetimeMs)||lifetimeMs<1||lifetimeMs>MAX_LIFETIME_MS)throw new TypeError("WEBCLIP_LIFETIME_INVALID");const iat=this.#now(),exp=iat+lifetimeMs,jti=randomBytes(32).toString("base64url");await this.#store.issue({jtiHash:digest(jti),deviceId:clean,issuedAt:new Date(iat),expiresAt:new Date(exp)});const h=encode({alg:"HS256",typ:"JWT",kid:this.#activeKeyId,v:1}),b=encode({v:1,iat,exp,jti,aud:this.#audience}),s=createHmac("sha256",this.#keys[this.#activeKeyId]!).update(`${h}.${b}`,"ascii").digest("base64url");return`${h}.${b}.${s}`;}
  async inspect(token:unknown){if(typeof token!=="string"||Buffer.byteLength(token,"utf8")>MAX_TOKEN_BYTES)throw new Error("INVALID_DEVICE_TOKEN");const p=token.split(".");if(p.length!==3)throw new Error("INVALID_DEVICE_TOKEN");const[h,b,s]=p as[string,string,string],head=headerSchema.safeParse(decode(h)),claims=claimsSchema.safeParse(decode(b));if(!head.success||!claims.success||!B64URL.test(s))throw new Error("INVALID_DEVICE_TOKEN");const key=this.#keys[head.data.kid];if(!key)throw new Error("INVALID_DEVICE_TOKEN");const expected=createHmac("sha256",key).update(`${h}.${b}`,"ascii").digest(),received=Buffer.from(s,"base64url");if(received.toString("base64url")!==s||received.length!==expected.length||!timingSafeEqual(received,expected))throw new Error("INVALID_DEVICE_TOKEN");const now=this.#now();if(claims.data.aud!==this.#audience||claims.data.exp-claims.data.iat>MAX_LIFETIME_MS||claims.data.iat>now+30_000)throw new Error("INVALID_DEVICE_TOKEN");if(claims.data.exp<=now)throw new Error("DEVICE_TOKEN_EXPIRED");const jtiHash=digest(claims.data.jti),deviceId=await this.#store.lookup(jtiHash,new Date(now));if(!deviceId)throw new Error("DEVICE_TOKEN_REPLAYED");const verified=Object.freeze({deviceId,expiresAt:new Date(claims.data.exp)});this.#verified.set(verified,{jti:claims.data.jti,jtiHash});return verified;}
  prepareExchange(verified:VerifiedWebClipToken,attempt:string){const own=this.#verified.get(verified as object),raw=Buffer.from(attempt,"base64url");if(!own||!B64URL.test(attempt)||raw.length!==32||raw.toString("base64url")!==attempt)throw new Error("INVALID_WEBCLIP_ATTEMPT");const cookieToken=createHmac("sha256",this.#exchangeKey).update(own.jti,"ascii").update("\0","ascii").update(attempt,"ascii").digest("base64url");const handle=Object.freeze({deviceId:verified.deviceId,expiresAt:verified.expiresAt,attemptHash:digest(attempt),cookieToken,tokenHash:digest(cookieToken)});this.#handles.set(handle,own.jtiHash);return handle;}
  async exchange<T extends StoredWebClipExchange>(handle:WebClipExchangeHandle,create:(transaction?:unknown)=>Promise<T>){const jtiHash=this.#handles.get(handle as object);if(!jtiHash)throw new Error("INVALID_WEBCLIP_EXCHANGE_HANDLE");return this.#store.exchange({jtiHash,attemptHash:handle.attemptHash,now:new Date(this.#now())},create);}
  async pruneExpired(batch=500){return this.#store.pruneExpired(new Date(this.#now()),batch);}
}
